# -*- coding: utf-8 -*-
"""chronic_constipation_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-D1fifjgpjqC7DOkhfC7xgqP-YSa7A-K
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================
# Output types
# =========================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)

@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)

@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None

Output = Action | DataRequest | Stop


# =========================
# Audit trail + overrides
# =========================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================
# Context
# =========================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key: str, default=None):
        return self.data.get(key, default)

    def set(self, key: str, value: Any):
        self.data[key] = value

    def apply_override(self, node: str, field: str, current_value: Any) -> Any:
        candidates = [o for o in self.overrides if o.target_node == node and o.field == field]
        if not candidates:
            return current_value
        newest = max(candidates, key=lambda o: o.created_at)
        return newest.new_value

    def log(self, node: str, decision: str, used_inputs: Dict[str, Any], outputs: List[Output]):
        def ser_action(a: Action) -> Dict[str, Any]:
            return {
                "type": "action",
                "code": a.code,
                "label": a.label,
                "urgency": a.urgency,
                "details": a.details,
                "override_options": a.override_options,
                "display": a.display,
            }

        def ser(o: Output) -> Dict[str, Any]:
            if isinstance(o, Action):
                return ser_action(o)
            if isinstance(o, DataRequest):
                return {
                    "type": "data_request",
                    "blocking_node": o.blocking_node,
                    "missing_fields": o.missing_fields,
                    "message": o.message,
                    "urgency_context": o.urgency_context,
                    "suggested_actions": [ser_action(a) for a in o.suggested_actions],
                }
            if isinstance(o, Stop):
                return {
                    "type": "stop",
                    "reason": o.reason,
                    "urgency": o.urgency,
                    "actions": [ser_action(a) for a in o.actions],
                }
            return {"type": "unknown"}

        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=used_inputs,
                outputs=[ser(x) for x in outputs],
            )
        )


# =========================
# Engine
# =========================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None

NodeFn = Callable[[Context], NodeResult]

@dataclass
class Node:
    node_id: str
    fn: NodeFn

class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current is not None:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break
            if current not in self.nodes:
                outputs.append(Stop(reason=f"Engine error: unknown node '{current}'"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (DataRequest, Stop)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# ==========================================================
# CHRONIC CONSTIPATION ENGINE
# ==========================================================

def constipation_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -------------------------
    # Helpers
    # -------------------------

    def _derive_constipation_criteria(ctx: Context) -> Dict[str, Any]:
        months = ctx.get("symptom_months_present_last_6")
        sbm = ctx.get("spontaneous_bowel_movements_per_week")
        hard = ctx.get("hard_or_lumpy_stool_percent")
        straining = ctx.get("straining_percent")
        incomplete = ctx.get("incomplete_evacuation_percent")
        blockage = ctx.get("anorectal_blockage_percent")
        manual = ctx.get("manual_maneuvers_percent")

        missing = []
        if months is None:
            missing.append("symptom_months_present_last_6")
        for k, v in {
            "spontaneous_bowel_movements_per_week": sbm,
            "hard_or_lumpy_stool_percent": hard,
            "straining_percent": straining,
            "incomplete_evacuation_percent": incomplete,
            "anorectal_blockage_percent": blockage,
            "manual_maneuvers_percent": manual,
        }.items():
            if v is None:
                missing.append(k)

        if missing:
            return {
                "blocked": True,
                "missing": missing,
                "criteria_met": None,
            }

        c1 = sbm <= 3
        c2 = hard > 25
        c3 = straining > 25
        c4 = incomplete > 25
        c5 = blockage > 25
        c6 = manual > 25

        count = sum([c1, c2, c3, c4, c5, c6])
        criteria_met = bool(months >= 3 and count >= 2)

        return {
            "blocked": False,
            "missing": [],
            "criterion_low_bm_frequency": c1,
            "criterion_hard_stool": c2,
            "criterion_straining": c3,
            "criterion_incomplete_evacuation": c4,
            "criterion_anorectal_blockage": c5,
            "criterion_manual_maneuvers": c6,
            "constipation_symptom_count": count,
            "criteria_met": criteria_met,
            "symptom_months_present_last_6": months,
        }

    def _alarm_features_present(ctx: Context) -> Dict[str, Any]:
        family_crc = bool(ctx.get("family_history_crc_first_degree"))
        weight_loss = ctx.get("weight_loss_percent_6_to_12_months")
        bowel_change = bool(ctx.get("sudden_or_progressive_change_in_bowel_habits"))
        visible_blood = bool(ctx.get("visible_blood_in_stool"))
        suspicious_mass = bool(ctx.get("suspicious_anal_canal_mass_or_irregularity"))
        ida = bool(ctx.get("iron_deficiency_anemia_present"))

        weight_loss_alarm = False
        if weight_loss is not None:
            weight_loss_alarm = weight_loss > 5.0

        present = bool(
            family_crc
            or weight_loss_alarm
            or bowel_change
            or visible_blood
            or suspicious_mass
            or ida
        )

        return {
            "alarm_features_present": present,
            "family_history_crc_first_degree": family_crc,
            "weight_loss_alarm": weight_loss_alarm,
            "sudden_or_progressive_change_in_bowel_habits": bowel_change,
            "visible_blood_in_stool": visible_blood,
            "suspicious_anal_canal_mass_or_irregularity": suspicious_mass,
            "iron_deficiency_anemia_present": ida,
        }

    def _defecatory_dysfunction_features(ctx: Context) -> Dict[str, Any]:
        traumatic = bool(ctx.get("traumatic_perineal_injury_history"))
        blockage = bool(ctx.get("outlet_blockage_sensation"))
        wiggle = bool(ctx.get("needs_to_wiggle_or_rotate_on_toilet"))
        present = bool(traumatic or blockage or wiggle)
        return {
            "defecatory_dysfunction_features_present": present,
            "traumatic_perineal_injury_history": traumatic,
            "outlet_blockage_sensation": blockage,
            "needs_to_wiggle_or_rotate_on_toilet": wiggle,
        }

    # -------------------------
    # Nodes
    # -------------------------

    def node_confirm_criteria(ctx: Context) -> NodeResult:
        node_id = "Confirm_Diagnostic_Criteria"

        d = _derive_constipation_criteria(ctx)
        if d["blocked"]:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=d["missing"],
                message="Need raw symptom data to determine whether chronic constipation criteria are met.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_CONSTIPATION_RAW_SYMPTOMS",
                        label="Capture raw stool frequency and symptom percentages",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": d["missing"]}, [dr])
            return NodeResult(outputs=[dr])

        ctx.set("criterion_low_bm_frequency", d["criterion_low_bm_frequency"])
        ctx.set("criterion_hard_stool", d["criterion_hard_stool"])
        ctx.set("criterion_straining", d["criterion_straining"])
        ctx.set("criterion_incomplete_evacuation", d["criterion_incomplete_evacuation"])
        ctx.set("criterion_anorectal_blockage", d["criterion_anorectal_blockage"])
        ctx.set("criterion_manual_maneuvers", d["criterion_manual_maneuvers"])
        ctx.set("constipation_symptom_count", d["constipation_symptom_count"])
        ctx.set("chronic_constipation_criteria_met", d["criteria_met"])

        if not d["criteria_met"]:
            stop = Stop(
                reason="Chronic constipation criteria are not met.",
                actions=[
                    Action(
                        code="CONSTIPATION_CRITERIA_NOT_MET",
                        label="Reassess symptoms and consider alternative diagnosis if symptoms change over time.",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 99},
                    )
                ],
            )
            ctx.log(node_id, "CRITERIA_NOT_MET", {"symptom_count": d["constipation_symptom_count"], "months": d["symptom_months_present_last_6"]}, [stop])
            return NodeResult(outputs=[stop])

        out = [
            Action(
                code="CONSTIPATION_CRITERIA_MET",
                label="Chronic constipation diagnostic criteria met.",
                details={
                    "supported_by": [
                        f"{d['constipation_symptom_count']} constipation criteria met",
                        f"Symptoms present for {d['symptom_months_present_last_6']} of last 6 months",
                    ],
                    "criterion_low_bm_frequency": d["criterion_low_bm_frequency"],
                    "criterion_hard_stool": d["criterion_hard_stool"],
                    "criterion_straining": d["criterion_straining"],
                    "criterion_incomplete_evacuation": d["criterion_incomplete_evacuation"],
                    "criterion_anorectal_blockage": d["criterion_anorectal_blockage"],
                    "criterion_manual_maneuvers": d["criterion_manual_maneuvers"],
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
            )
        ]
        ctx.log(node_id, "CRITERIA_MET", {"symptom_count": d["constipation_symptom_count"]}, out)
        return NodeResult(outputs=out, next_node="IBSC_Screen")

    def node_ibsc_screen(ctx: Context) -> NodeResult:
        node_id = "IBSC_Screen"

        predominant = ctx.get("predominant_pain_or_bloating")
        if predominant is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["predominant_pain_or_bloating"],
                message="Need to know whether pain and/or bloating are the predominant symptoms to determine if IBS-C pathway should be followed.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_PREDOMINANT_PAIN_BLOATING",
                        label="Document whether pain and/or bloating are predominant symptoms",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 21},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["predominant_pain_or_bloating"]}, [dr])
            return NodeResult(outputs=[dr])

        route_to_ibsc = bool(predominant)
        route_to_ibsc = ctx.apply_override(node_id, "route_to_ibsc", route_to_ibsc)
        ctx.set("route_to_ibsc", route_to_ibsc)

        if route_to_ibsc:
            stop = Stop(
                reason="Predominant pain and/or bloating present; follow IBS-C pathway instead.",
                actions=[
                    Action(
                        code="ROUTE_IBSC",
                        label="Route to IBS-C pathway",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 5},
                    )
                ],
            )
            ctx.log(node_id, "ROUTE_IBSC", {"predominant_pain_or_bloating": predominant}, [stop])
            return NodeResult(outputs=[stop])

        out = [
            Action(
                code="IBSC_NOT_PRIMARY",
                label="Pain and/or bloating are not predominant; continue chronic constipation pathway.",
                details={"supported_by": ["Predominant pain and/or bloating not identified"]},
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 15},
            )
        ]
        ctx.log(node_id, "CONTINUE_CONSTIPATION_PATHWAY", {"predominant_pain_or_bloating": predominant}, out)
        return NodeResult(outputs=out, next_node="Medical_History")

    def node_history(ctx: Context) -> NodeResult:
        node_id = "Medical_History"
        actions: List[Action] = []

        dd = _defecatory_dysfunction_features(ctx)
        ctx.set("defecatory_dysfunction_features_present", dd["defecatory_dysfunction_features_present"])

        actions.append(
            Action(
                code="HISTORY_REVIEWED",
                label="Review duration/progression, associated symptoms, triggers, and prior treatments.",
                details={
                    "supported_by": ["Trend of symptoms is important", "Past laxative and treatment history informs management"],
                    "symptom_duration_trend": ctx.get("symptom_duration_trend"),
                    "abdominal_pain_present": ctx.get("abdominal_pain_present"),
                    "bloating_present": ctx.get("bloating_present"),
                    "distention_present": ctx.get("distention_present"),
                    "past_laxative_use": ctx.get("past_laxative_use"),
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20},
            )
        )

        if dd["defecatory_dysfunction_features_present"]:
            actions.append(
                Action(
                    code="DEFECATORY_DYSFUNCTION_FEATURES_PRESENT",
                    label="Features suggestive of defecatory dysfunction are present.",
                    details={
                        "supported_by": [
                            "These features support later specialty evaluation if needed",
                            "They do not change initial management pathway"
                        ],
                        **dd,
                    },
                    display={"role": "modifier", "group_under": "FINAL_RECOMMENDATION", "show_as_standalone": False, "sort_priority": 70},
                )
            )

        ctx.log(node_id, "HISTORY_REVIEWED", {"defecatory_dysfunction_features_present": dd["defecatory_dysfunction_features_present"]}, actions)
        return NodeResult(outputs=actions, next_node="Physical_Exam")

    def node_physical_exam(ctx: Context) -> NodeResult:
        node_id = "Physical_Exam"
        actions: List[Output] = []

        abdominal_exam_done = ctx.get("abdominal_exam_done")
        anorectal_exam_done = ctx.get("digital_anorectal_exam_done")

        if abdominal_exam_done is None or anorectal_exam_done is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=[k for k, v in {
                    "abdominal_exam_done": abdominal_exam_done,
                    "digital_anorectal_exam_done": anorectal_exam_done,
                }.items() if v is None],
                message="Abdominal and digital anorectal examination are recommended as part of the pathway review.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_PHYSICAL_EXAM_STATUS",
                        label="Document abdominal and digital anorectal examination status",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 22},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"abdominal_exam_done": abdominal_exam_done, "digital_anorectal_exam_done": anorectal_exam_done}, [dr])
            return NodeResult(outputs=[dr])

        out = [
            Action(
                code="PHYSICAL_EXAM_REVIEWED",
                label="Physical examination documented.",
                details={
                    "supported_by": ["Abdominal and anorectal examination status captured"],
                    "abdominal_exam_done": abdominal_exam_done,
                    "digital_anorectal_exam_done": anorectal_exam_done,
                    "suspicious_anal_canal_mass_or_irregularity": ctx.get("suspicious_anal_canal_mass_or_irregularity"),
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 25},
            )
        ]
        ctx.log(node_id, "PHYSICAL_EXAM_REVIEWED", {"abdominal_exam_done": abdominal_exam_done, "digital_anorectal_exam_done": anorectal_exam_done}, out)
        return NodeResult(outputs=out, next_node="Alarm_Features")

    def node_alarm_features(ctx: Context) -> NodeResult:
        node_id = "Alarm_Features"

        alarms = _alarm_features_present(ctx)
        alarm_present = alarms["alarm_features_present"]
        alarm_present = ctx.apply_override(node_id, "alarm_features_present", alarm_present)
        ctx.set("alarm_features_present", alarm_present)

        if alarm_present:
            stop = Stop(
                reason="Alarm feature(s) identified; refer for consultation/endoscopy.",
                actions=[
                    Action(
                        code="REFER_CONSULT_ENDOSCOPY",
                        label="Refer for consultation/endoscopy and include all alarm features in the referral.",
                        details={
                            "supported_by": [
                                "At least one alarm feature is present",
                            ],
                            **alarms,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 5},
                    )
                ],
            )
            ctx.log(node_id, "ALARM_FEATURES_PRESENT", alarms, [stop])
            return NodeResult(outputs=[stop])

        out = [
            Action(
                code="NO_ALARM_FEATURES",
                label="No alarm features identified; continue conservative pathway management.",
                details={
                    "supported_by": ["No alarm features identified"],
                    **alarms,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30},
            )
        ]
        ctx.log(node_id, "NO_ALARM_FEATURES", alarms, out)
        return NodeResult(outputs=out, next_node="Optimize_Secondary_Causes")

    def node_optimize_secondary(ctx: Context) -> NodeResult:
        node_id = "Optimize_Secondary_Causes"
        actions: List[Action] = []

        for key, label in [
            ("medication_history_reviewed", "Review medications including OTCs and supplements."),
            ("secondary_causes_medical_conditions_reviewed", "Review underlying medical conditions and activity level."),
            ("diet_fluid_reviewed", "Review diet and fluid intake."),
            ("bowel_regimen_reviewed", "Review bowel regimen, especially in elderly patients."),
        ]:
            if ctx.get(key) is not True:
                actions.append(
                    Action(
                        code=f"REVIEW_{key.upper()}",
                        label=label,
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 35},
                    )
                )

        if not actions:
            actions = [
                Action(
                    code="SECONDARY_CAUSES_REVIEWED",
                    label="Secondary causes and contributors reviewed/optimized.",
                    details={"supported_by": ["Medication, medical conditions, activity, diet/fluid, and bowel regimen reviewed"]},
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 35},
                )
            ]

        ctx.log(node_id, "SECONDARY_CAUSES_REVIEWED", {}, actions)
        return NodeResult(outputs=actions, next_node="Baseline_Investigations")

    def node_baseline_investigations(ctx: Context) -> NodeResult:
        node_id = "Baseline_Investigations"
        actions: List[Action] = []

        if ctx.get("cbc_recent_available") is not True:
            actions.append(Action(
                code="CONSIDER_CBC",
                label="Consider CBC if no recent result is available.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
            ))

        for key, label in [
            ("glucose_done", "Consider glucose if clinically indicated."),
            ("creatinine_done", "Consider creatinine if clinically indicated."),
            ("calcium_albumin_done", "Consider calcium/albumin if clinically indicated."),
            ("tsh_done", "Consider TSH if clinically indicated."),
            ("celiac_screen_done", "Consider celiac disease screen if clinically indicated."),
        ]:
            if ctx.get(key) is not True:
                actions.append(Action(
                    code=f"CONSIDER_{key.upper()}",
                    label=label,
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
                ))

        if ctx.get("elderly_patient") is True and ctx.get("abdominal_radiograph_done") is not True:
            actions.append(Action(
                code="CONSIDER_ABDOMINAL_RADIOGRAPH",
                label="Consider abdominal radiograph in elderly patient.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 41},
            ))

        if ctx.get("celiac_screen_positive") is True:
            stop = Stop(
                reason="Positive celiac disease screen identified; refer for specialist assessment.",
                actions=[
                    Action(
                        code="REFER_POSITIVE_CELIAC_SCREEN",
                        label="Refer due to positive celiac disease screen.",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 6},
                    )
                ],
            )
            ctx.log(node_id, "POSITIVE_CELIAC_SCREEN", {"celiac_screen_positive": True}, [stop])
            return NodeResult(outputs=actions + [stop])

        ctx.log(node_id, "BASELINE_INVESTIGATIONS_REVIEWED", {}, actions)
        return NodeResult(outputs=actions, next_node="Management_Assessment")

    def node_management(ctx: Context) -> NodeResult:
        node_id = "Management_Assessment"

        unsat = ctx.get("unsatisfactory_response_after_3_to_6_months")
        months = ctx.get("management_months_trialed")

        if unsat is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["unsatisfactory_response_after_3_to_6_months"],
                message="Need management response status to determine whether referral is appropriate after therapy.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_MANAGEMENT_RESPONSE",
                        label="Document whether response after 3–6 months of multi-pronged therapy is unsatisfactory",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["unsatisfactory_response_after_3_to_6_months"]}, [dr])
            return NodeResult(outputs=[dr])

        actions: List[Output] = []

        if unsat is True:
            actions.append(
                Action(
                    code="UNSATISFACTORY_RESPONSE",
                    label="Unsatisfactory response after management trial.",
                    details={
                        "supported_by": [
                            "Management failure is subjective but pathway suggests 3–6 months of titrated, multi-pronged therapy"
                        ],
                        "management_months_trialed": months,
                        "advice_service_considered": ctx.get("advice_service_considered"),
                    },
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 55},
                )
            )

            stop = Stop(
                reason="Unsatisfactory response after management trial; referral can be considered.",
                actions=[
                    Action(
                        code="REFER_AFTER_FAILED_MANAGEMENT",
                        label="Consider advice service and refer if appropriate.",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 7},
                    )
                ],
            )
            ctx.log(node_id, "UNSATISFACTORY_RESPONSE", {"management_months_trialed": months, "unsatisfactory_response_after_3_to_6_months": unsat}, actions + [stop])
            return NodeResult(outputs=actions + [stop])

        actions.append(
            Action(
                code="CONTINUE_MEDICAL_HOME_CARE",
                label="Continue management in the Patient Medical Home.",
                details={
                    "supported_by": ["No alarm features and no unsatisfactory response after management trial"],
                    "management_months_trialed": months,
                },
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 8},
            )
        )
        ctx.log(node_id, "SATISFACTORY_RESPONSE", {"management_months_trialed": months, "unsatisfactory_response_after_3_to_6_months": unsat}, actions)
        return NodeResult(outputs=actions, next_node="Finalize")

    def node_finalize(ctx: Context) -> NodeResult:
        node_id = "Finalize"
        stop = Stop(
            reason="Chronic constipation pathway complete.",
            actions=[
                Action(
                    code="FINAL_RECOMMENDATION",
                    label="Finalize care plan based on pathway findings.",
                    display={"role": "primary_decision", "show_as_standalone": False, "sort_priority": 100},
                )
            ],
        )
        ctx.log(node_id, "STOP", {}, [stop])
        return NodeResult(outputs=[stop])

    # Register nodes
    nodes["Confirm_Diagnostic_Criteria"] = Node("Confirm_Diagnostic_Criteria", node_confirm_criteria)
    nodes["IBSC_Screen"] = Node("IBSC_Screen", node_ibsc_screen)
    nodes["Medical_History"] = Node("Medical_History", node_history)
    nodes["Physical_Exam"] = Node("Physical_Exam", node_physical_exam)
    nodes["Alarm_Features"] = Node("Alarm_Features", node_alarm_features)
    nodes["Optimize_Secondary_Causes"] = Node("Optimize_Secondary_Causes", node_optimize_secondary)
    nodes["Baseline_Investigations"] = Node("Baseline_Investigations", node_baseline_investigations)
    nodes["Management_Assessment"] = Node("Management_Assessment", node_management)
    nodes["Finalize"] = Node("Finalize", node_finalize)

    return PathwayEngine(nodes=nodes, start_node="Confirm_Diagnostic_Criteria")


def run_constipation_pathway(patient_data: Dict[str, Any], overrides: Optional[List[Override]] = None):
    engine = constipation_build_engine()
    ctx = Context(data=dict(patient_data), overrides=overrides or [])
    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx.overrides
