# -*- coding: utf-8 -*-
"""chronic_abdominal_pain_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z10FrqgGggw5hxx1z9XKWUEH40OcLw0a
"""

"""
========================================================
PATHWAY FILE: Chronic Abdominal Pain / CAPS
========================================================

Design goals
- Same architecture as other pathway engines
- Progressive decision gating: run as far as possible with partial data
- UI-friendly outputs: Action / DataRequest / Stop
- Audit log support
- Override capability
- Based on Alberta Chronic Abdominal Pain Primary Care Pathway
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def add_override(self, target_node: str, field: str, new_value: Any, reason: str):
        old_value = self.data.get(field, None)
        self.overrides.append(
            Override(
                target_node=target_node,
                field=field,
                old_value=old_value,
                new_value=new_value,
                reason=reason,
            )
        )

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# CHRONIC ABDOMINAL PAIN / CAPS PATHWAY IMPLEMENTATION
# =========================================================

def chronic_abdominal_pain_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # Helper functions
    # -----------------------------------------------------

    def _bool(v) -> bool:
        return bool(v) is True

    def _any_true(values: List[Optional[bool]]) -> bool:
        return any(v is True for v in values)

    def _all_known_and_true(values: List[Optional[bool]]) -> bool:
        return all(v is True for v in values)

    def _missing(ctx: Context, fields: List[str]) -> List[str]:
        return [f for f in fields if ctx.get(f) is None]

    def _abnormal_baseline_investigations(ctx: Context) -> bool:
        flags = [
            ctx.get("cbc_abnormal"),
            ctx.get("electrolytes_abnormal"),
            ctx.get("creatinine_abnormal"),
            ctx.get("liver_tests_abnormal"),
            ctx.get("lipase_abnormal"),
            ctx.get("crp_abnormal"),
            ctx.get("ferritin_or_tsat_abnormal"),
            ctx.get("c_difficile_positive"),
            ctx.get("ova_parasites_positive"),
            ctx.get("celiac_screen_positive"),
            ctx.get("tsh_abnormal"),
            ctx.get("h_pylori_positive"),
            ctx.get("urinalysis_abnormal"),
            ctx.get("pregnancy_test_positive"),
            ctx.get("abdominopelvic_ultrasound_abnormal"),
        ]
        return _any_true(flags)

    def _alternate_diagnosis_or_secondary_cause_present(ctx: Context) -> bool:
        flags = [
            ctx.get("referred_pain_other_system"),
            ctx.get("culprit_medication_present"),
            ctx.get("dietary_trigger_or_allergen_present"),
            ctx.get("abdominal_wall_pain_suspected"),
            ctx.get("cannabinoid_related_pain_suspected"),
            ctx.get("narcotic_bowel_suspected"),
            ctx.get("significant_psychological_comorbidity_predominant"),
            ctx.get("organic_condition_already_identified"),
        ]
        return _any_true(flags)

    def _management_started(ctx: Context) -> bool:
        flags = [
            ctx.get("patient_reassurance_done"),
            ctx.get("lifestyle_modification_started"),
            ctx.get("dietary_modification_started"),
            ctx.get("psychological_referral_or_therapy_started"),
            ctx.get("pharmacologic_caps_therapy_started"),
        ]
        return _any_true(flags)

    # -----------------------------------------------------
    # Node 1 – CAPS diagnostic criteria
    # -----------------------------------------------------
    def node_diagnostic_criteria(ctx: Context) -> NodeResult:
        node_id = "Diagnostic_Criteria"

        required_fields = [
            "continuous_or_near_continuous_pain",
            "pain_duration_months_at_criteria_level",
            "symptom_onset_months_ago",
            "pain_only_occasional_relation_to_physiologic_events",
            "pain_limits_daily_function",
            "pain_not_feigned",
            "not_explained_by_other_condition_initial_assessment",
        ]
        missing = _missing(ctx, required_fields)

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need core Rome IV / CAPS diagnostic criteria fields to determine whether chronic abdominal pain pathway applies.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_CAPS_DIAGNOSTIC_CRITERIA",
                        label="Capture CAPS diagnostic criteria and symptom timing",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult([dr])

        meets = (
            _bool(ctx.get("continuous_or_near_continuous_pain"))
            and float(ctx.get("pain_duration_months_at_criteria_level")) >= 3
            and float(ctx.get("symptom_onset_months_ago")) >= 6
            and _bool(ctx.get("pain_only_occasional_relation_to_physiologic_events"))
            and _bool(ctx.get("pain_limits_daily_function"))
            and _bool(ctx.get("pain_not_feigned"))
            and _bool(ctx.get("not_explained_by_other_condition_initial_assessment"))
        )

        meets = ctx.apply_override(node_id, "meets_caps_diagnostic_criteria", meets)
        ctx.set("meets_caps_diagnostic_criteria", meets)

        if not meets:
            stop = Stop(
                reason="CAPS / chronic abdominal pain pathway diagnostic criteria not met.",
                actions=[
                    Action(
                        code="NOT_CAPS_ENTRY",
                        label="Does not meet CAPS diagnostic criteria; consider alternate evaluation pathway.",
                        override_options={
                            "node": node_id,
                            "field": "meets_caps_diagnostic_criteria",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 11},
                    )
                ],
            )
            ctx.log(node_id, "CRITERIA_NOT_MET", {f: ctx.get(f) for f in required_fields}, [stop])
            return NodeResult([stop])

        actions: List[Output] = [
            Action(
                code="CAPS_CRITERIA_MET",
                label="CAPS diagnostic criteria are met; continue pathway assessment.",
                override_options={
                    "node": node_id,
                    "field": "meets_caps_diagnostic_criteria",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 12},
            )
        ]
        ctx.log(node_id, "CRITERIA_MET", {f: ctx.get(f) for f in required_fields}, actions)
        return NodeResult(actions, next_node="Better_Explained_By_Other_GI_Disorder")

    nodes["Diagnostic_Criteria"] = Node("Diagnostic_Criteria", node_diagnostic_criteria)

    # -----------------------------------------------------
    # Node 2 – Better explained by another GI disorder
    # -----------------------------------------------------
    def node_other_gi_disorder(ctx: Context) -> NodeResult:
        node_id = "Better_Explained_By_Other_GI_Disorder"

        required_fields = [
            "predominant_heartburn_or_regurgitation",
            "pain_related_to_defecation_or_change_in_stool",
            "epigastric_discomfort_or_upper_abdominal_pain_bloating",
        ]
        missing = _missing(ctx, required_fields)

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need symptom-pattern data to determine whether GERD, IBS, or dyspepsia better explains symptoms.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_OVERLAP_GI_PATTERN",
                        label="Document whether symptoms fit GERD, IBS, or dyspepsia patterns",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult([dr])

        gerd = _bool(ctx.get("predominant_heartburn_or_regurgitation"))
        ibs = _bool(ctx.get("pain_related_to_defecation_or_change_in_stool"))
        dyspepsia = _bool(ctx.get("epigastric_discomfort_or_upper_abdominal_pain_bloating"))

        actions: List[Output] = []

        if gerd:
            actions.append(
                Action(
                    code="ROUTE_GERD_PATHWAY",
                    label="Symptoms are more consistent with GERD; follow GERD pathway.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 21},
                )
            )
        if ibs:
            actions.append(
                Action(
                    code="ROUTE_IBS_PATHWAY",
                    label="Symptoms are more consistent with IBS; follow IBS pathway.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 22},
                )
            )
        if dyspepsia:
            actions.append(
                Action(
                    code="ROUTE_DYSPEPSIA_PATHWAY",
                    label="Symptoms are more consistent with dyspepsia; follow dyspepsia pathway.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 23},
                )
            )

        better_explained = any([gerd, ibs, dyspepsia])
        better_explained = ctx.apply_override(node_id, "better_explained_by_other_gi_disorder", better_explained)
        ctx.set("better_explained_by_other_gi_disorder", better_explained)

        if better_explained:
            stop = Stop(
                reason="Symptoms are better explained by another GI disorder.",
                actions=actions if actions else [
                    Action(
                        code="OTHER_GI_DISORDER_BETTER_EXPLAINS",
                        label="Another GI disorder better explains symptoms.",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 24},
                    )
                ],
            )
            ctx.log(
                node_id,
                "BETTER_EXPLAINED_BY_OTHER_GI_DISORDER",
                {f: ctx.get(f) for f in required_fields},
                [stop],
            )
            return NodeResult([stop])

        actions = [
            Action(
                code="NO_BETTER_GI_EXPLANATION",
                label="Symptoms are not better explained by GERD, IBS, or dyspepsia.",
                override_options={
                    "node": node_id,
                    "field": "better_explained_by_other_gi_disorder",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 25},
            )
        ]
        ctx.log(node_id, "NO_BETTER_GI_EXPLANATION", {f: ctx.get(f) for f in required_fields}, actions)
        return NodeResult(actions, next_node="Alarm_Features")

    nodes["Better_Explained_By_Other_GI_Disorder"] = Node(
        "Better_Explained_By_Other_GI_Disorder",
        node_other_gi_disorder,
    )

    # -----------------------------------------------------
    # Node 3 – Alarm features
    # -----------------------------------------------------
    def node_alarm_features(ctx: Context) -> NodeResult:
        node_id = "Alarm_Features"

        required_fields = [
            "family_history_ibd_or_crc_first_degree",
            "unintended_weight_loss_over_5_percent",
            "iron_deficiency_anemia",
            "symptom_onset_after_age_50",
            "persistent_vomiting",
            "visible_blood_in_stool",
        ]
        missing = _missing(ctx, required_fields)

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need alarm feature fields to determine whether referral/endoscopy is required.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_CAP_ALARM_FEATURES",
                        label="Document chronic abdominal pain alarm features",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult([dr])

        alarm = _any_true([ctx.get(f) for f in required_fields])
        alarm = ctx.apply_override(node_id, "alarm_features_present", alarm)
        ctx.set("alarm_features_present", alarm)

        if alarm:
            actions = [
                Action(
                    code="REFER_CONSULT_ENDOSCOPY",
                    label="Alarm features present; refer for specialist consultation/endoscopy.",
                    urgency="urgent",
                    details={f: ctx.get(f) for f in required_fields if ctx.get(f) is True},
                    override_options={
                        "node": node_id,
                        "field": "alarm_features_present",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 31},
                )
            ]
            stop = Stop(
                reason="Alarm features identified.",
                actions=actions,
                urgency="urgent",
            )
            ctx.log(node_id, "ALARM_FEATURES_PRESENT", {f: ctx.get(f) for f in required_fields}, [stop])
            return NodeResult([stop])

        actions = [
            Action(
                code="NO_ALARM_FEATURES",
                label="No alarm features identified; continue conservative workup.",
                override_options={
                    "node": node_id,
                    "field": "alarm_features_present",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 32},
            )
        ]
        ctx.log(node_id, "NO_ALARM_FEATURES", {f: ctx.get(f) for f in required_fields}, actions)
        return NodeResult(actions, next_node="Alternate_Diagnoses_Secondary_Causes")

    nodes["Alarm_Features"] = Node("Alarm_Features", node_alarm_features)

    # -----------------------------------------------------
    # Node 4 – Alternate diagnoses / secondary causes
    # -----------------------------------------------------
    def node_secondary_causes(ctx: Context) -> NodeResult:
        node_id = "Alternate_Diagnoses_Secondary_Causes"

        review_fields = [
            "referred_pain_other_system",
            "culprit_medication_present",
            "dietary_trigger_or_allergen_present",
            "abdominal_wall_pain_suspected",
            "cannabinoid_related_pain_suspected",
            "narcotic_bowel_suspected",
            "organic_condition_already_identified",
        ]
        missing = _missing(ctx, review_fields)

        actions: List[Output] = []

        # non-blocking support even if some details absent
        if ctx.get("medication_review_completed") is not True:
            actions.append(
                Action(
                    code="REVIEW_MEDICATIONS",
                    label="Review medications and reduce or discontinue culprit medications.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
                )
            )
        if ctx.get("dietary_review_completed") is not True:
            actions.append(
                Action(
                    code="REVIEW_DIETARY_TRIGGERS",
                    label="Identify and eliminate dietary triggers and allergens where appropriate.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 41},
                )
            )
        if ctx.get("referred_pain_assessed") is not True:
            actions.append(
                Action(
                    code="ASSESS_REFERRED_PAIN",
                    label="Consider referred pain from other systems.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 42},
                )
            )
        if ctx.get("carnet_test_considered") is not True and ctx.get("abdominal_wall_pain_suspected") is True:
            actions.append(
                Action(
                    code="CONSIDER_CARNET_TEST",
                    label="Consider Carnett's test if abdominal wall pain is suspected.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 43},
                )
            )

        secondary_cause = _alternate_diagnosis_or_secondary_cause_present(ctx)
        secondary_cause = ctx.apply_override(node_id, "alternate_or_secondary_cause_present", secondary_cause)
        ctx.set("alternate_or_secondary_cause_present", secondary_cause)

        if missing:
            actions.insert(
                0,
                DataRequest(
                    blocking_node=node_id,
                    missing_fields=missing,
                    message="Secondary-cause review is incomplete. Engine can continue, but these data improve confidence.",
                    suggested_actions=[
                        Action(
                            code="CAPTURE_SECONDARY_CAUSE_REVIEW",
                            label="Complete alternate diagnosis / secondary cause review",
                            display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 39},
                        )
                    ],
                )
            )

        if secondary_cause:
            actions.append(
                Action(
                    code="TREAT_OR_REFER_ALTERNATE_CAUSE",
                    label="Alternate diagnosis or secondary cause identified; treat or refer for consultation.",
                    details={f: ctx.get(f) for f in review_fields if ctx.get(f) is True},
                    override_options={
                        "node": node_id,
                        "field": "alternate_or_secondary_cause_present",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 44},
                )
            )
            stop = Stop(
                reason="Alternate diagnosis or secondary cause identified.",
                actions=[o for o in actions if isinstance(o, Action)],
            )
            ctx.log(node_id, "SECONDARY_CAUSE_PRESENT", {f: ctx.get(f) for f in review_fields}, [stop])
            return NodeResult([stop])

        if not actions:
            actions = [
                Action(
                    code="NO_SECONDARY_CAUSE_IDENTIFIED",
                    label="No alternate diagnosis or secondary cause identified on current review.",
                    override_options={
                        "node": node_id,
                        "field": "alternate_or_secondary_cause_present",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 45},
                )
            ]
        else:
            actions.append(
                Action(
                    code="NO_SECONDARY_CAUSE_REQUIRING_ROUTE_CHANGE",
                    label="No alternate diagnosis or secondary cause currently requires route change.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 46},
                )
            )

        ctx.log(node_id, "NO_SECONDARY_CAUSE_REQUIRING_ROUTE_CHANGE", {f: ctx.get(f) for f in review_fields}, actions)
        return NodeResult(actions, next_node="Baseline_Investigations")

    nodes["Alternate_Diagnoses_Secondary_Causes"] = Node(
        "Alternate_Diagnoses_Secondary_Causes",
        node_secondary_causes,
    )

    # -----------------------------------------------------
    # Node 5 – Baseline investigations
    # -----------------------------------------------------
    def node_baseline_investigations(ctx: Context) -> NodeResult:
        node_id = "Baseline_Investigations"

        required_core = [
            "cbc_done",
            "electrolytes_done",
            "creatinine_done",
            "liver_tests_done",
            "lipase_done",
            "ferritin_or_tsat_done",
        ]
        missing_core = _missing(ctx, required_core)

        actions: List[Output] = []

        if missing_core:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing_core,
                message="Need core baseline investigations to continue the chronic abdominal pain pathway.",
                suggested_actions=[
                    Action(
                        code="ORDER_CORE_BASELINE_INVESTIGATIONS",
                        label="Order CBC, electrolytes, creatinine, liver tests, lipase, ferritin/transferrin saturation",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_CORE_INVESTIGATIONS", {"missing": missing_core}, [dr])
            return NodeResult([dr])

        # non-blocking contextual recommendations
        if ctx.get("suspect_inflammatory_or_infectious_condition") is True and ctx.get("crp_done") is not True:
            actions.append(
                Action(
                    code="ORDER_CRP",
                    label="Consider/order CRP because inflammatory or infectious condition is suspected.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 51},
                )
            )
        if ctx.get("travel_or_parasite_risk") is True and ctx.get("stool_ova_parasites_done") is not True:
            actions.append(
                Action(
                    code="ORDER_OVA_PARASITES",
                    label="Consider/order stool ova and parasites based on travel or exposure history.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 52},
                )
            )
        if ctx.get("infectious_diarrhea_risk") is True and ctx.get("c_difficile_done") is not True:
            actions.append(
                Action(
                    code="ORDER_C_DIFFICLE",
                    label="Consider/order C. difficile testing based on clinical context.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 53},
                )
            )
        if ctx.get("celiac_screen_relevant") is True and ctx.get("celiac_screen_done") is not True:
            actions.append(
                Action(
                    code="ORDER_CELIAC_SCREEN",
                    label="Consider celiac disease screen based on clinical context.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 54},
                )
            )
        if ctx.get("tsh_relevant") is True and ctx.get("tsh_done") is not True:
            actions.append(
                Action(
                    code="ORDER_TSH",
                    label="Consider thyroid testing (TSH) based on clinical context.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 55},
                )
            )
        if ctx.get("h_pylori_relevant") is True and ctx.get("h_pylori_done") is not True:
            actions.append(
                Action(
                    code="ORDER_H_PYLORI_TEST",
                    label="Consider H. pylori testing based on clinical context.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 56},
                )
            )
        if ctx.get("urinary_or_renal_context") is True and ctx.get("urinalysis_done") is not True:
            actions.append(
                Action(
                    code="ORDER_URINALYSIS",
                    label="Consider urinalysis based on clinical context.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 57},
                )
            )
        if ctx.get("pregnancy_possible") is True and ctx.get("pregnancy_test_done") is not True:
            actions.append(
                Action(
                    code="ORDER_BHCG",
                    label="Consider pregnancy test (β-hCG) based on clinical context.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 58},
                )
            )
        if ctx.get("ultrasound_relevant") is True and ctx.get("abdominopelvic_ultrasound_done") is not True:
            actions.append(
                Action(
                    code="ORDER_ABDOMINOPELVIC_US",
                    label="Consider abdominopelvic ultrasound based on clinical context.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 59},
                )
            )

        abnormal = _abnormal_baseline_investigations(ctx)
        abnormal = ctx.apply_override(node_id, "abnormal_baseline_investigations", abnormal)
        ctx.set("abnormal_baseline_investigations", abnormal)

        if abnormal:
            actions.append(
                Action(
                    code="TREAT_OR_REFER_ABNORMAL_WORKUP",
                    label="Baseline investigations suggest another cause; treat or refer for consultation.",
                    details={
                        k: ctx.get(k) for k in [
                            "cbc_abnormal",
                            "electrolytes_abnormal",
                            "creatinine_abnormal",
                            "liver_tests_abnormal",
                            "lipase_abnormal",
                            "crp_abnormal",
                            "ferritin_or_tsat_abnormal",
                            "c_difficile_positive",
                            "ova_parasites_positive",
                            "celiac_screen_positive",
                            "tsh_abnormal",
                            "h_pylori_positive",
                            "urinalysis_abnormal",
                            "pregnancy_test_positive",
                            "abdominopelvic_ultrasound_abnormal",
                        ] if ctx.get(k) is True
                    },
                    override_options={
                        "node": node_id,
                        "field": "abnormal_baseline_investigations",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 60},
                )
            )
            stop = Stop(
                reason="Baseline investigations identified possible alternate/organic cause.",
                actions=[o for o in actions if isinstance(o, Action)],
            )
            ctx.log(node_id, "ABNORMAL_BASELINE_INVESTIGATIONS", {}, [stop])
            return NodeResult([stop])

        actions.append(
            Action(
                code="BASELINE_INVESTIGATIONS_REASSURING",
                label="Baseline investigations are reassuring / do not currently identify another cause.",
                override_options={
                    "node": node_id,
                    "field": "abnormal_baseline_investigations",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 61},
            )
        )

        ctx.log(node_id, "BASELINE_INVESTIGATIONS_REASSURING", {}, actions)
        return NodeResult(actions, next_node="Management")

    nodes["Baseline_Investigations"] = Node("Baseline_Investigations", node_baseline_investigations)

    # -----------------------------------------------------
    # Node 6 – Management
    # -----------------------------------------------------
    def node_management(ctx: Context) -> NodeResult:
        node_id = "Management"
        actions: List[Output] = []

        actions.append(
            Action(
                code="PROVIDE_PATIENT_REASSURANCE",
                label="Provide patient reassurance and reassessment/reappraisal to establish a therapeutic relationship.",
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 70},
            )
        )
        actions.append(
            Action(
                code="LIFESTYLE_MODIFICATION",
                label="Recommend lifestyle modification including stress reduction, physical activity, mindfulness/meditation, and consider hypnotherapy or acupuncture.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 71},
            )
        )
        actions.append(
            Action(
                code="DIETARY_MODIFICATION",
                label="Assess food triggers, keep a food journal, and consider referral to a Registered Dietitian.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 72},
            )
        )
        actions.append(
            Action(
                code="PSYCHOLOGICAL_THERAPY",
                label="Refer to behavioral health specialist; if psychiatric symptoms predominate, consider psychiatry.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 73},
            )
        )

        moderate_or_severe = ctx.get("moderate_or_severe_caps_symptoms")
        if moderate_or_severe is None:
            actions.append(
                Action(
                    code="CAPTURE_CAPS_SEVERITY",
                    label="Document whether CAPS symptoms are moderate/severe enough to justify pharmacologic therapy.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 74},
                )
            )
        elif moderate_or_severe is True:
            actions.append(
                Action(
                    code="CONSIDER_CAPS_PHARMACOTHERAPY",
                    label="Consider pharmacologic therapy for moderate-to-severe CAPS symptoms (e.g., antispasmodic, TCA, SNRI, SSRI as clinically appropriate).",
                    details={
                        "avoid": ["opioids", "narcotics"],
                    },
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 75},
                )
            )

        if ctx.get("opioid_use_for_chronic_gi_pain") is True:
            actions.append(
                Action(
                    code="AVOID_OPIOIDS_CAPS",
                    label="Do not use opioids/narcotics for CAPS or chronic GI pain.",
                    urgency="high",
                    display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 76},
                )
            )

        if ctx.get("sleep_or_mood_disorder_screen_completed") is not True:
            actions.append(
                Action(
                    code="SCREEN_SLEEP_MOOD",
                    label="Screen for underlying sleep or mood disorders.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 77},
                )
            )
        if ctx.get("trauma_history_screen_considered") is not True:
            actions.append(
                Action(
                    code="CONSIDER_TRAUMA_INFORMED_ASSESSMENT",
                    label="Consider trauma-informed assessment where relevant.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 78},
                )
            )

        ctx.set("management_started", _management_started(ctx))
        ctx.log(node_id, "MANAGEMENT_RECOMMENDED", {}, actions)
        return NodeResult(actions, next_node="Referral_Reassessment")

    nodes["Management"] = Node("Management", node_management)

    # -----------------------------------------------------
    # Node 7 – Reassessment / advice / referral
    # -----------------------------------------------------
    def node_reassessment(ctx: Context) -> NodeResult:
        node_id = "Referral_Reassessment"

        unsatisfactory = ctx.get("unsatisfactory_response_to_management")

        if unsatisfactory is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["unsatisfactory_response_to_management"],
                message="Need to know whether response to management has been unsatisfactory in order to decide on escalation.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_MANAGEMENT_RESPONSE",
                        label="Document response to management",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 80},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["unsatisfactory_response_to_management"]}, [dr])
            return NodeResult([dr])

        advice_before_referral = True
        advice_before_referral = ctx.apply_override(node_id, "use_advice_service_before_referral", advice_before_referral)
        ctx.set("use_advice_service_before_referral", advice_before_referral)

        if unsatisfactory is True:
            actions = []
            if advice_before_referral:
                actions.append(
                    Action(
                        code="CONSIDER_ADVICE_SERVICE",
                        label="Consider using an advice service before referring.",
                        override_options={
                            "node": node_id,
                            "field": "use_advice_service_before_referral",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 81},
                    )
                )
            actions.append(
                Action(
                    code="REFER_CONSULTATION_IF_PERSISTENT",
                    label="If symptoms remain unsatisfactory despite management, refer for consultation.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 82},
                )
            )
            stop = Stop(
                reason="Unsatisfactory response to management; escalation indicated.",
                actions=actions,
            )
            ctx.log(node_id, "UNSATISFACTORY_RESPONSE_ESCALATE", {"unsatisfactory_response_to_management": unsatisfactory}, [stop])
            return NodeResult([stop])

        stop = Stop(
            reason="Continue care in the patient medical home with ongoing reassessment.",
            actions=[
                Action(
                    code="CONTINUE_PRIMARY_CARE_MANAGEMENT",
                    label="Continue CAPS management in primary care and reassess for symptom change or new alarm features.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 83},
                )
            ],
        )
        ctx.log(node_id, "CONTINUE_PRIMARY_CARE", {"unsatisfactory_response_to_management": unsatisfactory}, [stop])
        return NodeResult([stop])

    nodes["Referral_Reassessment"] = Node("Referral_Reassessment", node_reassessment)

    return PathwayEngine(nodes=nodes, start_node="Diagnostic_Criteria")


# =========================================================
# RUNNER
# =========================================================

def run_chronic_abdominal_pain_pathway(
    patient_data: Dict[str, Any],
    overrides: Optional[List[Override]] = None,
):
    engine = chronic_abdominal_pain_build_engine()
    ctx = Context(data=dict(patient_data), overrides=overrides or [])
    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx


# =========================================================
# EXAMPLE INPUT
# =========================================================

EXAMPLE_PATIENT = {
    # Diagnostic criteria
    "continuous_or_near_continuous_pain": True,
    "pain_duration_months_at_criteria_level": 4,
    "symptom_onset_months_ago": 8,
    "pain_only_occasional_relation_to_physiologic_events": True,
    "pain_limits_daily_function": True,
    "pain_not_feigned": True,
    "not_explained_by_other_condition_initial_assessment": True,

    # Better explained by another GI disorder?
    "predominant_heartburn_or_regurgitation": False,
    "pain_related_to_defecation_or_change_in_stool": False,
    "epigastric_discomfort_or_upper_abdominal_pain_bloating": False,

    # Alarm features
    "family_history_ibd_or_crc_first_degree": False,
    "unintended_weight_loss_over_5_percent": False,
    "iron_deficiency_anemia": False,
    "symptom_onset_after_age_50": False,
    "persistent_vomiting": False,
    "visible_blood_in_stool": False,

    # Secondary cause review
    "medication_review_completed": True,
    "dietary_review_completed": True,
    "referred_pain_assessed": True,
    "referred_pain_other_system": False,
    "culprit_medication_present": False,
    "dietary_trigger_or_allergen_present": False,
    "abdominal_wall_pain_suspected": False,
    "cannabinoid_related_pain_suspected": False,
    "narcotic_bowel_suspected": False,
    "organic_condition_already_identified": False,

    # Baseline investigations
    "cbc_done": True,
    "electrolytes_done": True,
    "creatinine_done": True,
    "liver_tests_done": True,
    "lipase_done": True,
    "ferritin_or_tsat_done": True,
    "cbc_abnormal": False,
    "electrolytes_abnormal": False,
    "creatinine_abnormal": False,
    "liver_tests_abnormal": False,
    "lipase_abnormal": False,
    "ferritin_or_tsat_abnormal": False,

    # Contextual investigation flags
    "suspect_inflammatory_or_infectious_condition": False,
    "travel_or_parasite_risk": False,
    "infectious_diarrhea_risk": False,
    "celiac_screen_relevant": False,
    "tsh_relevant": False,
    "h_pylori_relevant": False,
    "urinary_or_renal_context": False,
    "pregnancy_possible": False,
    "ultrasound_relevant": False,

    # Management
    "moderate_or_severe_caps_symptoms": True,
    "opioid_use_for_chronic_gi_pain": False,
    "patient_reassurance_done": True,
    "lifestyle_modification_started": True,
    "dietary_modification_started": True,
    "psychological_referral_or_therapy_started": False,
    "pharmacologic_caps_therapy_started": False,
    "sleep_or_mood_disorder_screen_completed": False,
    "trauma_history_screen_considered": False,

    # Reassessment
    "unsatisfactory_response_to_management": False,
}