# -*- coding: utf-8 -*-
"""dyspepsia_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-0-5tlf7vaeenPsrC0f_WkzZJp1HXFj
"""

"""
========================================================
PATHWAY FILE: Dyspepsia
========================================================

Design goals
- Same architecture as other pathway engines
- Progressive gating with DataRequest where needed
- UI-friendly outputs: Action / DataRequest / Stop
- Audit log support
- Override capability
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# DYSPEPSIA PATHWAY IMPLEMENTATION
# =========================================================

def dyspepsia_build_engine() -> PathwayEngine:

    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # Node 1 – Suspected Dyspepsia
    # -----------------------------------------------------
    def node_suspected_dyspepsia(ctx: Context):

        node_id = "Suspected_Dyspepsia"

        predominant_epigastric_pain = ctx.get("predominant_epigastric_pain")
        predominant_epigastric_discomfort = ctx.get("predominant_epigastric_discomfort")
        predominant_upper_abdominal_bloating = ctx.get("predominant_upper_abdominal_bloating")
        symptom_duration_months = ctx.get("symptom_duration_months")

        # Rome IV supportive fields
        postprandial_fullness = ctx.get("postprandial_fullness")
        early_satiety = ctx.get("early_satiety")
        epigastric_pain = ctx.get("epigastric_pain")
        epigastric_burning = ctx.get("epigastric_burning")
        symptom_onset_months_ago = ctx.get("symptom_onset_months_ago")

        missing = []
        if predominant_epigastric_pain is None:
            missing.append("predominant_epigastric_pain")
        if predominant_epigastric_discomfort is None:
            missing.append("predominant_epigastric_discomfort")
        if predominant_upper_abdominal_bloating is None:
            missing.append("predominant_upper_abdominal_bloating")
        if symptom_duration_months is None:
            missing.append("symptom_duration_months")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need practical dyspepsia entry criteria: predominant symptoms and duration.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_DYSPEPSIA_ENTRY",
                        label="Capture predominant upper GI symptoms and duration",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult([dr])

        practical_entry = (
            symptom_duration_months > 1
            and bool(predominant_epigastric_pain or predominant_epigastric_discomfort or predominant_upper_abdominal_bloating)
        )
        practical_entry = ctx.apply_override(node_id, "suspected_dyspepsia", practical_entry)
        ctx.set("suspected_dyspepsia", practical_entry)

        # Rome IV support flag (non-blocking support)
        rome_iv_feature_count = sum([
            bool(postprandial_fullness),
            bool(early_satiety),
            bool(epigastric_pain),
            bool(epigastric_burning),
        ])
        rome_iv_support = False
        if symptom_duration_months is not None and symptom_onset_months_ago is not None:
            rome_iv_support = (symptom_duration_months >= 3) and (symptom_onset_months_ago >= 6) and (rome_iv_feature_count >= 1)
        ctx.set("rome_iv_support_dyspepsia", rome_iv_support)

        if not practical_entry:
            stop = Stop(
                reason="Dyspepsia pathway entry criteria not met.",
                actions=[
                    Action(
                        code="NOT_DYSPEPSIA",
                        label="Does not meet dyspepsia pathway entry criteria.",
                        details={
                            "supported_by": [
                                f"Symptom duration months: {symptom_duration_months}",
                                "Predominant symptom was not epigastric discomfort/pain or upper abdominal bloating",
                            ],
                            "rome_iv_support_dyspepsia": rome_iv_support,
                        },
                        override_options={
                            "node": node_id,
                            "field": "suspected_dyspepsia",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
                    )
                ],
            )
            ctx.log(node_id, "ENTRY_CRITERIA_NOT_MET", {
                "symptom_duration_months": symptom_duration_months,
                "predominant_epigastric_pain": predominant_epigastric_pain,
                "predominant_epigastric_discomfort": predominant_epigastric_discomfort,
                "predominant_upper_abdominal_bloating": predominant_upper_abdominal_bloating,
                "rome_iv_support_dyspepsia": rome_iv_support,
            }, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="DYSPEPSIA_ENTRY_MET",
                label="Dyspepsia pathway entry criteria met.",
                details={
                    "supported_by": [
                        f"Symptom duration months: {symptom_duration_months} (>1)",
                        "Predominant symptom is epigastric discomfort/pain and/or upper abdominal bloating",
                    ],
                    "rome_iv_support_dyspepsia": rome_iv_support,
                    "rome_iv_feature_count": rome_iv_feature_count,
                },
                override_options={
                    "node": node_id,
                    "field": "suspected_dyspepsia",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
            )
        ]
        ctx.log(node_id, "ENTRY_CRITERIA_MET", {
            "symptom_duration_months": symptom_duration_months,
            "rome_iv_support_dyspepsia": rome_iv_support,
            "rome_iv_feature_count": rome_iv_feature_count,
        }, out)
        return NodeResult(out, next_node="GERD_Screen")

    nodes["Suspected_Dyspepsia"] = Node("Suspected_Dyspepsia", node_suspected_dyspepsia)

    # -----------------------------------------------------
    # Node 2 – GERD Screen
    # -----------------------------------------------------
    def node_gerd_screen(ctx: Context):

        node_id = "GERD_Screen"

        predominant_heartburn = ctx.get("predominant_heartburn")
        predominant_regurgitation = ctx.get("predominant_regurgitation")

        if predominant_heartburn is None:
            predominant_heartburn = False
        if predominant_regurgitation is None:
            predominant_regurgitation = False

        route_gerd = bool(predominant_heartburn or predominant_regurgitation)
        route_gerd = ctx.apply_override(node_id, "route_gerd", route_gerd)
        ctx.set("route_gerd", route_gerd)

        if route_gerd:
            stop = Stop(
                reason="Predominant symptoms are heartburn and/or regurgitation – follow GERD pathway.",
                actions=[
                    Action(
                        code="ROUTE_GERD_PATHWAY",
                        label="Route to GERD pathway",
                        details={"supported_by": ["Predominant symptom is heartburn ± regurgitation"]},
                        override_options={
                            "node": node_id,
                            "field": "route_gerd",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 6},
                    )
                ],
            )
            ctx.log(node_id, "ROUTE_GERD", {
                "predominant_heartburn": predominant_heartburn,
                "predominant_regurgitation": predominant_regurgitation,
            }, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="NOT_PREDOMINANT_GERD",
                label="Predominant symptoms are not heartburn/regurgitation.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 12},
            )
        ]
        ctx.log(node_id, "NOT_GERD", {
            "predominant_heartburn": predominant_heartburn,
            "predominant_regurgitation": predominant_regurgitation,
        }, out)
        return NodeResult(out, next_node="Alarm_Features")

    nodes["GERD_Screen"] = Node("GERD_Screen", node_gerd_screen)

    # -----------------------------------------------------
    # Node 3 – Alarm Features
    # -----------------------------------------------------
    def node_alarm(ctx: Context):

        node_id = "Alarm_Features"

        actively_bleeding_now = bool(ctx.get("actively_bleeding_now"))
        if actively_bleeding_now:
            stop = Stop(
                reason="Possible active upper GI bleeding – urgent emergency assessment required.",
                urgency="urgent",
                actions=[
                    Action(
                        code="EMERGENT_BLEEDING_ASSESSMENT",
                        label="Immediate emergency assessment / GI on-call / ED",
                        urgency="urgent",
                        details={"supported_by": ["Active bleeding now"]},
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 1},
                    )
                ],
            )
            ctx.log(node_id, "ACTIVE_BLEEDING", {"actively_bleeding_now": True}, [stop])
            return NodeResult([stop])

        fh_upper_gi_cancer = bool(ctx.get("family_history_upper_gi_cancer_first_degree"))
        onset_after_60 = bool(ctx.get("symptom_onset_after_age_60"))
        unintended_weight_loss = bool(ctx.get("unintended_weight_loss"))
        black_stool_or_blood_in_vomit = bool(ctx.get("black_stool_or_blood_in_vomit"))
        dysphagia = bool(ctx.get("dysphagia"))
        persistent_vomiting = bool(ctx.get("persistent_vomiting"))
        iron_deficiency_anemia_present = bool(ctx.get("iron_deficiency_anemia_present"))

        alarm_present = any([
            fh_upper_gi_cancer,
            onset_after_60,
            unintended_weight_loss,
            black_stool_or_blood_in_vomit,
            dysphagia,
            persistent_vomiting,
            iron_deficiency_anemia_present,
        ])
        alarm_present = ctx.apply_override(node_id, "alarm_features_present", alarm_present)
        ctx.set("alarm_features_present", alarm_present)

        if alarm_present:
            stop = Stop(
                reason="Alarm features present – urgent referral for consultation/endoscopy.",
                urgency="urgent",
                actions=[
                    Action(
                        code="URGENT_ENDOSCOPY_REFERRAL",
                        label="Urgent referral for consultation/endoscopy",
                        urgency="urgent",
                        details={
                            "supported_by": ["At least one dyspepsia alarm feature is present"],
                            "family_history_upper_gi_cancer_first_degree": fh_upper_gi_cancer,
                            "symptom_onset_after_age_60": onset_after_60,
                            "unintended_weight_loss": unintended_weight_loss,
                            "black_stool_or_blood_in_vomit": black_stool_or_blood_in_vomit,
                            "dysphagia": dysphagia,
                            "persistent_vomiting": persistent_vomiting,
                            "iron_deficiency_anemia_present": iron_deficiency_anemia_present,
                        },
                        override_options={
                            "node": node_id,
                            "field": "alarm_features_present",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 5},
                    )
                ],
            )
            ctx.log(node_id, "ALARM_FEATURES_PRESENT", {
                "family_history_upper_gi_cancer_first_degree": fh_upper_gi_cancer,
                "symptom_onset_after_age_60": onset_after_60,
                "unintended_weight_loss": unintended_weight_loss,
                "black_stool_or_blood_in_vomit": black_stool_or_blood_in_vomit,
                "dysphagia": dysphagia,
                "persistent_vomiting": persistent_vomiting,
                "iron_deficiency_anemia_present": iron_deficiency_anemia_present,
            }, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="NO_ALARM_FEATURES",
                label="No dyspepsia alarm features present.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 12},
            )
        ]
        ctx.log(node_id, "NO_ALARM_FEATURES", {}, out)
        return NodeResult(out, next_node="Medication_Lifestyle_Review")

    nodes["Alarm_Features"] = Node("Alarm_Features", node_alarm)

    # -----------------------------------------------------
    # Node 4 – Medication and Lifestyle Review
    # -----------------------------------------------------
    def node_med_lifestyle(ctx: Context):

        node_id = "Medication_Lifestyle_Review"
        actions: List[Output] = []

        if ctx.get("medication_review_done") is not True:
            actions.append(Action(code="REVIEW_MEDICATIONS", label="Review medications and reduce/avoid culprit agents where possible.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))
        if ctx.get("lifestyle_review_done") is not True:
            actions.append(Action(code="REVIEW_LIFESTYLE", label="Review lifestyle factors relevant to dyspepsia.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))
        if ctx.get("diet_trigger_review_done") is not True:
            actions.append(Action(code="REVIEW_DIET_TRIGGERS", label="Review diet and common trigger foods.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))

        improved = ctx.get("symptoms_improved_after_med_lifestyle_review")
        if improved is True:
            stop = Stop(
                reason="Symptoms improved after medication/lifestyle review – no further action required.",
                actions=[
                    Action(
                        code="NO_FURTHER_ACTION_REQUIRED",
                        label="No further action required at this stage",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 7},
                    )
                ],
            )
            ctx.log(node_id, "IMPROVED_AFTER_REVIEW", {"symptoms_improved_after_med_lifestyle_review": True}, actions + [stop])
            return NodeResult(actions + [stop])

        if not actions:
            actions = [
                Action(
                    code="MEDICATION_LIFESTYLE_REVIEWED",
                    label="Medication and lifestyle review completed.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20},
                )
            ]

        ctx.log(node_id, "MEDICATION_LIFESTYLE_REVIEWED", {"symptoms_improved_after_med_lifestyle_review": improved}, actions)
        return NodeResult(actions, next_node="Baseline_Investigations")

    nodes["Medication_Lifestyle_Review"] = Node("Medication_Lifestyle_Review", node_med_lifestyle)

    # -----------------------------------------------------
    # Node 5 – Baseline Investigations
    # -----------------------------------------------------
    def node_baseline(ctx: Context):

        node_id = "Baseline_Investigations"
        actions: List[Output] = []

        # Core blocking / required-ish pieces
        missing = []
        if ctx.get("cbc_done") is None:
            missing.append("cbc_done")
        if ctx.get("h_pylori_test_done") is None:
            missing.append("h_pylori_test_done")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need CBC and H. pylori testing status for baseline dyspepsia workup.",
                suggested_actions=[
                    Action(code="CAPTURE_CORE_BASELINE", label="Capture CBC and H. pylori testing status", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 25})
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult([dr])

        # Warnings and conditional tests
        if ctx.get("cbc_done") is not True:
            actions.append(Action(code="CONSIDER_CBC", label="Consider CBC.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 25}))
        if ctx.get("ferritin_done") is False:
            actions.append(Action(code="CONSIDER_FERRITIN", label="Ferritin may be helpful (optional / based on context).", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 25}))
        if ctx.get("ttg_iga_done") is False:
            actions.append(Action(code="CONSIDER_TTG_IGA", label="Consider TTG IgA / celiac testing if indicated.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 25}))
        if ctx.get("suspect_hepatobiliary_pancreatic_process") is True and ctx.get("hepatobiliary_pancreatic_tests_done") is not True:
            actions.append(Action(code="CONSIDER_HEPATOBILIARY_PANCREATIC_TESTS", label="Consider hepatobiliary/pancreatic workup based on history.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 25}))

        # Abnormal / other diagnosis catch
        if any([
            ctx.get("cbc_abnormal") is True,
            ctx.get("ttg_iga_positive") is True,
            ctx.get("hepatobiliary_pancreatic_workup_abnormal") is True,
            ctx.get("other_diagnosis_found") is True,
        ]):
            stop = Stop(
                reason="Baseline investigations suggest another diagnosis – treat or refer as appropriate.",
                actions=[
                    Action(
                        code="OTHER_DIAGNOSIS_IDENTIFIED",
                        label="Treat or refer for alternative diagnosis",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 8},
                    )
                ],
            )
            ctx.log(node_id, "OTHER_DIAGNOSIS", {}, actions + [stop])
            return NodeResult(actions + [stop])

        ctx.log(node_id, "BASELINE_INVESTIGATIONS_REVIEWED", {}, actions)
        return NodeResult(actions, next_node="H_Pylori_Test_And_Treat")

    nodes["Baseline_Investigations"] = Node("Baseline_Investigations", node_baseline)

    # -----------------------------------------------------
    # Node 6 – H. pylori test and treat
    # -----------------------------------------------------
    def node_h_pylori(ctx: Context):

        node_id = "H_Pylori_Test_And_Treat"

        test_done = ctx.get("h_pylori_test_done")
        result_positive = ctx.get("h_pylori_result_positive")

        missing = []
        if test_done is None:
            missing.append("h_pylori_test_done")
        if test_done is True and result_positive is None:
            missing.append("h_pylori_result_positive")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need H. pylori testing and result to follow dyspepsia pathway.",
                suggested_actions=[
                    Action(code="CAPTURE_H_PYLORI", label="Capture H. pylori test status/result", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30})
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult([dr])

        if test_done is False:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["h_pylori_test_done"],
                message="H. pylori testing is central to the dyspepsia pathway. Please test before progressing.",
                suggested_actions=[
                    Action(code="ORDER_H_PYLORI_TEST", label="Order H. pylori stool antigen or urea breath test", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30})
                ],
            )
            ctx.log(node_id, "H_PYLORI_NOT_DONE", {"h_pylori_test_done": False}, [dr])
            return NodeResult([dr])

        if result_positive is True:
            stop = Stop(
                reason="H. pylori positive – follow H. pylori pathway.",
                actions=[
                    Action(
                        code="ROUTE_H_PYLORI_PATHWAY",
                        label="Route to H. pylori pathway",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 9},
                    )
                ],
            )
            ctx.log(node_id, "H_PYLORI_POSITIVE", {"h_pylori_result_positive": True}, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="H_PYLORI_NEGATIVE_OR_TREATED",
                label="H. pylori is negative / not driving current pathway escalation.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 31},
            )
        ]
        ctx.log(node_id, "H_PYLORI_NEGATIVE", {"h_pylori_result_positive": result_positive}, out)
        return NodeResult(out, next_node="Pharmacologic_Therapy")

    nodes["H_Pylori_Test_And_Treat"] = Node("H_Pylori_Test_And_Treat", node_h_pylori)

    # -----------------------------------------------------
    # Node 7 – Pharmacologic Therapy
    # -----------------------------------------------------
    def node_pharmacologic(ctx: Context):

        node_id = "Pharmacologic_Therapy"
        actions: List[Output] = []

        ppi_once_daily_trial_done = ctx.get("ppi_once_daily_trial_done")
        ppi_once_daily_response_adequate = ctx.get("ppi_once_daily_response_adequate")

        if ppi_once_daily_trial_done is None:
            actions.append(Action(
                code="START_PPI_ONCE_DAILY",
                label="Trial PPI once daily for 4–8 weeks.",
                details={"supported_by": ["First pharmacologic step in dyspepsia pathway"]},
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 35},
            ))
            ctx.log(node_id, "START_PPI_ONCE_DAILY", {}, actions)
            return NodeResult(actions, next_node="Management_Response")

        if ppi_once_daily_trial_done is True and ppi_once_daily_response_adequate is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["ppi_once_daily_response_adequate"],
                message="Need response to once-daily PPI trial.",
                suggested_actions=[
                    Action(code="CAPTURE_PPI_ONCE_DAILY_RESPONSE", label="Capture response to once-daily PPI", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 35})
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["ppi_once_daily_response_adequate"]}, [dr])
            return NodeResult([dr])

        if ppi_once_daily_trial_done is True and ppi_once_daily_response_adequate is True:
            actions.append(Action(
                code="PPI_ONCE_DAILY_SUCCESS",
                label="Symptoms improved with once-daily PPI.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 35},
            ))
            ctx.log(node_id, "PPI_ONCE_DAILY_SUCCESS", {}, actions)
            return NodeResult(actions, next_node="Maintenance_Or_Deprescribing")

        # Once daily inadequate -> BID
        actions.append(Action(
            code="OPTIMIZE_PPI_BID",
            label="Optimize to PPI twice daily for 4–8 weeks.",
            display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 36},
        ))

        ppi_bid_trial_done = ctx.get("ppi_bid_trial_done")
        ppi_bid_response_adequate = ctx.get("ppi_bid_response_adequate")

        if ppi_bid_trial_done is None:
            ctx.log(node_id, "PPI_BID_RECOMMENDED", {}, actions)
            return NodeResult(actions, next_node="Management_Response")

        if ppi_bid_trial_done is True and ppi_bid_response_adequate is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["ppi_bid_response_adequate"],
                message="Need response to twice-daily PPI trial.",
                suggested_actions=[
                    Action(code="CAPTURE_PPI_BID_RESPONSE", label="Capture response to twice-daily PPI", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 36})
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["ppi_bid_response_adequate"]}, [dr])
            return NodeResult([dr])

        if ppi_bid_trial_done is True and ppi_bid_response_adequate is True:
            actions.append(Action(
                code="PPI_BID_SUCCESS",
                label="Symptoms improved with twice-daily PPI.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 36},
            ))
            ctx.log(node_id, "PPI_BID_SUCCESS", {}, actions)
            return NodeResult(actions, next_node="Maintenance_Or_Deprescribing")

        # Still inadequate -> consider TCA / domperidone
        actions.append(Action(
            code="CONSIDER_TCA",
            label="Consider low-dose TCA for persistent symptoms.",
            display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 37},
        ))
        ctx.log(node_id, "PPI_INADEQUATE_AFTER_BID", {}, actions)
        return NodeResult(actions, next_node="Domperidone_Eligibility")

    nodes["Pharmacologic_Therapy"] = Node("Pharmacologic_Therapy", node_pharmacologic)

    # -----------------------------------------------------
    # Node 8 – Domperidone Eligibility
    # -----------------------------------------------------
    def node_domperidone(ctx: Context):

        node_id = "Domperidone_Eligibility"
        actions: List[Output] = []

        age = ctx.get("age")
        sex = ctx.get("sex")
        ecg_qtc_ms = ctx.get("ecg_qtc_ms")
        family_history_sudden_cardiac_death = ctx.get("family_history_sudden_cardiac_death")
        personal_cardiac_history = ctx.get("personal_cardiac_history")
        qt_prolonging_medications_present = ctx.get("qt_prolonging_medications_present")

        missing = []
        if age is None:
            missing.append("age")
        if sex is None:
            missing.append("sex")
        if ecg_qtc_ms is None:
            missing.append("ecg_qtc_ms")
        if family_history_sudden_cardiac_death is None:
            missing.append("family_history_sudden_cardiac_death")
        if personal_cardiac_history is None:
            missing.append("personal_cardiac_history")
        if qt_prolonging_medications_present is None:
            missing.append("qt_prolonging_medications_present")

        if missing:
            actions.append(Action(
                code="CAPTURE_DOMPERIDONE_SAFETY",
                label="Capture age, QTc, cardiac history, and QT-prolonging medications before considering domperidone.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
            ))
            ctx.log(node_id, "INSUFFICIENT_DOMPERIDONE_DATA", {"missing": missing}, actions)
            return NodeResult(actions, next_node="Management_Response")

        qtc_limit = 470 if str(sex).lower() == "male" else 450
        eligible = (
            age < 60
            and ecg_qtc_ms <= qtc_limit
            and not bool(family_history_sudden_cardiac_death)
            and not bool(personal_cardiac_history)
            and not bool(qt_prolonging_medications_present)
        )
        eligible = ctx.apply_override(node_id, "domperidone_eligible", eligible)
        ctx.set("domperidone_eligible", eligible)

        if eligible:
            actions.append(Action(
                code="DOMPERIDONE_ELIGIBLE",
                label="Domperidone may be considered in selected patients.",
                details={
                    "supported_by": [
                        f"Age {age} < 60",
                        f"QTc {ecg_qtc_ms} within threshold ({qtc_limit})",
                        "No family history of sudden cardiac death",
                        "No personal cardiac history",
                        "No QT-prolonging medications",
                    ]
                },
                override_options={
                    "node": node_id,
                    "field": "domperidone_eligible",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
            ))
        else:
            actions.append(Action(
                code="DOMPERIDONE_NOT_ELIGIBLE",
                label="Domperidone should be avoided based on current safety profile.",
                details={
                    "supported_by": [
                        f"Age {age}",
                        f"QTc {ecg_qtc_ms} with threshold {qtc_limit}",
                        f"Family history sudden cardiac death: {family_history_sudden_cardiac_death}",
                        f"Personal cardiac history: {personal_cardiac_history}",
                        f"QT-prolonging medications present: {qt_prolonging_medications_present}",
                    ]
                },
                override_options={
                    "node": node_id,
                    "field": "domperidone_eligible",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
            ))

        ctx.log(node_id, "DOMPERIDONE_ASSESSED", {"domperidone_eligible": eligible}, actions)
        return NodeResult(actions, next_node="Maintenance_Or_Deprescribing")

    nodes["Domperidone_Eligibility"] = Node("Domperidone_Eligibility", node_domperidone)

    # -----------------------------------------------------
    # Node 9 – Maintenance / Deprescribing
    # -----------------------------------------------------
    def node_maintenance(ctx: Context):

        node_id = "Maintenance_Or_Deprescribing"
        actions: List[Output] = []

        symptoms_resolved_after_ppi = ctx.get("symptoms_resolved_after_ppi")
        symptoms_return_after_deprescribing = ctx.get("symptoms_return_after_deprescribing")

        if symptoms_resolved_after_ppi is None:
            actions.append(Action(
                code="CAPTURE_PPI_RESOLUTION_STATUS",
                label="Capture whether symptoms resolved after PPI therapy.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45},
            ))
            ctx.log(node_id, "MISSING_RESOLUTION_STATUS", {}, actions)
            return NodeResult(actions, next_node="Management_Response")

        if symptoms_resolved_after_ppi is True:
            actions.append(Action(
                code="TITRATE_DOWN_PPI",
                label="Discontinue or titrate down to the lowest effective PPI dose.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45},
            ))

            if symptoms_return_after_deprescribing is True:
                actions.append(Action(
                    code="PPI_MAINTENANCE",
                    label="Symptoms returned – resume/continue PPI at the lowest effective dose and attempt annual deprescribing.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 46},
                ))

        ctx.log(node_id, "MAINTENANCE_REVIEWED", {
            "symptoms_resolved_after_ppi": symptoms_resolved_after_ppi,
            "symptoms_return_after_deprescribing": symptoms_return_after_deprescribing,
        }, actions)
        return NodeResult(actions, next_node="Management_Response")

    nodes["Maintenance_Or_Deprescribing"] = Node("Maintenance_Or_Deprescribing", node_maintenance)

    # -----------------------------------------------------
    # Node 10 – Management Response
    # -----------------------------------------------------
    def node_management_response(ctx: Context):

        node_id = "Management_Response"

        unsat = ctx.get("unsatisfactory_response_to_management")
        if unsat is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["unsatisfactory_response_to_management"],
                message="Need overall response to dyspepsia management.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_MANAGEMENT_RESPONSE",
                        label="Document whether dyspepsia response is unsatisfactory",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["unsatisfactory_response_to_management"]}, [dr])
            return NodeResult([dr])

        unsat = ctx.apply_override(node_id, "unsatisfactory_response_to_management", unsat)
        ctx.set("unsatisfactory_response_to_management", unsat)

        if unsat:
            actions: List[Output] = [
                Action(
                    code="CONSIDER_ADVICE_SERVICE",
                    label="Consider using an advice service before referring.",
                    details={"supported_by": ["Unsatisfactory response to dyspepsia management"]},
                    override_options={
                        "node": node_id,
                        "field": "unsatisfactory_response_to_management",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 55},
                )
            ]

            if ctx.get("advice_service_considered") is True:
                stop = Stop(
                    reason="Unsatisfactory response after management – refer for consultation/endoscopy.",
                    actions=[
                        Action(
                            code="REFER_FAILED_MANAGEMENT",
                            label="Refer for consultation/endoscopy due to failed management",
                            display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 9},
                        )
                    ],
                )
                ctx.log(node_id, "FAILED_MANAGEMENT_REFER", {"advice_service_considered": True}, actions + [stop])
                return NodeResult(actions + [stop])

            ctx.log(node_id, "FAILED_MANAGEMENT_ADVICE_FIRST", {"advice_service_considered": ctx.get("advice_service_considered")}, actions)
            return NodeResult(actions)

        stop = Stop(
            reason="Dyspepsia pathway complete – continue management in medical home.",
            actions=[
                Action(
                    code="CONTINUE_MEDICAL_HOME_CARE",
                    label="Continue management in the Patient Medical Home.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 10},
                )
            ],
        )
        ctx.log(node_id, "PATHWAY_COMPLETE", {}, [stop])
        return NodeResult([stop])

    nodes["Management_Response"] = Node("Management_Response", node_management_response)

    return PathwayEngine(
        nodes=nodes,
        start_node="Suspected_Dyspepsia"
    )


# =========================================================
# RUNNER
# =========================================================

def run_dyspepsia_pathway(patient_data: Dict[str, Any], overrides=None):

    engine = dyspepsia_build_engine()

    ctx = Context(
        data=dict(patient_data),
        overrides=overrides or []
    )

    outputs = engine.run(ctx)

    return outputs, ctx.logs, ctx.overrides