# -*- coding: utf-8 -*-
"""gastric_cancer_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTxpX9nxEXRazMCRsQnHFwTH8Cx_TRJo
"""

"""
========================================================
PATHWAY FILE: Gastric Cancer
========================================================

Design goals
- Same architecture as other pathway engines
- Explicit routing across prevention / asymptomatic screening / symptomatic branches
- UI-friendly outputs: Action / DataRequest / Stop
- Audit log support
- Override capability
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone

# Optional chained dyspepsia engine import
# If unavailable in notebook/module environment, the router still works and can emit a fallback action.
try:
    from dyspepsia_engine import run_dyspepsia_pathway
    DYSPepsia_ENGINE_AVAILABLE = True
except Exception:
    DYSPepsia_ENGINE_AVAILABLE = False


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# GASTRIC CANCER PATHWAY IMPLEMENTATION
# =========================================================

def gastric_cancer_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # Helper functions
    # -----------------------------------------------------

    def _prevention_actions(ctx: Context) -> List[Action]:
        actions: List[Action] = []

        from_endemic_region = bool(ctx.get("from_endemic_region"))
        family_origin_endemic_region = bool(ctx.get("family_origin_endemic_region"))
        household_member_h_pylori_positive = bool(ctx.get("household_member_h_pylori_positive"))

        qualifies_h_pylori_prevention = any([
            from_endemic_region,
            family_origin_endemic_region,
            household_member_h_pylori_positive,
        ])
        ctx.set("qualifies_h_pylori_prevention", qualifies_h_pylori_prevention)

        if qualifies_h_pylori_prevention:
            actions.append(Action(
                code="CONSIDER_H_PYLORI_TESTING_PREVENTION",
                label="Consider opportunistic H. pylori testing/eradication for gastric cancer prevention.",
                details={
                    "supported_by": [
                        "Prevention pathway applies to all patients",
                        "Patient meets at least one H. pylori prevention-risk context"
                    ],
                    "from_endemic_region": from_endemic_region,
                    "family_origin_endemic_region": family_origin_endemic_region,
                    "household_member_h_pylori_positive": household_member_h_pylori_positive,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20},
            ))

        actions.append(Action(
            code="COUNSEL_SMOKING_CESSATION",
            label="Counsel on smoking cessation.",
            display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 21},
        ))
        actions.append(Action(
            code="COUNSEL_ALCOHOL_MODERATION",
            label="Counsel on alcohol moderation.",
            display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 21},
        ))
        actions.append(Action(
            code="COUNSEL_DIETARY_RISK_REDUCTION",
            label="Counsel on dietary risk reduction (more fibre/fruits/vegetables/lean meats; less salt/red meat/processed meat/processed foods).",
            display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 21},
        ))

        return actions

    def _screening_age_threshold(ctx: Context) -> int:
        base = 50
        if bool(ctx.get("family_history_gastric_cancer_first_degree")):
            fam_dx_age = ctx.get("family_member_gastric_cancer_age_at_diagnosis")
            if fam_dx_age is not None:
                return min(base, max(18, fam_dx_age - 10))
        return base

    def _screening_risk_factor_count(ctx: Context) -> Dict[str, Any]:
        age = ctx.get("age")
        family_history_gastric_cancer = bool(ctx.get("family_history_gastric_cancer_first_degree"))
        hereditary_syndrome = bool(ctx.get("hereditary_gi_polyposis_or_cancer_syndrome"))

        chronic_h_pylori_infection = bool(ctx.get("chronic_h_pylori_infection"))
        smoking_pack_years = ctx.get("smoking_pack_years")
        heavy_smoking = (smoking_pack_years is not None and smoking_pack_years > 20)
        high_risk_diet = bool(ctx.get("high_salt_or_red_processed_meat_diet"))
        low_socioeconomic_status = bool(ctx.get("low_socioeconomic_status"))

        h_pylori_lifestyle_cluster = chronic_h_pylori_infection and any([
            heavy_smoking,
            high_risk_diet,
            low_socioeconomic_status,
        ])

        count = 0
        factors = []

        if family_history_gastric_cancer:
            count += 1
            factors.append("Family history of gastric cancer in a first-degree relative")
        if hereditary_syndrome:
            count += 1
            factors.append("Hereditary GI polyposis/cancer syndrome")
        if h_pylori_lifestyle_cluster:
            count += 1
            factors.append("Chronic H. pylori infection plus smoking/diet/low socioeconomic risk cluster")

        threshold = _screening_age_threshold(ctx)
        age_met = (age is not None and age >= threshold)

        return {
            "risk_factor_count": count,
            "risk_factors": factors,
            "screening_age_threshold": threshold,
            "screening_age_met": age_met,
            "family_history_gastric_cancer_first_degree": family_history_gastric_cancer,
            "hereditary_gi_polyposis_or_cancer_syndrome": hereditary_syndrome,
            "chronic_h_pylori_infection": chronic_h_pylori_infection,
            "smoking_pack_years": smoking_pack_years,
            "heavy_smoking": heavy_smoking,
            "high_salt_or_red_processed_meat_diet": high_risk_diet,
            "low_socioeconomic_status": low_socioeconomic_status,
            "h_pylori_lifestyle_cluster": h_pylori_lifestyle_cluster,
        }

    # -----------------------------------------------------
    # Node 1 – Route context
    # -----------------------------------------------------

    def node_route_context(ctx: Context):
        node_id = "Route_Context"

        patient_context = ctx.get("patient_context")
        if patient_context is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["patient_context"],
                message="Need explicit gastric cancer pathway context.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_PATIENT_CONTEXT",
                        label="Set patient context: prevention / asymptomatic_screening / symptomatic_dyspepsia",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 5},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["patient_context"]}, [dr])
            return NodeResult([dr])

        valid = patient_context in ["prevention", "asymptomatic_screening", "symptomatic_dyspepsia"]
        valid = ctx.apply_override(node_id, "patient_context_valid", valid)
        ctx.set("patient_context_valid", valid)

        if not valid:
            stop = Stop(
                reason="Invalid gastric cancer pathway context.",
                actions=[
                    Action(
                        code="INVALID_CONTEXT",
                        label="Patient context must be prevention, asymptomatic_screening, or symptomatic_dyspepsia.",
                        override_options={
                            "node": node_id,
                            "field": "patient_context_valid",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 5},
                    )
                ],
            )
            ctx.log(node_id, "INVALID_CONTEXT", {"patient_context": patient_context}, [stop])
            return NodeResult([stop])

        prevention = _prevention_actions(ctx)

        if patient_context == "prevention":
            stop = Stop(
                reason="Primary prevention branch completed.",
                actions=prevention + [
                    Action(
                        code="PRIMARY_PREVENTION_COMPLETE",
                        label="Primary prevention counseling completed.",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 10},
                    )
                ],
            )
            ctx.log(node_id, "ROUTE_PREVENTION", {"patient_context": patient_context}, [stop])
            return NodeResult([stop])

        if patient_context == "asymptomatic_screening":
            ctx.log(node_id, "ROUTE_ASYMPTOMATIC_SCREENING", {"patient_context": patient_context}, prevention)
            return NodeResult(prevention, next_node="Targeted_Screening_Risk_Assessment")

        ctx.log(node_id, "ROUTE_SYMPTOMATIC", {"patient_context": patient_context}, prevention)
        return NodeResult(prevention, next_node="Symptomatic_Dyspepsia_Assessment")

    nodes["Route_Context"] = Node("Route_Context", node_route_context)

    # -----------------------------------------------------
    # Node 2 – Targeted Screening Risk Assessment
    # -----------------------------------------------------

    def node_targeted_screening(ctx: Context):
        node_id = "Targeted_Screening_Risk_Assessment"

        if ctx.get("asymptomatic") is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["asymptomatic"],
                message="Need asymptomatic status for targeted screening branch.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_ASYMPTOMATIC_STATUS",
                        label="Document whether patient is asymptomatic",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["asymptomatic"]}, [dr])
            return NodeResult([dr])

        if ctx.get("asymptomatic") is not True:
            stop = Stop(
                reason="Targeted screening branch applies to asymptomatic patients only.",
                actions=[
                    Action(
                        code="NOT_ASYMPTOMATIC_SCREENING_CANDIDATE",
                        label="Not an asymptomatic screening candidate.",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 31},
                    )
                ],
            )
            ctx.log(node_id, "NOT_ASYMPTOMATIC", {"asymptomatic": ctx.get("asymptomatic")}, [stop])
            return NodeResult([stop])

        if ctx.get("age") is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["age"],
                message="Need age to assess targeted screening eligibility.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_AGE",
                        label="Capture patient age",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["age"]}, [dr])
            return NodeResult([dr])

        risk = _screening_risk_factor_count(ctx)

        screening_indicated = bool(risk["screening_age_met"] and risk["risk_factor_count"] >= 1)
        screening_indicated = ctx.apply_override(node_id, "screening_indicated", screening_indicated)
        ctx.set("screening_indicated", screening_indicated)

        if screening_indicated:
            stop = Stop(
                reason="Targeted gastric cancer screening may be indicated.",
                actions=[
                    Action(
                        code="CONSIDER_ELECTIVE_SCREENING_ENDOSCOPY",
                        label="Consider elective screening endoscopy referral",
                        details={
                            "supported_by": [
                                f"Age threshold met: {risk['screening_age_met']} (threshold {risk['screening_age_threshold']})",
                                f"Risk factor count: {risk['risk_factor_count']}",
                            ] + risk["risk_factors"],
                        },
                        override_options={
                            "node": node_id,
                            "field": "screening_indicated",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 12},
                    )
                ],
            )
            ctx.log(node_id, "SCREENING_INDICATED", risk, [stop])
            return NodeResult([stop])

        stop = Stop(
            reason="Targeted gastric cancer screening is not indicated at this time.",
            actions=[
                Action(
                    code="SCREENING_NOT_INDICATED",
                    label="Gastric cancer screening not indicated at this time; continue prevention counseling and reassess if symptoms develop.",
                    details=risk,
                    override_options={
                        "node": node_id,
                        "field": "screening_indicated",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 13},
                )
            ],
        )
        ctx.log(node_id, "SCREENING_NOT_INDICATED", risk, [stop])
        return NodeResult([stop])

    nodes["Targeted_Screening_Risk_Assessment"] = Node("Targeted_Screening_Risk_Assessment", node_targeted_screening)

    # -----------------------------------------------------
    # Node 3 – Symptomatic Dyspepsia Assessment
    # -----------------------------------------------------

    def node_symptomatic_dyspepsia(ctx: Context):
        node_id = "Symptomatic_Dyspepsia_Assessment"

        symptomatic = ctx.get("symptomatic_dyspepsia_over_1_month")
        if symptomatic is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["symptomatic_dyspepsia_over_1_month"],
                message="Need to know whether patient has dyspepsia symptoms for more than 1 month.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_DYSPEPSIA_STATUS",
                        label="Document dyspepsia symptoms >1 month",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["symptomatic_dyspepsia_over_1_month"]}, [dr])
            return NodeResult([dr])

        if symptomatic is not True:
            stop = Stop(
                reason="Symptomatic branch requires dyspepsia symptoms >1 month.",
                actions=[
                    Action(
                        code="NOT_SYMPTOMATIC_DYSPEPSIA",
                        label="Does not meet symptomatic dyspepsia branch criteria.",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 41},
                    )
                ],
            )
            ctx.log(node_id, "NOT_SYMPTOMATIC_DYSPEPSIA", {"symptomatic_dyspepsia_over_1_month": symptomatic}, [stop])
            return NodeResult([stop])

        # Chain into dyspepsia engine when available
        actions: List[Output] = [
            Action(
                code="CHAIN_DYSPEPSIA_PATHWAY",
                label="Assess as per dyspepsia pathway.",
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 42},
            )
        ]

        if DYSPepsia_ENGINE_AVAILABLE:
            dys_inputs = ctx.get("dyspepsia_patient_data")
            if isinstance(dys_inputs, dict):
                try:
                    dys_outputs, _, _ = run_dyspepsia_pathway(dys_inputs)
                    # Convert only Action outputs into supportive actions for presentation.
                    for o in dys_outputs:
                        if isinstance(o, Action):
                            actions.append(Action(
                                code=f"DYSP_{o.code}",
                                label=f"Dyspepsia: {o.label}",
                                urgency=o.urgency,
                                details=o.details,
                                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 43},
                            ))
                except Exception:
                    actions.append(Action(
                        code="DYSPEPSIA_CHAIN_FAILED",
                        label="Dyspepsia engine chaining unavailable at runtime; review dyspepsia pathway separately.",
                        display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 43},
                    ))
            else:
                actions.append(Action(
                    code="DYSPEPSIA_INPUT_MISSING",
                    label="Provide dyspepsia_patient_data to fully chain into the dyspepsia engine.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 43},
                ))
        else:
            actions.append(Action(
                code="ROUTE_DYSPEPSIA_PATHWAY",
                label="Dyspepsia engine unavailable in this environment; route to dyspepsia pathway.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 43},
            ))

        ctx.log(node_id, "CHAINED_TO_DYSPEPSIA", {}, actions)
        return NodeResult(actions, next_node="Alarm_Features_Symptomatic")

    nodes["Symptomatic_Dyspepsia_Assessment"] = Node("Symptomatic_Dyspepsia_Assessment", node_symptomatic_dyspepsia)

    # -----------------------------------------------------
    # Node 4 – Symptomatic alarm features
    # -----------------------------------------------------

    def node_alarm_symptomatic(ctx: Context):
        node_id = "Alarm_Features_Symptomatic"

        fh_gastric_or_esophageal = bool(ctx.get("family_history_gastric_or_esophageal_cancer_first_degree"))
        onset_after_60 = bool(ctx.get("symptom_onset_after_age_60"))
        unintended_weight_loss = bool(ctx.get("unintended_weight_loss"))
        black_stool_or_blood_in_vomit = bool(ctx.get("black_stool_or_blood_in_vomit"))
        dysphagia = bool(ctx.get("dysphagia"))
        persistent_vomiting = bool(ctx.get("persistent_vomiting"))
        iron_deficiency_anemia_present = bool(ctx.get("iron_deficiency_anemia_present"))
        concerning_imaging_for_gastric_cancer = bool(ctx.get("concerning_imaging_for_gastric_cancer"))

        alarm_present = any([
            fh_gastric_or_esophageal,
            onset_after_60,
            unintended_weight_loss,
            black_stool_or_blood_in_vomit,
            dysphagia,
            persistent_vomiting,
            iron_deficiency_anemia_present,
            concerning_imaging_for_gastric_cancer,
        ])
        alarm_present = ctx.apply_override(node_id, "symptomatic_alarm_features_present", alarm_present)
        ctx.set("symptomatic_alarm_features_present", alarm_present)

        if alarm_present:
            stop = Stop(
                reason="Symptomatic alarm features concerning for gastric/esophageal malignancy – urgent referral.",
                urgency="urgent",
                actions=[
                    Action(
                        code="URGENT_GI_ENDOSCOPY_REFERRAL",
                        label="Urgent referral to local GI/endoscopy provider",
                        urgency="urgent",
                        details={
                            "supported_by": [
                                "At least one symptomatic gastric/esophageal cancer alarm feature is present"
                            ],
                            "family_history_gastric_or_esophageal_cancer_first_degree": fh_gastric_or_esophageal,
                            "symptom_onset_after_age_60": onset_after_60,
                            "unintended_weight_loss": unintended_weight_loss,
                            "black_stool_or_blood_in_vomit": black_stool_or_blood_in_vomit,
                            "dysphagia": dysphagia,
                            "persistent_vomiting": persistent_vomiting,
                            "iron_deficiency_anemia_present": iron_deficiency_anemia_present,
                            "concerning_imaging_for_gastric_cancer": concerning_imaging_for_gastric_cancer,
                        },
                        override_options={
                            "node": node_id,
                            "field": "symptomatic_alarm_features_present",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 50},
                    )
                ],
            )
            ctx.log(node_id, "SYMPTOMATIC_ALARM_PRESENT", {
                "family_history_gastric_or_esophageal_cancer_first_degree": fh_gastric_or_esophageal,
                "concerning_imaging_for_gastric_cancer": concerning_imaging_for_gastric_cancer,
            }, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="NO_SYMPTOMATIC_ALARM_FEATURES",
                label="No gastric/esophageal cancer alarm features identified in symptomatic branch.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 51},
            )
        ]
        ctx.log(node_id, "SYMPTOMATIC_ALARM_ABSENT", {}, out)
        return NodeResult(out, next_node="Management_Response_Symptomatic")

    nodes["Alarm_Features_Symptomatic"] = Node("Alarm_Features_Symptomatic", node_alarm_symptomatic)

    # -----------------------------------------------------
    # Node 5 – Management response symptomatic
    # -----------------------------------------------------

    def node_management_response_symptomatic(ctx: Context):
        node_id = "Management_Response_Symptomatic"

        unsat = ctx.get("unsatisfactory_response_to_management")
        if unsat is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["unsatisfactory_response_to_management"],
                message="Need overall response to symptomatic management.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_MANAGEMENT_RESPONSE",
                        label="Document whether symptomatic management response is unsatisfactory",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 60},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["unsatisfactory_response_to_management"]}, [dr])
            return NodeResult([dr])

        unsat = ctx.apply_override(node_id, "unsatisfactory_response_to_management", unsat)
        ctx.set("unsatisfactory_response_to_management", unsat)

        if unsat:
            actions: List[Output] = [
                Action(
                    code="CONSIDER_ADVICE_SERVICE",
                    label="Consider using an advice service before referring.",
                    details={"supported_by": ["Unsatisfactory response to symptomatic management"]},
                    override_options={
                        "node": node_id,
                        "field": "unsatisfactory_response_to_management",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 61},
                )
            ]

            if ctx.get("advice_service_considered") is True:
                stop = Stop(
                    reason="Unsatisfactory symptomatic response after management – refer to GI/endoscopy provider.",
                    actions=[
                        Action(
                            code="REFER_FAILED_SYMPTOMATIC_MANAGEMENT",
                            label="Refer due to failed symptomatic management",
                            display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 62},
                        )
                    ],
                )
                ctx.log(node_id, "FAILED_MANAGEMENT_REFER", {"advice_service_considered": True}, actions + [stop])
                return NodeResult(actions + [stop])

            ctx.log(node_id, "FAILED_MANAGEMENT_ADVICE_FIRST", {"advice_service_considered": ctx.get("advice_service_considered")}, actions)
            return NodeResult(actions)

        stop = Stop(
            reason="No gastric cancer escalation criteria currently identified in symptomatic branch; continue primary care/dyspepsia management.",
            actions=[
                Action(
                    code="CONTINUE_PRIMARY_CARE_MANAGEMENT",
                    label="Continue primary care / dyspepsia management",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 63},
                )
            ],
        )
        ctx.log(node_id, "PATHWAY_COMPLETE", {}, [stop])
        return NodeResult([stop])

    nodes["Management_Response_Symptomatic"] = Node("Management_Response_Symptomatic", node_management_response_symptomatic)

    return PathwayEngine(
        nodes=nodes,
        start_node="Route_Context"
    )


# =========================================================
# RUNNER
# =========================================================

def run_gastric_cancer_pathway(patient_data: Dict[str, Any], overrides=None):
    engine = gastric_cancer_build_engine()

    ctx = Context(
        data=dict(patient_data),
        overrides=overrides or []
    )

    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx.overrides