# -*- coding: utf-8 -*-
"""gerd_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODhpZwIpzwuED7Yk7qVK3yyEBdQb0_RP
"""

"""
========================================================
PATHWAY FILE: Gastroesophageal Reflux Disease (GERD)
========================================================

Design goals
- Same architecture as other pathway engines
- Progressive gating with DataRequest where appropriate
- UI-friendly outputs: Action / DataRequest / Stop
- Audit log support
- Override capability
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone

# Optional chained dyspepsia engine import
try:
    from dyspepsia_engine import run_dyspepsia_pathway
    DYSPEPSIA_ENGINE_AVAILABLE = True
except Exception:
    DYSPEPSIA_ENGINE_AVAILABLE = False


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# GERD PATHWAY IMPLEMENTATION
# =========================================================

def gerd_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # Helpers
    # -----------------------------------------------------

    def _central_obesity(ctx: Context) -> Dict[str, Any]:
        sex = str(ctx.get("sex")).lower() if ctx.get("sex") is not None else None
        waist = ctx.get("waist_circumference_cm")
        whr = ctx.get("waist_hip_ratio")

        waist_positive = False
        whr_positive = False

        if sex == "male":
            waist_positive = waist is not None and waist >= 102
            whr_positive = whr is not None and whr > 0.9
        elif sex == "female":
            waist_positive = waist is not None and waist >= 88
            whr_positive = whr is not None and whr > 0.8

        return {
            "waist_positive": waist_positive,
            "whr_positive": whr_positive,
            "central_obesity": bool(waist_positive or whr_positive),
        }

    def _barretts_rule_algorithm(ctx: Context) -> Dict[str, Any]:
        # Algorithm page style: >5 years and/or weekly+ symptoms + >=3 RFs
        symptom_years = ctx.get("gerd_symptom_years")
        symptoms_per_week = ctx.get("symptoms_per_week")

        chronic = symptom_years is not None and symptom_years > 5
        frequent = symptoms_per_week is not None and symptoms_per_week >= 1

        central = _central_obesity(ctx)
        risk_count = 0
        risks = []

        if str(ctx.get("sex")).lower() == "male":
            risk_count += 1
            risks.append("Male sex")
        if ctx.get("age") is not None and ctx.get("age") > 50:
            risk_count += 1
            risks.append("Age >50")
        if bool(ctx.get("caucasian")):
            risk_count += 1
            risks.append("Caucasian")
        if bool(ctx.get("current_or_history_smoking")):
            risk_count += 1
            risks.append("Current or history of smoking")
        if central["central_obesity"]:
            risk_count += 1
            risks.append("Central obesity")
        if bool(ctx.get("family_history_barretts_or_esophageal_cancer_first_degree")):
            risk_count += 1
            risks.append("First-degree family history of Barrett’s or esophageal cancer")

        indicated = bool((chronic or frequent) and risk_count >= 3)

        return {
            "rule_name": "algorithm_page",
            "chronic": chronic,
            "frequent": frequent,
            "risk_count": risk_count,
            "risk_factors": risks,
            "indicated": indicated,
        }

    def _barretts_rule_expanded(ctx: Context) -> Dict[str, Any]:
        # Expanded details: males >10 years and/or weekly+ symptoms and at least 2 RFs
        symptom_years = ctx.get("gerd_symptom_years")
        symptoms_per_week = ctx.get("symptoms_per_week")
        sex = str(ctx.get("sex")).lower() if ctx.get("sex") is not None else None

        chronic = symptom_years is not None and symptom_years > 10
        frequent = symptoms_per_week is not None and symptoms_per_week >= 1

        central = _central_obesity(ctx)
        risk_count = 0
        risks = []

        if ctx.get("age") is not None and ctx.get("age") > 50:
            risk_count += 1
            risks.append("Age >50")
        if bool(ctx.get("caucasian")):
            risk_count += 1
            risks.append("Caucasian")
        if bool(ctx.get("current_or_history_smoking")):
            risk_count += 1
            risks.append("Current or history of smoking")
        if central["central_obesity"]:
            risk_count += 1
            risks.append("Central obesity")
        if bool(ctx.get("family_history_barretts_or_esophageal_cancer_first_degree")):
            risk_count += 1
            risks.append("First-degree family history of Barrett’s or esophageal cancer")

        if sex == "male":
            indicated = bool((chronic or frequent) and risk_count >= 2)
        elif sex == "female":
            indicated = False
        else:
            indicated = False

        female_soft_note = bool(
            sex == "female"
            and (chronic or frequent)
            and risk_count >= 2
        )

        return {
            "rule_name": "expanded_details",
            "chronic": chronic,
            "frequent": frequent,
            "risk_count": risk_count,
            "risk_factors": risks,
            "indicated": indicated,
            "female_soft_note": female_soft_note,
        }

    # -----------------------------------------------------
    # Node 1 – Suspected GERD
    # -----------------------------------------------------

    def node_suspected_gerd(ctx: Context):
        node_id = "Suspected_GERD"

        predominant_heartburn = ctx.get("predominant_heartburn")
        predominant_regurgitation = ctx.get("predominant_regurgitation")

        missing = []
        if predominant_heartburn is None:
            missing.append("predominant_heartburn")
        if predominant_regurgitation is None:
            missing.append("predominant_regurgitation")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need predominant GERD symptoms to determine pathway entry.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_GERD_ENTRY",
                        label="Capture predominant heartburn and regurgitation symptoms",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult([dr])

        suspected_gerd = bool(predominant_heartburn or predominant_regurgitation)
        suspected_gerd = ctx.apply_override(node_id, "suspected_gerd", suspected_gerd)
        ctx.set("suspected_gerd", suspected_gerd)

        actions: List[Output] = []

        if bool(ctx.get("dominant_chest_pain")):
            actions.append(Action(
                code="CARDIAC_WORKUP_WARNING",
                label="If chest pain is a dominant feature, exclude cardiac causes first. GERD treatment can begin while cardiac workup proceeds.",
                details={"supported_by": ["Dominant chest pain reported"]},
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 11},
            ))

        if not suspected_gerd:
            stop = Stop(
                reason="GERD pathway entry criteria not met.",
                actions=actions + [
                    Action(
                        code="NOT_GERD",
                        label="Does not meet suspected GERD entry criteria.",
                        override_options={
                            "node": node_id,
                            "field": "suspected_gerd",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 12},
                    )
                ],
            )
            ctx.log(node_id, "ENTRY_CRITERIA_NOT_MET", {
                "predominant_heartburn": predominant_heartburn,
                "predominant_regurgitation": predominant_regurgitation,
                "dominant_chest_pain": ctx.get("dominant_chest_pain"),
            }, [stop])
            return NodeResult([stop])

        out = actions + [
            Action(
                code="GERD_ENTRY_MET",
                label="Suspected GERD entry criteria met.",
                details={
                    "supported_by": ["Predominant symptom is heartburn and/or regurgitation"]
                },
                override_options={
                    "node": node_id,
                    "field": "suspected_gerd",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 13},
            )
        ]
        ctx.log(node_id, "ENTRY_CRITERIA_MET", {
            "predominant_heartburn": predominant_heartburn,
            "predominant_regurgitation": predominant_regurgitation,
            "dominant_chest_pain": ctx.get("dominant_chest_pain"),
        }, out)
        return NodeResult(out, next_node="Dyspepsia_Screen")

    nodes["Suspected_GERD"] = Node("Suspected_GERD", node_suspected_gerd)

    # -----------------------------------------------------
    # Node 2 – Dyspepsia Screen
    # -----------------------------------------------------

    def node_dyspepsia_screen(ctx: Context):
        node_id = "Dyspepsia_Screen"

        predominant_epigastric_pain = bool(ctx.get("predominant_epigastric_pain"))
        predominant_upper_abdominal_bloating = bool(ctx.get("predominant_upper_abdominal_bloating"))

        route_dyspepsia = bool(predominant_epigastric_pain or predominant_upper_abdominal_bloating)
        route_dyspepsia = ctx.apply_override(node_id, "route_dyspepsia", route_dyspepsia)
        ctx.set("route_dyspepsia", route_dyspepsia)

        if route_dyspepsia:
            actions: List[Action] = [
                Action(
                    code="ROUTE_DYSPEPSIA_PATHWAY",
                    label="Route to dyspepsia pathway",
                    details={"supported_by": ["Predominant symptom is epigastric pain/discomfort and/or upper abdominal bloating"]},
                    override_options={
                        "node": node_id,
                        "field": "route_dyspepsia",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 20},
                )
            ]

            if DYSPEPSIA_ENGINE_AVAILABLE:
                dys_inputs = ctx.get("dyspepsia_patient_data")
                if isinstance(dys_inputs, dict):
                    try:
                        dys_outputs, _, _ = run_dyspepsia_pathway(dys_inputs)
                        for o in dys_outputs:
                            if isinstance(o, Action):
                                actions.append(Action(
                                    code=f"DYSP_{o.code}",
                                    label=f"Dyspepsia: {o.label}",
                                    urgency=o.urgency,
                                    details=o.details,
                                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 21},
                                ))
                    except Exception:
                        actions.append(Action(
                            code="DYSPEPSIA_CHAIN_FAILED",
                            label="Dyspepsia engine chaining unavailable at runtime; review dyspepsia pathway separately.",
                            display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 21},
                        ))

            stop = Stop(
                reason="Predominant symptoms are dyspeptic rather than reflux-predominant.",
                actions=actions,
            )
            ctx.log(node_id, "ROUTE_DYSPEPSIA", {
                "predominant_epigastric_pain": predominant_epigastric_pain,
                "predominant_upper_abdominal_bloating": predominant_upper_abdominal_bloating,
            }, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="NOT_DYSPEPSIA_PREDOMINANT",
                label="Predominant symptoms are not dyspeptic.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 22},
            )
        ]
        ctx.log(node_id, "NOT_DYSPEPSIA", {
            "predominant_epigastric_pain": predominant_epigastric_pain,
            "predominant_upper_abdominal_bloating": predominant_upper_abdominal_bloating,
        }, out)
        return NodeResult(out, next_node="Alarm_Features")

    nodes["Dyspepsia_Screen"] = Node("Dyspepsia_Screen", node_dyspepsia_screen)

    # -----------------------------------------------------
    # Node 3 – Alarm Features
    # -----------------------------------------------------

    def node_alarm(ctx: Context):
        node_id = "Alarm_Features"

        if bool(ctx.get("actively_bleeding_now")):
            stop = Stop(
                reason="Possible active upper GI bleeding – urgent emergency assessment required.",
                urgency="urgent",
                actions=[
                    Action(
                        code="EMERGENT_BLEEDING_ASSESSMENT",
                        label="Immediate emergency assessment / GI on-call / ED",
                        urgency="urgent",
                        details={"supported_by": ["Active bleeding now"]},
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 1},
                    )
                ],
            )
            ctx.log(node_id, "ACTIVE_BLEEDING", {"actively_bleeding_now": True}, [stop])
            return NodeResult([stop])

        unintended_weight_loss = bool(ctx.get("unintended_weight_loss"))
        progressive_dysphagia = bool(ctx.get("progressive_dysphagia"))
        odynophagia = bool(ctx.get("odynophagia"))
        persistent_vomiting = bool(ctx.get("persistent_vomiting"))
        black_stool_or_blood_in_vomit = bool(ctx.get("black_stool_or_blood_in_vomit"))
        iron_deficiency_anemia_present = bool(ctx.get("iron_deficiency_anemia_present"))
        abdominal_mass = bool(ctx.get("abdominal_mass"))

        alarm_present = any([
            unintended_weight_loss,
            progressive_dysphagia,
            odynophagia,
            persistent_vomiting,
            black_stool_or_blood_in_vomit,
            iron_deficiency_anemia_present,
            abdominal_mass,
        ])
        alarm_present = ctx.apply_override(node_id, "alarm_features_present", alarm_present)
        ctx.set("alarm_features_present", alarm_present)

        if alarm_present:
            actions = [
                Action(
                    code="URGENT_ENDOSCOPY_REFERRAL",
                    label="Urgent referral for consultation/endoscopy",
                    urgency="urgent",
                    details={
                        "supported_by": ["At least one GERD alarm feature is present"],
                        "unintended_weight_loss": unintended_weight_loss,
                        "progressive_dysphagia": progressive_dysphagia,
                        "odynophagia": odynophagia,
                        "persistent_vomiting": persistent_vomiting,
                        "black_stool_or_blood_in_vomit": black_stool_or_blood_in_vomit,
                        "iron_deficiency_anemia_present": iron_deficiency_anemia_present,
                        "abdominal_mass": abdominal_mass,
                    },
                    override_options={
                        "node": node_id,
                        "field": "alarm_features_present",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 30},
                )
            ]

            if black_stool_or_blood_in_vomit:
                actions.append(Action(
                    code="BLEEDING_REFERRAL_LABS",
                    label="If black stool or blood in vomit is present, include CBC, INR, and BUN as part of referral.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 31},
                ))

            stop = Stop(
                reason="Alarm features present – urgent referral for consultation/endoscopy.",
                urgency="urgent",
                actions=actions,
            )
            ctx.log(node_id, "ALARM_FEATURES_PRESENT", {
                "unintended_weight_loss": unintended_weight_loss,
                "progressive_dysphagia": progressive_dysphagia,
                "odynophagia": odynophagia,
                "persistent_vomiting": persistent_vomiting,
                "black_stool_or_blood_in_vomit": black_stool_or_blood_in_vomit,
                "iron_deficiency_anemia_present": iron_deficiency_anemia_present,
                "abdominal_mass": abdominal_mass,
            }, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="NO_ALARM_FEATURES",
                label="No GERD alarm features present.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 32},
            )
        ]
        ctx.log(node_id, "NO_ALARM_FEATURES", {}, out)
        return NodeResult(out, next_node="Barretts_Risk_Assessment")

    nodes["Alarm_Features"] = Node("Alarm_Features", node_alarm)

    # -----------------------------------------------------
    # Node 4 – Barrett's Risk Assessment
    # -----------------------------------------------------

    def node_barretts(ctx: Context):
        node_id = "Barretts_Risk_Assessment"
        actions: List[Output] = []

        if bool(ctx.get("known_barretts_esophagus")):
            actions.append(Action(
                code="KNOWN_BARRETTS_LIFETIME_PPI",
                label="Known Barrett’s esophagus: lifetime daily PPI is recommended.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
            ))

        if bool(ctx.get("barretts_screen_positive")):
            stop = Stop(
                reason="Positive Barrett’s esophagus screening – refer for consultation/endoscopy.",
                actions=[
                    Action(
                        code="REFER_POSITIVE_BARRETTS_SCREEN",
                        label="Refer for positive Barrett’s esophagus screening",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 41},
                    )
                ],
            )
            ctx.log(node_id, "BARRETTS_POSITIVE", {"barretts_screen_positive": True}, actions + [stop])
            return NodeResult(actions + [stop])

        alg = _barretts_rule_algorithm(ctx)
        exp = _barretts_rule_expanded(ctx)

        if alg["indicated"] != exp["indicated"]:
            actions.append(Action(
                code="BARRETTS_RULE_DISAGREEMENT_NOTE",
                label="Barrett’s screening rules differ between algorithm box and expanded details; review clinically.",
                details={
                    "algorithm_page_indicated": alg["indicated"],
                    "expanded_details_indicated": exp["indicated"],
                    "algorithm_page_risk_count": alg["risk_count"],
                    "expanded_details_risk_count": exp["risk_count"],
                },
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 42},
            ))

        if bool(ctx.get("history_of_sleeve_gastrectomy")):
            actions.append(Action(
                code="CONSIDER_BARRETTS_SCREENING_SLEEVE",
                label="Consider Barrett’s screening in those with sleeve gastrectomy.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 43},
            ))

        if exp["female_soft_note"]:
            actions.append(Action(
                code="BARRETTS_FEMALE_SOFT_NOTE",
                label="Females have lower esophageal cancer risk; Barrett’s screening may be considered only with multiple risk factors.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 44},
            ))

        if exp["indicated"]:
            actions.append(Action(
                code="CONSIDER_BARRETTS_SCREENING",
                label="Consider referral for Barrett’s esophagus screening.",
                details={
                    "supported_by": [
                        "Expanded-details Barrett’s screening rule met"
                    ] + exp["risk_factors"],
                    "expanded_details_indicated": exp["indicated"],
                    "algorithm_page_indicated": alg["indicated"],
                },
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 45},
            ))
        else:
            actions.append(Action(
                code="BARRETTS_SCREENING_NOT_INDICATED",
                label="Barrett’s screening not clearly indicated based on current data.",
                details={
                    "expanded_details_indicated": exp["indicated"],
                    "algorithm_page_indicated": alg["indicated"],
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 46},
            ))

        ctx.log(node_id, "BARRETTS_ASSESSED", {
            "algorithm_page_indicated": alg["indicated"],
            "expanded_details_indicated": exp["indicated"],
        }, actions)
        return NodeResult(actions, next_node="Non_Pharmacologic_Therapy")

    nodes["Barretts_Risk_Assessment"] = Node("Barretts_Risk_Assessment", node_barretts)

    # -----------------------------------------------------
    # Node 5 – Non-pharmacologic Therapy
    # -----------------------------------------------------

    def node_non_pharm(ctx: Context):
        node_id = "Non_Pharmacologic_Therapy"

        out = [
            Action(
                code="COUNSEL_SMOKING_CESSATION",
                label="Smoking cessation is essential.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
            ),
            Action(
                code="COUNSEL_WEIGHT_LOSS",
                label="Recommend weight loss if overweight or recently gained weight.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
            ),
            Action(
                code="COUNSEL_SMALLER_MEALS",
                label="Avoid large meals; choose smaller, more frequent meals.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
            ),
            Action(
                code="COUNSEL_MEAL_TIMING",
                label="Avoid meals within 3 hours of lying down if nocturnal symptoms are present.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
            ),
            Action(
                code="COUNSEL_TRIGGER_LOG",
                label="Keep a food and symptom log to identify triggers.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
            ),
            Action(
                code="COUNSEL_HEAD_OF_BED",
                label="Consider elevating the head of bed 4–6 inches; extra pillows are not sufficient.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
            ),
        ]

        ctx.log(node_id, "NON_PHARM_EMITTED", {}, out)
        return NodeResult(out, next_node="Pharmacologic_Therapy")

    nodes["Non_Pharmacologic_Therapy"] = Node("Non_Pharmacologic_Therapy", node_non_pharm)

    # -----------------------------------------------------
    # Node 6 – Pharmacologic Therapy
    # -----------------------------------------------------

    def node_pharmacologic(ctx: Context):
        node_id = "Pharmacologic_Therapy"

        symptoms_per_week = ctx.get("symptoms_per_week")
        if symptoms_per_week is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["symptoms_per_week"],
                message="Need symptom frequency to select initial GERD pharmacologic pathway.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_SYMPTOM_FREQUENCY",
                        label="Capture GERD symptom frequency per week",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 60},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["symptoms_per_week"]}, [dr])
            return NodeResult([dr])

        # Mild/infrequent branch
        if symptoms_per_week < 2:
            out = [
                Action(
                    code="H2RA_OR_ANTACID_PRN",
                    label="If symptoms are mild and infrequent (<2 times/week), consider H2RA or antacids as needed.",
                    details={"supported_by": [f"Symptoms per week: {symptoms_per_week} (<2)"]},
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 61},
                )
            ]
            ctx.log(node_id, "MILD_INFREQUENT_BRANCH", {"symptoms_per_week": symptoms_per_week}, out)
            return NodeResult(out, next_node="Management_Response")

        # PPI branch
        ppi_once_daily_trial_done = ctx.get("ppi_once_daily_trial_done")
        if ppi_once_daily_trial_done is None:
            out = [
                Action(
                    code="START_PPI_ONCE_DAILY",
                    label="Start PPI once daily for 4–8 weeks, 30 minutes before breakfast on an empty stomach.",
                    details={"supported_by": [f"Symptoms per week: {symptoms_per_week} (>=2)"]},
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 62},
                )
            ]
            ctx.log(node_id, "START_PPI_ONCE_DAILY", {"symptoms_per_week": symptoms_per_week}, out)
            return NodeResult(out, next_node="Management_Response")

        ppi_once_daily_response_adequate = ctx.get("ppi_once_daily_response_adequate")
        if ppi_once_daily_trial_done is True and ppi_once_daily_response_adequate is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["ppi_once_daily_response_adequate"],
                message="Need response to once-daily PPI trial.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_PPI_ONCE_DAILY_RESPONSE",
                        label="Capture response to once-daily PPI",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 63},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["ppi_once_daily_response_adequate"]}, [dr])
            return NodeResult([dr])

        if ppi_once_daily_trial_done is True and ppi_once_daily_response_adequate is True:
            out = [
                Action(
                    code="PPI_ONCE_DAILY_SUCCESS",
                    label="Symptoms controlled with once-daily PPI.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 64},
                )
            ]
            ctx.log(node_id, "PPI_ONCE_DAILY_SUCCESS", {}, out)
            return NodeResult(out, next_node="Maintenance_Or_Deprescribing")

        # Before declaring failure, check correct use/adherence
        ppi_taken_correctly_before_breakfast = ctx.get("ppi_taken_correctly_before_breakfast")
        ppi_adherence_adequate = ctx.get("ppi_adherence_adequate")

        if ppi_taken_correctly_before_breakfast is None or ppi_adherence_adequate is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=[
                    k for k in [
                        "ppi_taken_correctly_before_breakfast",
                        "ppi_adherence_adequate"
                    ] if ctx.get(k) is None
                ],
                message="Before escalating GERD therapy, confirm PPI timing and adherence.",
                suggested_actions=[
                    Action(
                        code="CONFIRM_PPI_USE",
                        label="Confirm intended dose was taken daily, 30 minutes before breakfast, with adequate adherence",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 65},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {
                "missing": [k for k in ["ppi_taken_correctly_before_breakfast", "ppi_adherence_adequate"] if ctx.get(k) is None]
            }, [dr])
            return NodeResult([dr])

        actions: List[Output] = []
        if not ppi_taken_correctly_before_breakfast or not ppi_adherence_adequate:
            actions.append(Action(
                code="OPTIMIZE_PPI_ADHERENCE",
                label="Optimize PPI adherence and timing before declaring treatment failure.",
                details={
                    "ppi_taken_correctly_before_breakfast": ppi_taken_correctly_before_breakfast,
                    "ppi_adherence_adequate": ppi_adherence_adequate,
                },
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 66},
            ))

        actions.append(Action(
            code="OPTIMIZE_PPI_BID",
            label="If inadequate response after 8 weeks, step up to PPI twice daily for 4–8 weeks, or switch to a different PPI.",
            display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 67},
        ))

        ppi_bid_trial_done = ctx.get("ppi_bid_trial_done")
        ppi_bid_response_adequate = ctx.get("ppi_bid_response_adequate")

        if ppi_bid_trial_done is None:
            ctx.log(node_id, "PPI_BID_RECOMMENDED", {}, actions)
            return NodeResult(actions, next_node="Management_Response")

        if ppi_bid_trial_done is True and ppi_bid_response_adequate is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["ppi_bid_response_adequate"],
                message="Need response to optimized twice-daily PPI trial.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_PPI_BID_RESPONSE",
                        label="Capture response to twice-daily PPI",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 68},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["ppi_bid_response_adequate"]}, [dr])
            return NodeResult([dr])

        if ppi_bid_trial_done is True and ppi_bid_response_adequate is True:
            actions.append(Action(
                code="PPI_BID_SUCCESS",
                label="Symptoms controlled with twice-daily PPI.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 69},
            ))
            ctx.log(node_id, "PPI_BID_SUCCESS", {}, actions)
            return NodeResult(actions, next_node="Maintenance_Or_Deprescribing")

        actions.append(Action(
            code="PERSISTENT_TROUBLESOME_GERD",
            label="Persistent troublesome GERD symptoms despite optimized PPI use may require diagnostic evaluation (endoscopy ± reflux monitoring).",
            display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 70},
        ))
        ctx.log(node_id, "PPI_INADEQUATE_AFTER_BID", {}, actions)
        return NodeResult(actions, next_node="Management_Response")

    nodes["Pharmacologic_Therapy"] = Node("Pharmacologic_Therapy", node_pharmacologic)

    # -----------------------------------------------------
    # Node 7 – Maintenance / Deprescribing
    # -----------------------------------------------------

    def node_maintenance(ctx: Context):
        node_id = "Maintenance_Or_Deprescribing"
        actions: List[Output] = []

        symptoms_resolved = ctx.get("symptoms_resolved_after_ppi")
        symptoms_return = ctx.get("symptoms_return_after_taper")

        if symptoms_resolved is None:
            actions.append(Action(
                code="CAPTURE_PPI_RESOLUTION_STATUS",
                label="Capture whether symptoms are controlled and whether tapering was attempted.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 75},
            ))
            ctx.log(node_id, "MISSING_RESOLUTION_STATUS", {}, actions)
            return NodeResult(actions, next_node="Management_Response")

        if bool(ctx.get("known_barretts_esophagus")):
            actions.append(Action(
                code="KNOWN_BARRETTS_LIFETIME_PPI",
                label="Known Barrett’s esophagus: lifetime daily PPI is recommended regardless of ongoing symptoms.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 76},
            ))
            ctx.log(node_id, "KNOWN_BARRETTS", {}, actions)
            return NodeResult(actions, next_node="Management_Response")

        if symptoms_resolved:
            actions.append(Action(
                code="TITRATE_TO_LOWEST_EFFECTIVE_PPI",
                label="If symptoms are controlled, titrate PPI to the lowest effective dose and attempt once yearly to taper or stop.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 77},
            ))

            if symptoms_return is True:
                actions.append(Action(
                    code="PPI_MAINTENANCE",
                    label="If symptoms return, use PPI maintenance at the lowest effective dose and consider annual deprescribing attempts.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 78},
                ))

        ctx.log(node_id, "MAINTENANCE_REVIEWED", {
            "symptoms_resolved_after_ppi": symptoms_resolved,
            "symptoms_return_after_taper": symptoms_return,
        }, actions)
        return NodeResult(actions, next_node="Management_Response")

    nodes["Maintenance_Or_Deprescribing"] = Node("Maintenance_Or_Deprescribing", node_maintenance)

    # -----------------------------------------------------
    # Node 8 – Management Response
    # -----------------------------------------------------

    def node_management_response(ctx: Context):
        node_id = "Management_Response"

        unsat = ctx.get("unsatisfactory_response_to_pharmacologic_therapy")
        if unsat is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["unsatisfactory_response_to_pharmacologic_therapy"],
                message="Need overall response to GERD pharmacologic therapy.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_MANAGEMENT_RESPONSE",
                        label="Document whether response to GERD pharmacologic therapy is unsatisfactory",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 80},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["unsatisfactory_response_to_pharmacologic_therapy"]}, [dr])
            return NodeResult([dr])

        unsat = ctx.apply_override(node_id, "unsatisfactory_response_to_pharmacologic_therapy", unsat)
        ctx.set("unsatisfactory_response_to_pharmacologic_therapy", unsat)

        if unsat:
            actions: List[Output] = [
                Action(
                    code="CONSIDER_ADVICE_SERVICE",
                    label="Consider using an advice service before referring.",
                    details={"supported_by": ["Unsatisfactory response to pharmacologic therapy"]},
                    override_options={
                        "node": node_id,
                        "field": "unsatisfactory_response_to_pharmacologic_therapy",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 81},
                )
            ]

            if ctx.get("advice_service_considered") is True:
                stop = Stop(
                    reason="Unsatisfactory response to GERD pharmacologic therapy – refer for consultation/endoscopy.",
                    actions=[
                        Action(
                            code="REFER_FAILED_GERD_MANAGEMENT",
                            label="Refer for consultation/endoscopy due to failed GERD management",
                            display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 82},
                        )
                    ],
                )
                ctx.log(node_id, "FAILED_MANAGEMENT_REFER", {"advice_service_considered": True}, actions + [stop])
                return NodeResult(actions + [stop])

            ctx.log(node_id, "FAILED_MANAGEMENT_ADVICE_FIRST", {"advice_service_considered": ctx.get("advice_service_considered")}, actions)
            return NodeResult(actions)

        stop = Stop(
            reason="GERD pathway complete – continue management in the Patient Medical Home.",
            actions=[
                Action(
                    code="CONTINUE_MEDICAL_HOME_CARE",
                    label="Continue management in the Patient Medical Home.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 83},
                )
            ],
        )
        ctx.log(node_id, "PATHWAY_COMPLETE", {}, [stop])
        return NodeResult([stop])

    nodes["Management_Response"] = Node("Management_Response", node_management_response)

    return PathwayEngine(
        nodes=nodes,
        start_node="Suspected_GERD"
    )


# =========================================================
# RUNNER
# =========================================================

def run_gerd_pathway(patient_data: Dict[str, Any], overrides=None):
    engine = gerd_build_engine()

    ctx = Context(
        data=dict(patient_data),
        overrides=overrides or []
    )

    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx.overrides