# -*- coding: utf-8 -*-
"""hcv_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kg991gmptmrc1EQF1BpiKgeUuN2M7Kda
"""

"""
========================================================
PATHWAY FILE: Hepatitis C Virus (HCV)
========================================================

Design goals
- Same architecture as other pathway engines
- Progressive gating with DataRequest where appropriate
- UI-friendly outputs: Action / DataRequest / Stop
- Audit log support
- Override capability
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# HCV PATHWAY IMPLEMENTATION
# =========================================================

def hcv_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # Helper functions
    # -----------------------------------------------------

    def _hcv_risk_info(ctx: Context) -> Dict[str, Any]:
        current_or_history_injection_drug_use = bool(ctx.get("current_or_history_injection_drug_use"))
        incarceration_history = bool(ctx.get("incarceration_history"))
        endemic_country_exposure = bool(ctx.get("endemic_country_exposure"))
        unsafe_healthcare_exposure = bool(ctx.get("unsafe_healthcare_exposure"))
        child_born_to_hcv_mother_over_18_months = bool(ctx.get("child_born_to_hcv_mother_over_18_months"))
        transfusion_or_transplant_pre_1992 = bool(ctx.get("transfusion_or_transplant_pre_1992"))
        needle_stick_history = bool(ctx.get("needle_stick_history"))
        persistently_elevated_alt = bool(ctx.get("persistently_elevated_alt"))
        hemodialysis = bool(ctx.get("hemodialysis"))
        patient_requests_screening = bool(ctx.get("patient_requests_screening"))
        other_hcv_risk_factors = bool(ctx.get("other_hcv_risk_factors"))

        risk_present = any([
            current_or_history_injection_drug_use,
            incarceration_history,
            endemic_country_exposure,
            unsafe_healthcare_exposure,
            child_born_to_hcv_mother_over_18_months,
            transfusion_or_transplant_pre_1992,
            needle_stick_history,
            persistently_elevated_alt,
            hemodialysis,
            patient_requests_screening,
            other_hcv_risk_factors,
        ])

        return {
            "risk_present": risk_present,
            "current_or_history_injection_drug_use": current_or_history_injection_drug_use,
            "incarceration_history": incarceration_history,
            "endemic_country_exposure": endemic_country_exposure,
            "unsafe_healthcare_exposure": unsafe_healthcare_exposure,
            "child_born_to_hcv_mother_over_18_months": child_born_to_hcv_mother_over_18_months,
            "transfusion_or_transplant_pre_1992": transfusion_or_transplant_pre_1992,
            "needle_stick_history": needle_stick_history,
            "persistently_elevated_alt": persistently_elevated_alt,
            "hemodialysis": hemodialysis,
            "patient_requests_screening": patient_requests_screening,
            "other_hcv_risk_factors": other_hcv_risk_factors,
        }

    def _compute_fib4(ctx: Context) -> Dict[str, Any]:
        age = ctx.get("age")
        ast = ctx.get("ast")
        alt = ctx.get("alt")
        platelets = ctx.get("platelets")

        missing = []
        if age is None:
            missing.append("age")
        if ast is None:
            missing.append("ast")
        if alt is None:
            missing.append("alt")
        if platelets is None:
            missing.append("platelets")

        if missing:
            return {"blocked": True, "missing": missing, "fib4": None}

        if alt <= 0 or platelets <= 0:
            return {"blocked": True, "missing": [], "fib4": None, "invalid_values": True}

        # FIB-4 = (Age × AST) / (Platelets × sqrt(ALT))
        fib4 = (age * ast) / (platelets * (alt ** 0.5))
        return {"blocked": False, "missing": [], "fib4": round(fib4, 3)}

    # -----------------------------------------------------
    # Node 1 – Who should be tested
    # -----------------------------------------------------

    def node_entry(ctx: Context):
        node_id = "Who_Should_Be_Tested"

        info = _hcv_risk_info(ctx)
        risk_present = info["risk_present"]
        risk_present = ctx.apply_override(node_id, "risk_present", risk_present)
        ctx.set("risk_present", risk_present)

        actions: List[Output] = []

        if risk_present:
            actions.append(Action(
                code="HCV_TESTING_INDICATED",
                label="HCV testing is indicated based on risk profile.",
                details=info,
                override_options={
                    "node": node_id,
                    "field": "risk_present",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
            ))
        else:
            actions.append(Action(
                code="HCV_TESTING_RISK_WARNING",
                label="No clear HCV testing risk factor documented; consider screening only if clinically appropriate.",
                details=info,
                override_options={
                    "node": node_id,
                    "field": "risk_present",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 10},
            ))

        ctx.log(node_id, "ENTRY_ASSESSED", info, actions)
        return NodeResult(actions, next_node="Harm_Reduction")

    nodes["Who_Should_Be_Tested"] = Node("Who_Should_Be_Tested", node_entry)

    # -----------------------------------------------------
    # Node 2 – Harm reduction
    # -----------------------------------------------------

    def node_harm_reduction(ctx: Context):
        node_id = "Harm_Reduction"

        out = [
            Action(
                code="CONNECT_HARM_REDUCTION",
                label="Connect patient to harm reduction support programs, as appropriate.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20},
            )
        ]

        ctx.log(node_id, "HARM_REDUCTION_EMITTED", {}, out)
        return NodeResult(out, next_node="Testing_And_Blood_Work")

    nodes["Harm_Reduction"] = Node("Harm_Reduction", node_harm_reduction)

    # -----------------------------------------------------
    # Node 3 – Testing and blood work
    # -----------------------------------------------------

    def node_testing(ctx: Context):
        node_id = "Testing_And_Blood_Work"

        actions: List[Output] = []

        exposure_months_ago = ctx.get("months_since_exposure")
        if exposure_months_ago is not None and exposure_months_ago < 3:
            actions.append(Action(
                code="TESTING_WINDOW_WARNING",
                label="Testing is ideally performed at least 3 months after exposure; consider repeat testing if done earlier.",
                details={"months_since_exposure": exposure_months_ago},
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 30},
            ))

        prior_hcv_infection = ctx.get("prior_hcv_infection")
        hcv_antibody_result = ctx.get("hcv_antibody_result")
        hcv_rna_result = ctx.get("hcv_rna_result")

        missing = []
        if prior_hcv_infection is None:
            missing.append("prior_hcv_infection")
        if hcv_antibody_result is None:
            missing.append("hcv_antibody_result")
        if hcv_rna_result is None:
            missing.append("hcv_rna_result")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need HCV testing history plus antibody and RNA results to interpret status.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_HCV_TESTING_RESULTS",
                        label="Capture prior HCV history, antibody result, and RNA result",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 31},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, actions + [dr])
            return NodeResult(actions + [dr])

        # Interpret results
        if hcv_antibody_result == "negative":
            stop = Stop(
                reason="HCV antibody negative.",
                actions=actions + [
                    Action(
                        code="HCV_ANTIBODY_NEGATIVE",
                        label="HCV antibody negative; if ongoing risk, maintain harm reduction supports and retest annually.",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 32},
                    )
                ],
            )
            ctx.log(node_id, "ANTIBODY_NEGATIVE", {
                "prior_hcv_infection": prior_hcv_infection,
                "hcv_antibody_result": hcv_antibody_result,
                "hcv_rna_result": hcv_rna_result,
            }, [stop])
            return NodeResult([stop])

        if hcv_antibody_result == "positive" and hcv_rna_result == "negative":
            out = actions + [
                Action(
                    code="HCV_CLEARED",
                    label="HCV antibody positive / RNA negative: infection has cleared.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 33},
                ),
                Action(
                    code="COMPLETE_ADDITIONAL_BLOODWORK",
                    label="Complete blood work to assess co-morbidities and liver health (Hep A, Hep B, HIV, AST, ALT, platelets, creatinine).",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 34},
                ),
            ]
            ctx.log(node_id, "ANTIBODY_POSITIVE_RNA_NEGATIVE", {
                "prior_hcv_infection": prior_hcv_infection,
                "hcv_antibody_result": hcv_antibody_result,
                "hcv_rna_result": hcv_rna_result,
            }, out)
            return NodeResult(out, next_node="Treatment_Appropriate_At_This_Time")

        out = actions + [
            Action(
                code="HCV_VIREMIC",
                label="HCV antibody positive / RNA positive: active HCV infection present.",
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 35},
            ),
            Action(
                code="COMPLETE_TREATMENT_BLOODWORK",
                label="Complete blood work to inform treatment plan (Hep A, Hep B, HIV, AST, ALT, platelets, creatinine).",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 36},
            ),
        ]
        ctx.log(node_id, "ANTIBODY_POSITIVE_RNA_POSITIVE", {
            "prior_hcv_infection": prior_hcv_infection,
            "hcv_antibody_result": hcv_antibody_result,
            "hcv_rna_result": hcv_rna_result,
        }, out)
        return NodeResult(out, next_node="Treatment_Appropriate_At_This_Time")

    nodes["Testing_And_Blood_Work"] = Node("Testing_And_Blood_Work", node_testing)

    # -----------------------------------------------------
    # Node 4 – Is treatment appropriate at this time?
    # -----------------------------------------------------

    def node_treatment_now(ctx: Context):
        node_id = "Treatment_Appropriate_At_This_Time"

        actions: List[Output] = [
            Action(
                code="ASSESS_ADHERENCE_SUPPORTS",
                label="Discuss what supports are required for adherence to treatment and link patient to these supports.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
            )
        ]

        treatment_postponed = False

        if bool(ctx.get("pregnant")) or bool(ctx.get("lactating")) or bool(ctx.get("at_risk_of_pregnancy")):
            treatment_postponed = True
            actions.append(Action(
                code="POSTPONE_TREATMENT_PREGNANCY",
                label="Postpone treatment if pregnant, lactating, or at risk of pregnancy.",
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 41},
            ))

        if bool(ctx.get("adherence_readiness_low")):
            treatment_postponed = True
            actions.append(Action(
                code="POSTPONE_TREATMENT_ADHERENCE",
                label="If adherence readiness is low, maintain supports and monitor until treatment is more appropriate.",
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 42},
            ))

        ctx.set("treatment_postponed", treatment_postponed)

        if treatment_postponed:
            stop = Stop(
                reason="Treatment is being postponed at this time.",
                actions=actions,
            )
            ctx.log(node_id, "TREATMENT_POSTPONED", {
                "pregnant": ctx.get("pregnant"),
                "lactating": ctx.get("lactating"),
                "at_risk_of_pregnancy": ctx.get("at_risk_of_pregnancy"),
                "adherence_readiness_low": ctx.get("adherence_readiness_low"),
            }, [stop])
            return NodeResult([stop])

        ctx.log(node_id, "TREATMENT_APPROPRIATE_NOW", {
            "pregnant": ctx.get("pregnant"),
            "lactating": ctx.get("lactating"),
            "at_risk_of_pregnancy": ctx.get("at_risk_of_pregnancy"),
            "adherence_readiness_low": ctx.get("adherence_readiness_low"),
        }, actions)
        return NodeResult(actions, next_node="Determine_Appropriateness_In_Medical_Home")

    nodes["Treatment_Appropriate_At_This_Time"] = Node("Treatment_Appropriate_At_This_Time", node_treatment_now)

    # -----------------------------------------------------
    # Node 5 – Determine appropriateness in Patient Medical Home
    # -----------------------------------------------------

    def node_medical_home(ctx: Context):
        node_id = "Determine_Appropriateness_In_Medical_Home"

        if bool(ctx.get("decompensated_cirrhosis")):
            stop = Stop(
                reason="Do not treat patients with decompensated cirrhosis in primary care.",
                urgency="urgent",
                actions=[
                    Action(
                        code="URGENT_HEPATOLOGY_REFERRAL",
                        label="Urgent referral to hepatology for decompensated cirrhosis.",
                        urgency="urgent",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 50},
                    )
                ],
            )
            ctx.log(node_id, "DECOMPENSATED_CIRRHOSIS_STOP", {"decompensated_cirrhosis": True}, [stop])
            return NodeResult([stop])

        actions: List[Output] = []

        must_refer = any([
            bool(ctx.get("prior_hcv_treatment")),
            bool(ctx.get("hbv_coinfection")),
            bool(ctx.get("hiv_coinfection")),
            (ctx.get("egfr") is not None and ctx.get("egfr") < 30),
            bool(ctx.get("pediatric_hcv")),
        ])
        must_refer = ctx.apply_override(node_id, "must_refer", must_refer)
        ctx.set("must_refer", must_refer)

        if must_refer:
            actions.append(Action(
                code="ALWAYS_REFER_SPECIALIST",
                label="This patient meets criteria for specialist referral.",
                details={
                    "prior_hcv_treatment": bool(ctx.get("prior_hcv_treatment")),
                    "hbv_coinfection": bool(ctx.get("hbv_coinfection")),
                    "hiv_coinfection": bool(ctx.get("hiv_coinfection")),
                    "egfr": ctx.get("egfr"),
                    "pediatric_hcv": bool(ctx.get("pediatric_hcv")),
                },
                override_options={
                    "node": node_id,
                    "field": "must_refer",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 51},
            ))

        if bool(ctx.get("provider_not_comfortable_treating")):
            actions.append(Action(
                code="REFER_PROVIDER_COMFORT",
                label="Refer because the primary care provider is not comfortable initiating treatment.",
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 52},
            ))

        if bool(ctx.get("insurance_requires_referral")):
            actions.append(Action(
                code="REFER_INSURANCE_REQUIREMENT",
                label="Refer if required by the patient’s insurance provider.",
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 53},
            ))

        ctx.log(node_id, "MEDICAL_HOME_APPROPRIATENESS_ASSESSED", {
            "must_refer": must_refer,
            "provider_not_comfortable_treating": bool(ctx.get("provider_not_comfortable_treating")),
            "insurance_requires_referral": bool(ctx.get("insurance_requires_referral")),
        }, actions)
        return NodeResult(actions, next_node="Calculate_FIB4")

    nodes["Determine_Appropriateness_In_Medical_Home"] = Node("Determine_Appropriateness_In_Medical_Home", node_medical_home)

    # -----------------------------------------------------
    # Node 6 – Calculate FIB-4
    # -----------------------------------------------------

    def node_fib4(ctx: Context):
        node_id = "Calculate_FIB4"

        result = _compute_fib4(ctx)
        if result["blocked"]:
            if result.get("invalid_values"):
                stop = Stop(
                    reason="Invalid lab values supplied for FIB-4 calculation.",
                    actions=[
                        Action(
                            code="INVALID_FIB4_INPUTS",
                            label="AST, ALT, and platelets must be positive values for FIB-4 calculation.",
                            display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 60},
                        )
                    ],
                )
                ctx.log(node_id, "INVALID_VALUES", {}, [stop])
                return NodeResult([stop])

            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=result["missing"],
                message="Need age, AST, ALT, and platelets to calculate FIB-4.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_FIB4_INPUTS",
                        label="Capture age, AST, ALT, and platelets",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 61},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": result["missing"]}, [dr])
            return NodeResult([dr])

        fib4 = result["fib4"]
        ctx.set("fib4", fib4)

        actions: List[Output] = [
            Action(
                code="FIB4_CALCULATED",
                label=f"FIB-4 calculated: {fib4}",
                details={"fib4": fib4},
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 62},
            )
        ]

        if fib4 > 3.25:
            stop = Stop(
                reason="FIB-4 > 3.25 indicates need for specialist assessment.",
                actions=actions + [
                    Action(
                        code="REFER_HIGH_FIB4",
                        label="Refer to specialist for further assessment of liver damage.",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 63},
                    )
                ],
            )
            ctx.log(node_id, "FIB4_HIGH", {"fib4": fib4}, [stop])
            return NodeResult([stop])

        ctx.log(node_id, "FIB4_LOW", {"fib4": fib4}, actions)
        return NodeResult(actions, next_node="Seek_Specialist_Advice")

    nodes["Calculate_FIB4"] = Node("Calculate_FIB4", node_fib4)

    # -----------------------------------------------------
    # Node 7 – Seek specialist advice
    # -----------------------------------------------------

    def node_advice(ctx: Context):
        node_id = "Seek_Specialist_Advice"

        out = [
            Action(
                code="SEEK_SPECIALIST_ADVICE",
                label="Seek advice from hepatology, infectious disease, or gastroenterology specialist if required by insurance or needed clinically.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 70},
            )
        ]

        ctx.log(node_id, "ADVICE_EMITTED", {}, out)
        return NodeResult(out, next_node="Offer_Therapy")

    nodes["Seek_Specialist_Advice"] = Node("Seek_Specialist_Advice", node_advice)

    # -----------------------------------------------------
    # Node 8 – Offer therapy
    # -----------------------------------------------------

    def node_offer_therapy(ctx: Context):
        node_id = "Offer_Therapy"

        out = [
            Action(
                code="OFFER_PANGENOTYPIC_THERAPY",
                label="Offer pan-genotypic HCV therapy (Epclusa or Maviret, 8–12 weeks).",
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 80},
            ),
            Action(
                code="ASSESS_DRUG_INTERACTIONS",
                label="Assess drug-drug interactions before selecting regimen.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 81},
            ),
            Action(
                code="FACILITATE_INSURANCE_COVERAGE",
                label="Facilitate insurance coverage and assess/address barriers to adherence.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 82},
            ),
        ]

        ctx.log(node_id, "THERAPY_EMITTED", {}, out)
        return NodeResult(out, next_node="Confirm_Cure")

    nodes["Offer_Therapy"] = Node("Offer_Therapy", node_offer_therapy)

    # -----------------------------------------------------
    # Node 9 – Confirm cure
    # -----------------------------------------------------

    def node_confirm_cure(ctx: Context):
        node_id = "Confirm_Cure"

        hcv_rna_12_weeks_post_treatment = ctx.get("hcv_rna_12_weeks_post_treatment")
        ast_post_treatment = ctx.get("ast_post_treatment")
        alt_post_treatment = ctx.get("alt_post_treatment")

        if hcv_rna_12_weeks_post_treatment is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["hcv_rna_12_weeks_post_treatment"],
                message="Need HCV RNA result 12 weeks after completion of therapy to confirm cure.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_SVR12_RESULT",
                        label="Capture 12-week post-treatment HCV RNA result",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 90},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["hcv_rna_12_weeks_post_treatment"]}, [dr])
            return NodeResult([dr])

        actions: List[Output] = [
            Action(
                code="RECHECK_AST_ALT",
                label="Re-test AST and ALT at 12 weeks post-treatment; if not normalized, investigate other causes.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 91},
            )
        ]

        if hcv_rna_12_weeks_post_treatment == "positive":
            stop = Stop(
                reason="HCV not cured after treatment.",
                actions=actions + [
                    Action(
                        code="REFER_TREATMENT_FAILURE",
                        label="Refer to specialist because treatment failed to clear the virus.",
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 92},
                    )
                ],
            )
            ctx.log(node_id, "NOT_CURED", {"hcv_rna_12_weeks_post_treatment": hcv_rna_12_weeks_post_treatment}, [stop])
            return NodeResult([stop])

        if ast_post_treatment is not None and alt_post_treatment is not None:
            if ast_post_treatment > ctx.get("ast_upper_limit_normal", 40) or alt_post_treatment > ctx.get("alt_upper_limit_normal", 40):
                actions.append(Action(
                    code="INVESTIGATE_PERSISTENT_LIVER_ENZYME_ELEVATION",
                    label="AST/ALT not normalized; investigate other causes of elevated liver enzymes.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 93},
                ))

        ctx.log(node_id, "CURED", {"hcv_rna_12_weeks_post_treatment": hcv_rna_12_weeks_post_treatment}, actions)
        return NodeResult(actions, next_node="Long_Term_Followup")

    nodes["Confirm_Cure"] = Node("Confirm_Cure", node_confirm_cure)

    # -----------------------------------------------------
    # Node 10 – Long-term follow-up
    # -----------------------------------------------------

    def node_followup(ctx: Context):
        node_id = "Long_Term_Followup"

        at_risk_reinfection = bool(ctx.get("at_risk_reinfection"))
        actions: List[Output] = []

        if at_risk_reinfection:
            actions.append(Action(
                code="MAINTAIN_HARM_REDUCTION_AND_RETEST",
                label="Maintain harm reduction supports and retest annually if at risk of infection/reinfection.",
                details={"supported_by": ["Patient is at ongoing risk of infection/reinfection"]},
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 100},
            ))

        stop = Stop(
            reason="HCV pathway complete.",
            actions=actions + [
                Action(
                    code="CONTINUE_HCV_FOLLOWUP",
                    label="Continue HCV follow-up in the Patient Medical Home or specialist care as indicated.",
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 101},
                )
            ],
        )
        ctx.log(node_id, "PATHWAY_COMPLETE", {"at_risk_reinfection": at_risk_reinfection}, [stop])
        return NodeResult([stop])

    nodes["Long_Term_Followup"] = Node("Long_Term_Followup", node_followup)

    return PathwayEngine(
        nodes=nodes,
        start_node="Who_Should_Be_Tested"
    )


# =========================================================
# RUNNER
# =========================================================

def run_hcv_pathway(patient_data: Dict[str, Any], overrides=None):
    engine = hcv_build_engine()

    ctx = Context(
        data=dict(patient_data),
        overrides=overrides or []
    )

    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx.overrides