# -*- coding: utf-8 -*-
"""hrrb_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBHwe-pHYp0ZA8uGNfbDm0Hs78OI5ZjO
"""

"""
========================================================
PATHWAY FILE: High Risk Rectal Bleeding → CRC Referral
========================================================

Design goals:
- Separate pathway engine, callable standalone or from IDA
- Progressive decision gating: run as far as possible with partial data
- Only stop when a decision node cannot proceed without critical info
- UI-ready outputs: Action / DataRequest / Stop
- Full audit log for every node
- Clinician overrides supported at specific nodes/fields
- Display metadata for cleaner reports

USER-SPECIFIC DECISIONS APPLIED:
1. "New or worsening anemia" means:
   - Hb is below threshold for sex
   - OR Hb is below prior known baseline when patient previously had anemia
2. Scenario C requires:
   - NOT Scenario A
   - NOT Scenario B
   - HRRB present
   - at least one semi-urgent feature
3. "Unexplained" uses COMPLETE colonoscopy within last 2 years (strict)
4. If DRE cannot be completed due to pain, semi-urgent referral can still proceed
5. Family history supports output but does not change urgency by itself
6. FIT is a warning, not a blocker
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================
# Output types
# =========================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)

@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)

@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None

Output = Action | DataRequest | Stop


# =========================
# Audit trail + overrides
# =========================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================
# Context
# =========================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key: str, default=None):
        return self.data.get(key, default)

    def set(self, key: str, value: Any):
        self.data[key] = value

    def apply_override(self, node: str, field: str, current_value: Any) -> Any:
        candidates = [o for o in self.overrides if o.target_node == node and o.field == field]
        if not candidates:
            return current_value
        newest = max(candidates, key=lambda o: o.created_at)
        return newest.new_value

    def log(self, node: str, decision: str, used_inputs: Dict[str, Any], outputs: List[Output]):
        def ser_action(a: Action) -> Dict[str, Any]:
            return {
                "type": "action",
                "code": a.code,
                "label": a.label,
                "urgency": a.urgency,
                "details": a.details,
                "override_options": a.override_options,
                "display": a.display,
            }

        def ser(o: Output) -> Dict[str, Any]:
            if isinstance(o, Action):
                return ser_action(o)
            if isinstance(o, DataRequest):
                return {
                    "type": "data_request",
                    "blocking_node": o.blocking_node,
                    "missing_fields": o.missing_fields,
                    "message": o.message,
                    "urgency_context": o.urgency_context,
                    "suggested_actions": [ser_action(a) for a in o.suggested_actions],
                }
            if isinstance(o, Stop):
                return {
                    "type": "stop",
                    "reason": o.reason,
                    "urgency": o.urgency,
                    "actions": [ser_action(a) for a in o.actions],
                }
            return {"type": "unknown"}

        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=used_inputs,
                outputs=[ser(x) for x in outputs],
            )
        )


# =========================
# Engine
# =========================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None

NodeFn = Callable[[Context], NodeResult]

@dataclass
class Node:
    node_id: str
    fn: NodeFn

class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current is not None:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break
            if current not in self.nodes:
                outputs.append(Stop(reason=f"Engine error: unknown node '{current}'"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (DataRequest, Stop)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# ==========================================================
# HRRB IMPLEMENTATION
# ==========================================================

def hrrb_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -------------------------
    # Helpers
    # -------------------------

    def _freshness_flag(days_ago: Optional[int], within_flag: Optional[bool]) -> Optional[bool]:
        if within_flag is not None:
            return within_flag
        if days_ago is None:
            return None
        return days_ago <= 56

    def _ferritin_cutoff(ctx: Context) -> Optional[float]:
        sex = ctx.get("sex")
        if sex == "male":
            return 30.0
        if sex == "female":
            return 20.0
        return None

    def _iron_deficiency(ctx: Context) -> Dict[str, Any]:
        sex = ctx.get("sex")
        ferritin = ctx.get("ferritin")

        missing = []
        if sex is None:
            missing.append("sex")
        if ferritin is None:
            missing.append("ferritin")

        if missing:
            return {"blocked": True, "missing": missing, "iron_deficient": None, "cutoff": None}

        cutoff = _ferritin_cutoff(ctx)
        iron_deficient = ferritin < cutoff
        return {"blocked": False, "missing": [], "iron_deficient": iron_deficient, "cutoff": cutoff}

    def _anemia_thresholds(sex: Optional[str]) -> Dict[str, Optional[float]]:
        if sex == "male":
            return {"general": 130.0, "urgent": 110.0}
        if sex == "female":
            return {"general": 120.0, "urgent": 100.0}
        return {"general": None, "urgent": None}

    def _new_or_worsening_anemia(ctx: Context) -> Dict[str, Any]:
        """
        User rule:
        alarm if:
        - Hb below general anemia threshold for sex
        OR
        - Hb below prior baseline when they previously had anemia
        """
        sex = ctx.get("sex")
        hb = ctx.get("hemoglobin")
        baseline_hb = ctx.get("baseline_hemoglobin")
        prior_anemia_documented = ctx.get("prior_anemia_documented")

        missing = []
        if sex is None:
            missing.append("sex")
        if hb is None:
            missing.append("hemoglobin")

        if missing:
            return {"blocked": True, "missing": missing, "new_or_worsening_anemia": None}

        thresholds = _anemia_thresholds(sex)
        general_threshold = thresholds["general"]

        low_hb = hb < general_threshold
        worse_than_baseline = False

        if baseline_hb is not None and prior_anemia_documented is True:
            worse_than_baseline = hb < baseline_hb

        result = bool(low_hb or worse_than_baseline)
        return {
            "blocked": False,
            "missing": [],
            "new_or_worsening_anemia": result,
            "low_hb": low_hb,
            "worse_than_baseline": worse_than_baseline,
            "general_threshold": general_threshold,
            "baseline_hemoglobin": baseline_hb,
        }

    def _urgent_anemia_plus_iron_deficiency(ctx: Context) -> Dict[str, Any]:
        sex = ctx.get("sex")
        hb = ctx.get("hemoglobin")

        missing = []
        if sex is None:
            missing.append("sex")
        if hb is None:
            missing.append("hemoglobin")

        iron = _iron_deficiency(ctx)
        if iron["blocked"]:
            missing.extend(iron["missing"])

        if missing:
            return {
                "blocked": True,
                "missing": sorted(set(missing)),
                "urgent_anemia_plus_iron_deficiency": None,
            }

        urgent_threshold = _anemia_thresholds(sex)["urgent"]
        urgent_anemia = hb < urgent_threshold
        result = bool(urgent_anemia and iron["iron_deficient"])

        return {
            "blocked": False,
            "missing": [],
            "urgent_anemia_plus_iron_deficiency": result,
            "urgent_anemia": urgent_anemia,
            "urgent_threshold": urgent_threshold,
            "iron_deficient": iron["iron_deficient"],
            "ferritin_cutoff": iron["cutoff"],
        }

    def _scenario_c_features(ctx: Context) -> Dict[str, Any]:
        anemia = _new_or_worsening_anemia(ctx)
        iron = _iron_deficiency(ctx)

        abdominal_pain = bool(ctx.get("abdominal_pain_new_persistent_or_worsening"))
        weight_loss = ctx.get("weight_loss_percent_6_months")
        bowel_change = bool(ctx.get("concerning_change_in_bowel_habit"))

        weight_loss_flag = False
        if weight_loss is not None:
            weight_loss_flag = weight_loss >= 5.0

        return {
            "new_or_worsening_anemia": anemia["new_or_worsening_anemia"] if not anemia["blocked"] else None,
            "iron_deficiency": iron["iron_deficient"] if not iron["blocked"] else None,
            "abdominal_pain": abdominal_pain,
            "weight_loss_flag": weight_loss_flag,
            "concerning_change_in_bowel_habit": bowel_change,
            "any_feature": bool(
                (anemia["new_or_worsening_anemia"] if not anemia["blocked"] else False)
                or (iron["iron_deficient"] if not iron["blocked"] else False)
                or abdominal_pain
                or weight_loss_flag
                or bowel_change
            ),
            "weight_loss_percent_6_months": weight_loss,
        }

    # -------------------------
    # Nodes
    # -------------------------

    def node_confirm_hrrb(ctx: Context) -> NodeResult:
        node_id = "Confirm_HRRB"

        visible = ctx.get("rectal_bleeding_visible")
        not_just_tissue = ctx.get("rectal_bleeding_not_just_tissue")
        new_or_worsening = ctx.get("rectal_bleeding_new_or_worsening")
        persistent = ctx.get("rectal_bleeding_persistent")
        most_days = ctx.get("rectal_bleeding_most_days_per_week")
        duration_weeks = ctx.get("rectal_bleeding_duration_weeks")
        complete_colonoscopy_within_2y = ctx.get("complete_colonoscopy_within_2y")

        missing = []
        for key, value in {
            "rectal_bleeding_visible": visible,
            "rectal_bleeding_not_just_tissue": not_just_tissue,
            "rectal_bleeding_new_or_worsening": new_or_worsening,
            "rectal_bleeding_persistent": persistent,
            "rectal_bleeding_most_days_per_week": most_days,
            "rectal_bleeding_duration_weeks": duration_weeks,
            "complete_colonoscopy_within_2y": complete_colonoscopy_within_2y,
        }.items():
            if value is None:
                missing.append(key)

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message=(
                    "Need full rectal bleeding history to determine whether high-risk rectal bleeding criteria are met."
                ),
                suggested_actions=[
                    Action(
                        code="CAPTURE_HRRB_CORE",
                        label="Capture visible bleeding, persistence, duration, and complete colonoscopy history",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult(outputs=[dr])

        visible_blood = bool(visible and not_just_tissue)
        persistent_pattern = bool(new_or_worsening and persistent and most_days and duration_weeks > 2)
        unexplained = (complete_colonoscopy_within_2y is False)

        hrrb_confirmed = bool(visible_blood and persistent_pattern and unexplained)
        hrrb_confirmed = ctx.apply_override(node_id, "hrrb_confirmed", hrrb_confirmed)
        ctx.set("hrrb_confirmed", hrrb_confirmed)

        if not hrrb_confirmed:
            stop = Stop(
                reason="High-risk rectal bleeding criteria are not met; this pathway does not apply.",
                actions=[
                    Action(
                        code="LOW_RISK_OR_REEVALUATE",
                        label="Monitor and re-evaluate; low-risk rectal bleeding pathway is under development",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 99},
                    )
                ],
            )
            ctx.log(
                node_id,
                "HRRB_NOT_CONFIRMED",
                {
                    "visible_blood": visible_blood,
                    "persistent_pattern": persistent_pattern,
                    "unexplained": unexplained,
                },
                [stop],
            )
            return NodeResult(outputs=[stop])

        out = [
            Action(
                code="HRRB_CONFIRMED",
                label="High-risk rectal bleeding criteria confirmed.",
                details={
                    "supported_by": [
                        "Visible blood present in/on stool or toilet and not just on tissue",
                        "Bleeding is new/worsening and persistent most days for >2 weeks",
                        "No complete colonoscopy within the last 2 years",
                    ],
                    "visible_blood": visible_blood,
                    "persistent_pattern": persistent_pattern,
                    "unexplained": unexplained,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
            )
        ]
        ctx.log(node_id, "HRRB_CONFIRMED", {"hrrb_confirmed": True}, out)
        return NodeResult(outputs=out, next_node="Medical_History")

    def node_history(ctx: Context) -> NodeResult:
        node_id = "Medical_History"

        actions: List[Action] = []

        if ctx.get("personal_history_crc") is True:
            actions.append(Action(
                code="HISTORY_CRC_PERSONAL",
                label="Personal history of colorectal cancer documented.",
                display={"role": "modifier", "group_under": "ASSIGN_URGENCY_HRRB", "show_as_standalone": False, "sort_priority": 60},
            ))
        elif ctx.get("personal_history_crc") is None:
            actions.append(Action(
                code="CAPTURE_PERSONAL_HISTORY_CRC",
                label="Document personal history of colorectal cancer.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 65},
            ))

        if ctx.get("family_history_crc_first_degree") is True:
            actions.append(Action(
                code="HISTORY_CRC_FAMILY",
                label="First-degree family history of colorectal cancer documented.",
                display={"role": "modifier", "group_under": "ASSIGN_URGENCY_HRRB", "show_as_standalone": False, "sort_priority": 60},
            ))
        elif ctx.get("family_history_crc_first_degree") is None:
            actions.append(Action(
                code="CAPTURE_FAMILY_HISTORY_CRC",
                label="Document first-degree family history of colorectal cancer.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 65},
            ))

        if ctx.get("personal_history_ibd") is True:
            actions.append(Action(
                code="HISTORY_IBD_PERSONAL",
                label="Personal history of inflammatory bowel disease documented.",
                display={"role": "modifier", "group_under": "ASSIGN_URGENCY_HRRB", "show_as_standalone": False, "sort_priority": 60},
            ))
        elif ctx.get("personal_history_ibd") is None:
            actions.append(Action(
                code="CAPTURE_PERSONAL_HISTORY_IBD",
                label="Document personal history of inflammatory bowel disease.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 65},
            ))

        if ctx.get("family_history_ibd_first_degree") is True:
            actions.append(Action(
                code="HISTORY_IBD_FAMILY",
                label="First-degree family history of inflammatory bowel disease documented.",
                display={"role": "modifier", "group_under": "ASSIGN_URGENCY_HRRB", "show_as_standalone": False, "sort_priority": 60},
            ))
        elif ctx.get("family_history_ibd_first_degree") is None:
            actions.append(Action(
                code="CAPTURE_FAMILY_HISTORY_IBD",
                label="Document first-degree family history of inflammatory bowel disease.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 65},
            ))

        if ctx.get("most_recent_lower_endoscopy_result") is None:
            actions.append(Action(
                code="CAPTURE_MOST_RECENT_ENDOSCOPY_RESULT",
                label="Document results of most recent lower endoscopy.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 65},
            ))

        ctx.log(node_id, "HISTORY_CAPTURED", {}, actions)
        return NodeResult(outputs=actions, next_node="Physical_Exam")

    def node_physical_exam(ctx: Context) -> NodeResult:
        node_id = "Physical_Exam"

        dre_done = ctx.get("dre_done")
        dre_not_possible_due_to_pain = ctx.get("dre_not_possible_due_to_pain")

        actions: List[Output] = []

        if dre_done is None and dre_not_possible_due_to_pain is None:
            actions.append(
                DataRequest(
                    blocking_node=node_id,
                    missing_fields=["dre_done", "dre_not_possible_due_to_pain"],
                    message="Digital rectal exam is strongly recommended; document findings or if not possible due to pain.",
                    suggested_actions=[
                        Action(
                            code="CAPTURE_DRE_STATUS",
                            label="Document DRE findings or reason not completed",
                            display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 25},
                        )
                    ],
                )
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["dre_done", "dre_not_possible_due_to_pain"]}, actions)
            return NodeResult(outputs=actions)

        if dre_not_possible_due_to_pain is True:
            actions.append(
                Action(
                    code="DRE_NOT_COMPLETED_DUE_TO_PAIN",
                    label="DRE could not be completed due to pain; semi-urgent referral can still proceed.",
                    details={"supported_by": ["Pathway allows semi-urgent referral even if DRE could not be completed due to pain"]},
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 26},
                )
            )

        ctx.log(node_id, "PHYSICAL_EXAM_RECORDED", {"dre_done": dre_done, "dre_not_possible_due_to_pain": dre_not_possible_due_to_pain}, actions)
        return NodeResult(outputs=actions, next_node="Baseline_Investigations")

    def node_baseline_investigations(ctx: Context) -> NodeResult:
        node_id = "Baseline_Investigations"

        actions: List[Action] = []

        cbc_fresh = _freshness_flag(ctx.get("cbc_days_ago"), ctx.get("cbc_within_8_weeks"))
        creatinine_fresh = _freshness_flag(ctx.get("creatinine_days_ago"), ctx.get("creatinine_within_8_weeks"))
        serum_iron_fresh = _freshness_flag(ctx.get("serum_iron_days_ago"), ctx.get("serum_iron_within_8_weeks"))
        tibc_fresh = _freshness_flag(ctx.get("tibc_days_ago"), ctx.get("tibc_within_8_weeks"))
        ferritin_fresh = _freshness_flag(ctx.get("ferritin_days_ago"), ctx.get("ferritin_within_8_weeks"))

        if cbc_fresh is False:
            actions.append(Action(code="UPDATE_CBC", label="CBC is older than 8 weeks: repeat/update before referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))
        elif cbc_fresh is None:
            actions.append(Action(code="CHECK_CBC_DATE", label="Confirm CBC is within 8 weeks of referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))

        if creatinine_fresh is False:
            actions.append(Action(code="UPDATE_CREATININE", label="Creatinine is older than 8 weeks: repeat/update before referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))
        elif creatinine_fresh is None:
            actions.append(Action(code="CHECK_CREATININE_DATE", label="Confirm creatinine is within 8 weeks of referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))

        if serum_iron_fresh is False:
            actions.append(Action(code="UPDATE_SERUM_IRON", label="Serum iron is older than 8 weeks: repeat/update before referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))
        elif serum_iron_fresh is None:
            actions.append(Action(code="CHECK_SERUM_IRON_DATE", label="Confirm serum iron is within 8 weeks of referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))

        if tibc_fresh is False:
            actions.append(Action(code="UPDATE_TIBC", label="TIBC is older than 8 weeks: repeat/update before referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))
        elif tibc_fresh is None:
            actions.append(Action(code="CHECK_TIBC_DATE", label="Confirm TIBC is within 8 weeks of referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))

        if ferritin_fresh is False:
            actions.append(Action(code="UPDATE_FERRITIN", label="Ferritin is older than 8 weeks: repeat/update before referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))
        elif ferritin_fresh is None:
            actions.append(Action(code="CHECK_FERRITIN_DATE", label="Confirm ferritin is within 8 weeks of referral.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))

        if ctx.get("abdominal_pain_new_persistent_or_worsening") is True:
            actions.append(Action(
                code="CONSIDER_ABDOMINAL_ULTRASOUND",
                label="Consider abdominal ultrasound because abdominal pain is reported.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 46},
            ))

        if ctx.get("fit_ordered_or_planned") is True:
            actions.append(Action(
                code="DO_NOT_ORDER_FIT_HRRB",
                label="Do NOT order FIT for patients meeting high-risk rectal bleeding criteria.",
                details={"supported_by": ["Pathway states FIT should not be done in HRRB patients"]},
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 50},
            ))

        ctx.log(
            node_id,
            "BASELINE_INVESTIGATIONS_REVIEWED",
            {
                "cbc_fresh": cbc_fresh,
                "creatinine_fresh": creatinine_fresh,
                "serum_iron_fresh": serum_iron_fresh,
                "tibc_fresh": tibc_fresh,
                "ferritin_fresh": ferritin_fresh,
            },
            actions,
        )
        return NodeResult(outputs=actions, next_node="Alarm_Features")

    def node_alarm_features(ctx: Context) -> NodeResult:
        node_id = "Alarm_Features"

        # Scenario A
        palpable_abdominal_mass = bool(ctx.get("palpable_abdominal_mass"))
        palpable_rectal_mass = bool(ctx.get("palpable_rectal_mass"))
        suspected_colorectal_lesion_on_imaging = bool(ctx.get("suspected_colorectal_lesion_on_imaging"))
        evidence_of_metastases_on_imaging = bool(ctx.get("evidence_of_metastases_on_imaging"))

        scenario_a = bool(
            palpable_abdominal_mass
            or palpable_rectal_mass
            or suspected_colorectal_lesion_on_imaging
            or evidence_of_metastases_on_imaging
        )
        scenario_a = ctx.apply_override(node_id, "scenario_a", scenario_a)

        # Scenario B
        scenario_b_eval = _urgent_anemia_plus_iron_deficiency(ctx)
        if scenario_b_eval["blocked"]:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=scenario_b_eval["missing"],
                message="Need sex, hemoglobin, and ferritin to determine whether urgent anemia + iron deficiency scenario is present.",
                suggested_actions=[
                    Action(code="CAPTURE_HB_FERRITIN_FOR_HRRB", label="Capture sex, hemoglobin, and ferritin", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 55})
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA_SCENARIO_B", {"missing": scenario_b_eval["missing"]}, [dr])
            return NodeResult(outputs=[dr])

        scenario_b = scenario_b_eval["urgent_anemia_plus_iron_deficiency"]
        scenario_b = ctx.apply_override(node_id, "scenario_b", scenario_b)

        # Scenario C
        scenario_c_features = _scenario_c_features(ctx)
        scenario_c = bool((not scenario_a) and (not scenario_b) and scenario_c_features["any_feature"])
        scenario_c = ctx.apply_override(node_id, "scenario_c", scenario_c)

        ctx.set("scenario_a", scenario_a)
        ctx.set("scenario_b", scenario_b)
        ctx.set("scenario_c", scenario_c)

        actions = [
            Action(
                code="SCENARIOS_ASSESSED",
                label="HRRB alarm-feature scenarios assessed.",
                details={
                    "supported_by": [
                        f"Scenario A present: {scenario_a}",
                        f"Scenario B present: {scenario_b}",
                        f"Scenario C present: {scenario_c}",
                    ],
                    "scenario_a": scenario_a,
                    "scenario_b": scenario_b,
                    "scenario_c": scenario_c,
                    "scenario_c_features": scenario_c_features,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 55},
            )
        ]
        ctx.log(
            node_id,
            "SCENARIOS_ASSESSED",
            {
                "scenario_a": scenario_a,
                "scenario_b": scenario_b,
                "scenario_c": scenario_c,
            },
            actions,
        )
        return NodeResult(outputs=actions, next_node="Assign_Urgency")

    def node_assign_urgency(ctx: Context) -> NodeResult:
        node_id = "Assign_Urgency"

        scenario_a = bool(ctx.get("scenario_a"))
        scenario_b = bool(ctx.get("scenario_b"))
        scenario_c = bool(ctx.get("scenario_c"))

        dre_not_possible_due_to_pain = bool(ctx.get("dre_not_possible_due_to_pain"))

        if scenario_a or scenario_b:
            urgency = "urgent"
            label = "Urgent: colonoscopy referral (<2 weeks)"
            supported_by = []
            if scenario_a:
                supported_by.append("Scenario A is present")
            if scenario_b:
                supported_by.append("Scenario B is present")

        elif scenario_c or dre_not_possible_due_to_pain:
            urgency = "semi_urgent"
            label = "Semi-urgent: colonoscopy referral (<8 weeks)"
            supported_by = []
            if scenario_c:
                supported_by.append("Scenario C is present")
            if dre_not_possible_due_to_pain:
                supported_by.append("DRE could not be completed due to pain")

        else:
            stop = Stop(
                reason="HRRB is present but no urgent or semi-urgent alarm-feature scenario was identified; this pathway does not assign referral urgency.",
                actions=[
                    Action(
                        code="NO_HRRB_URGENCY_CRITERIA",
                        label="Monitor and re-evaluate; referral using this pathway is not established without Scenario A, B, or C.",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 90},
                    )
                ],
            )
            ctx.log(node_id, "NO_URGENCY_ASSIGNED", {}, [stop])
            return NodeResult(outputs=[stop])

        urgency = ctx.apply_override(node_id, "urgency", urgency)
        ctx.set("urgency", urgency)

        out = [
            Action(
                code="ASSIGN_URGENCY_HRRB",
                label=label,
                urgency=urgency,
                details={
                    "supported_by": supported_by,
                    "scenario_a": scenario_a,
                    "scenario_b": scenario_b,
                    "scenario_c": scenario_c,
                },
                override_options={
                    "node": node_id,
                    "field": "urgency",
                    "allowed": ["urgent", "semi_urgent"],
                    "reason_required": True,
                },
                display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 5},
            )
        ]
        ctx.log(node_id, "URGENCY_ASSIGNED", {"scenario_a": scenario_a, "scenario_b": scenario_b, "scenario_c": scenario_c}, out)
        return NodeResult(outputs=out, next_node="Finalize")

    def node_finalize(ctx: Context) -> NodeResult:
        node_id = "Finalize"
        urgency = ctx.get("urgency")

        referral_action = Action(
            code="REFER_COLONOSCOPY_HRRB",
            label="Refer for colonoscopy per HRRB urgency.",
            urgency=urgency,
            details={
                "supported_by": [
                    f"Final HRRB urgency is {urgency}",
                    "HRRB pathway reached final referral step",
                ]
            },
            display={
                "role": "primary_decision",
                "group_under": "ASSIGN_URGENCY_HRRB",
                "show_as_standalone": False,
                "sort_priority": 70,
            },
        )

        stop = Stop(
            reason="HRRB pathway complete: proceed with colonoscopy referral per assigned urgency and documented context.",
            actions=[referral_action],
            urgency=urgency,
        )
        ctx.log(node_id, "STOP", {"urgency": urgency}, [stop])
        return NodeResult(outputs=[stop])

    # Register nodes
    nodes["Confirm_HRRB"] = Node("Confirm_HRRB", node_confirm_hrrb)
    nodes["Medical_History"] = Node("Medical_History", node_history)
    nodes["Physical_Exam"] = Node("Physical_Exam", node_physical_exam)
    nodes["Baseline_Investigations"] = Node("Baseline_Investigations", node_baseline_investigations)
    nodes["Alarm_Features"] = Node("Alarm_Features", node_alarm_features)
    nodes["Assign_Urgency"] = Node("Assign_Urgency", node_assign_urgency)
    nodes["Finalize"] = Node("Finalize", node_finalize)

    return PathwayEngine(nodes=nodes, start_node="Confirm_HRRB")


# ==========================================================
# Convenience runner
# ==========================================================

def run_hrrb_pathway(patient_data: Dict[str, Any], overrides: Optional[List[Override]] = None):
    engine = hrrb_build_engine()
    ctx = Context(data=dict(patient_data), overrides=overrides or [])
    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx.overrides
