# -*- coding: utf-8 -*-
"""ibs_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SSUDit4DNvez7UHob-U49JOAnfXhktn
"""

"""
========================================================
PATHWAY FILE: Irritable Bowel Syndrome (IBS)
========================================================

Design goals
- Same architecture as other pathway engines
- Progressive gating with DataRequest
- UI-friendly outputs: Action / DataRequest / Stop
- Audit log support
- Override capability
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:

        outputs: List[Output] = []
        current = self.start_node

        while current:

            result = self.nodes[current].fn(ctx)

            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# IBS PATHWAY IMPLEMENTATION
# =========================================================

def ibs_build_engine() -> PathwayEngine:

    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # Node 1 – Confirm IBS Diagnostic Criteria
    # -----------------------------------------------------

    def node_confirm_ibs(ctx: Context):

        node_id = "Confirm_IBS_Criteria"

        pain_days = ctx.get("abdominal_pain_days_per_week")
        months = ctx.get("symptom_months_present")

        related = ctx.get("pain_related_to_defecation")
        freq_change = ctx.get("pain_with_change_in_stool_frequency")
        form_change = ctx.get("pain_with_change_in_stool_form")

        missing = []

        if pain_days is None:
            missing.append("abdominal_pain_days_per_week")

        if months is None:
            missing.append("symptom_months_present")

        if related is None:
            missing.append("pain_related_to_defecation")

        if freq_change is None:
            missing.append("pain_with_change_in_stool_frequency")

        if form_change is None:
            missing.append("pain_with_change_in_stool_form")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need core Rome IV IBS criteria data."
            )
            return NodeResult([dr])

        pain_threshold = pain_days >= 1
        duration_ok = months >= 3

        feature_count = sum([
            bool(related),
            bool(freq_change),
            bool(form_change)
        ])

        ibs_criteria = pain_threshold and duration_ok and feature_count >= 2
        ibs_criteria = ctx.apply_override(node_id, "ibs_criteria_met", ibs_criteria)

        ctx.set("ibs_criteria_met", ibs_criteria)

        if not ibs_criteria:

            stop = Stop(
                reason="IBS diagnostic criteria not met."
            )

            return NodeResult([stop])

        action = Action(
            code="IBS_CRITERIA_MET",
            label="IBS diagnostic criteria met.",
            override_options={
                "node": node_id,
                "field": "ibs_criteria_met",
                "allowed": [True, False],
                "reason_required": True,
            },
        )

        return NodeResult([action], next_node="Baseline_Investigations")


    nodes["Confirm_IBS_Criteria"] = Node("Confirm_IBS_Criteria", node_confirm_ibs)

    # -----------------------------------------------------
    # Node 2 – Baseline Investigations
    # -----------------------------------------------------

    def node_baseline(ctx: Context):

        node_id = "Baseline_Investigations"

        cbc = ctx.get("cbc_done")
        ferritin = ctx.get("ferritin_done")
        celiac = ctx.get("celiac_screen_done")

        missing = []

        if cbc is None:
            missing.append("cbc_done")

        if ferritin is None:
            missing.append("ferritin_done")

        if celiac is None:
            missing.append("celiac_screen_done")

        if missing:

            return NodeResult([
                DataRequest(
                    blocking_node=node_id,
                    missing_fields=missing,
                    message="Baseline IBS investigations required."
                )
            ])

        if ctx.get("celiac_screen_positive"):

            stop = Stop(
                reason="Positive celiac screen – refer for gastroenterology.",
                actions=[Action(
                    code="REFER_CELIAC",
                    label="Referral for positive celiac screen"
                )]
            )

            return NodeResult([stop])

        return NodeResult([
            Action(
                code="BASELINE_INVESTIGATIONS_COMPLETE",
                label="Baseline IBS investigations complete"
            )
        ], next_node="Alarm_Features")


    nodes["Baseline_Investigations"] = Node("Baseline_Investigations", node_baseline)


    # -----------------------------------------------------
    # Node 3 – Alarm Features
    # -----------------------------------------------------

    def node_alarm(ctx: Context):

        node_id = "Alarm_Features"

        alarm_flags = [
            ctx.get("family_history_crc_first_degree"),
            ctx.get("family_history_ibd_first_degree"),
            ctx.get("symptom_onset_after_age_50"),
            ctx.get("visible_blood_in_stool"),
            ctx.get("nocturnal_symptoms"),
            ctx.get("iron_deficiency_anemia_present"),
        ]

        weight_loss = ctx.get("unintended_weight_loss_percent_6_to_12_months")

        if weight_loss is not None and weight_loss > 5:
            alarm_flags.append(True)

        alarm_present = any(alarm_flags)
        alarm_present = ctx.apply_override(node_id, "alarm_features_present", alarm_present)

        ctx.set("alarm_features_present", alarm_present)

        if alarm_present:
            stop = Stop(
                reason="Alarm features present – urgent referral for endoscopy.",
                urgency="urgent",
                actions=[
                    Action(
                        code="URGENT_ENDOSCOPY_REFERRAL",
                        label="Urgent referral for endoscopy",
                        urgency="urgent",
                        override_options={
                            "node": node_id,
                            "field": "alarm_features_present",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                    )
                ],
            )
            return NodeResult([stop])

        return NodeResult([
            Action(
                code="NO_ALARM_FEATURES",
                label="No alarm features present."
            )
        ], next_node="Determine_Subtype")

    # -----------------------------------------------------
    # Node 4 – Determine IBS Subtype
    # -----------------------------------------------------

    def node_subtype(ctx: Context):

        node_id = "Determine_Subtype"

        hard = ctx.get("hard_stool_percent")
        loose = ctx.get("loose_stool_percent")

        if hard is None or loose is None:
            return NodeResult([
                DataRequest(
                    blocking_node=node_id,
                    missing_fields=["hard_stool_percent", "loose_stool_percent"],
                    message="Need stool form percentages to determine IBS subtype."
                )
            ])

        subtype = "IBS-U"

        if hard > 25 and loose < 25:
            subtype = "IBS-C"
        elif loose > 25 and hard < 25:
            subtype = "IBS-D"
        elif loose > 25 and hard > 25:
            subtype = "IBS-M"

        subtype = ctx.apply_override(node_id, "ibs_subtype", subtype)
        ctx.set("ibs_subtype", subtype)

        return NodeResult([
            Action(
                code="IBS_SUBTYPE",
                label=f"IBS subtype identified: {subtype}",
                details={"subtype": subtype},
                override_options={
                    "node": node_id,
                    "field": "ibs_subtype",
                    "allowed": ["IBS-C", "IBS-D", "IBS-M", "IBS-U"],
                    "reason_required": True,
                }
            )
        ], next_node="Subtype_Treatment")


    # -----------------------------------------------------
    # Node 5 – Subtype Treatment
    # -----------------------------------------------------

    def node_treatment(ctx: Context):

        subtype = ctx.get("ibs_subtype")

        actions = []

        if subtype == "IBS-D":

            actions.append(Action(
                code="IBS_D_TREATMENT",
                label="IBS-D treatment options",
                details={
                    "options": [
                        "loperamide",
                        "low FODMAP diet",
                        "tricyclic antidepressants",
                        "rifaximin"
                    ]
                }
            ))

            return NodeResult(actions, next_node="IBD_Check")

        if subtype == "IBS-C":

            actions.append(Action(
                code="IBS_C_TREATMENT",
                label="IBS-C treatment options",
                details={
                    "options": [
                        "soluble fibre",
                        "osmotic laxatives",
                        "linaclotide",
                        "prucalopride"
                    ]
                }
            ))

        else:

            actions.append(Action(
                code="IBS_GENERAL_TREATMENT",
                label="General IBS management"
            ))

        return NodeResult(actions, next_node="Management_Response")


    nodes["Subtype_Treatment"] = Node("Subtype_Treatment", node_treatment)


    # -----------------------------------------------------
    # Node 6 – IBD Suspicion Check
    # -----------------------------------------------------

    def node_ibd(ctx: Context):

        node_id = "IBD_Check"

        suspicion = ctx.get("high_suspicion_ibd")

        if suspicion is None:
            return NodeResult([
                DataRequest(
                    blocking_node=node_id,
                    missing_fields=["high_suspicion_ibd"],
                    message="Need clinician judgement: high suspicion of IBD?"
                )
            ])

        suspicion = ctx.apply_override(node_id, "high_suspicion_ibd", suspicion)
        ctx.set("high_suspicion_ibd", suspicion)

        if not suspicion:
            return NodeResult([], next_node="Management_Response")

        return NodeResult([], next_node="Fecal_Calprotectin")


    # -----------------------------------------------------
    # Node 7 – Fecal Calprotectin
    # -----------------------------------------------------

    def node_calprotectin(ctx: Context):

        node_id = "Fecal_Calprotectin"

        cal = ctx.get("fecal_calprotectin_ug_g")

        if cal is None:
            return NodeResult([
                DataRequest(
                    blocking_node=node_id,
                    missing_fields=["fecal_calprotectin_ug_g"],
                    message="Need fecal calprotectin result."
                )
            ])

        elevated_calprotectin = cal > 120
        elevated_calprotectin = ctx.apply_override(node_id, "elevated_calprotectin", elevated_calprotectin)
        ctx.set("elevated_calprotectin", elevated_calprotectin)

        if elevated_calprotectin:
            stop = Stop(
                reason="Elevated fecal calprotectin – refer to gastroenterology.",
                actions=[
                    Action(
                        code="REFER_IBD_EVALUATION",
                        label="Referral for suspected IBD",
                        override_options={
                            "node": node_id,
                            "field": "elevated_calprotectin",
                            "allowed": [True, False],
                            "reason_required": True,
                        }
                    )
                ]
            )
            return NodeResult([stop])

        return NodeResult([], next_node="Management_Response")


    # -----------------------------------------------------
    # Node 8 – Management Response
    # -----------------------------------------------------

    def node_management(ctx: Context):

        node_id = "Management_Response"

        unsatisfactory = ctx.get("unsatisfactory_response_to_treatment")

        if unsatisfactory is None:
            return NodeResult([
                DataRequest(
                    blocking_node=node_id,
                    missing_fields=["unsatisfactory_response_to_treatment"],
                    message="Need response to IBS treatment."
                )
            ])

        unsatisfactory = ctx.apply_override(node_id, "unsatisfactory_response_to_treatment", unsatisfactory)
        ctx.set("unsatisfactory_response_to_treatment", unsatisfactory)

        if unsatisfactory:
            return NodeResult([
                Action(
                    code="CONSIDER_ADVICE_SERVICE",
                    label="Consider specialist advice service",
                    override_options={
                        "node": node_id,
                        "field": "unsatisfactory_response_to_treatment",
                        "allowed": [True, False],
                        "reason_required": True,
                    }
                )
            ])

        stop = Stop(
            reason="IBS pathway complete – continue management in medical home."
        )

        return NodeResult([stop])

    nodes["Alarm_Features"] = Node("Alarm_Features", node_alarm)
    nodes["Determine_Subtype"] = Node("Determine_Subtype", node_subtype)
    nodes["IBD_Check"] = Node("IBD_Check", node_ibd)
    nodes["Fecal_Calprotectin"] = Node("Fecal_Calprotectin", node_calprotectin)
    nodes["Management_Response"] = Node("Management_Response", node_management)

    return PathwayEngine(
        nodes=nodes,
        start_node="Confirm_IBS_Criteria"
    )
# =========================================================
# RUNNER
# =========================================================

def run_ibs_pathway(patient_data: Dict[str, Any], overrides=None):

    engine = ibs_build_engine()

    ctx = Context(
        data=dict(patient_data),
        overrides=overrides or []
    )

    outputs = engine.run(ctx)

    return outputs, ctx.logs, ctx.overrides
