# -*- coding: utf-8 -*-
"""ida_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18L_5vn-ktFtLuzEYMd9b-9iCv5btmQuW
"""

"""
========================================================
PATHWAY FILE: Iron Deficiency Anemia → CRC Referral (IDA)
========================================================

Design goals (as requested):
- Progressive decision gating: run as far as possible with partial data
- Only stop when a decision node cannot proceed without critical info
- UI-ready outputs: Action / DataRequest / Stop
- Full audit log for every node
- Nurse/clinician overrides supported at specific nodes/fields
- Represents expanded pathway text (including the non-diagram details)

--------------------------------------------------------
PATIENT DATA (Context.data) — variables used in this file
--------------------------------------------------------

Core IDA diagnosis:
- sex: "male" | "female"
- hemoglobin: float (g/L)
- ferritin: float (ug/L)
- inflammation_present: bool (infection/active IBD/inflammation)
- transferrin_saturation: float (%) optional
- chronic_kidney_disease: bool optional (significant CKD; affects ferritin>100 caveat)

Urgent alarm subset (explicit urgent criteria in text):
- significant_diarrhea: bool
- weight_loss: bool  (represents unintentional ≥5–10% body weight over 6 months)
- progressive_bowel_change: bool
- significant_abdominal_pain: bool

Other triage-modifying features (listed as influencing triage, not automatic urgent):
- nocturnal_symptoms: bool
- family_history_crc_first_degree: bool
- family_history_ibd_first_degree: bool
- evidence_of_gi_bleeding: bool

“Unexplained” qualifier (scope within last 2 years):
- complete_colonoscopy_within_2y: bool | None
- lower_endoscopy_within_2y: bool | None   (optional alias; if present can map to above)
- colonoscopy_complete: bool | None         (optional detail)
- alarm_features_investigated_by_lower_endoscopy_within_2y: Optional[bool]

Hb baseline drop nuance:
- baseline_hemoglobin: float | None
- hemoglobin_drop_g_per_l: float | None (optional; if not provided and baseline exists, derived)
- drop_unexplained: bool | None         (optional; can be overridden)

Celiac rule-out:
- prior_duodenal_biopsy_normal: bool
- ttg_years_since_test: float  (years since TTG; <5 = recent)
- ttg_positive: bool | None
- celiac_duration_months: float | None
- gluten_free_compliant: bool | None
- anemia_out_of_keeping_with_menses: bool | None  (used both in celiac text and gyne text)
- ttg_positive_repeat: bool | None
Gynecology:
- age: int | None
- menstruating: bool | None
- hysterectomy: bool | None

High-risk rectal bleeding (computed from detail fields if provided):
- rectal_bleeding_visible: bool | None              (blood visibly in/on stool or toilet; not just tissue)
- rectal_bleeding_new_or_worsening: bool | None
- rectal_bleeding_most_days: bool | None
- rectal_bleeding_duration_weeks: float | None
- other_alarm_features_with_bleeding: bool | None   (if you want to explicitly mark “bleeding + alarm features”)

FIT warning:
- fit_ordered_or_planned: bool | None

Investigation freshness (within 8 weeks of referral):
(you can provide either dates as days ago or boolean flags)
- cbc_days_ago: int | None
- ferritin_days_ago: int | None
- ttg_days_ago: int | None
- cbc_within_8_weeks: bool | None
- ferritin_within_8_weeks: bool | None
- ttg_within_8_weeks: bool | None

Medication review reminders:
- anticoagulants: bool | None
- antiplatelets: bool | None
- nsaid_use: bool | None

Physical exam reminder:
- rectal_exam_done: bool | None

--------------------------------------------------------
OVERRIDES (Context.overrides)
--------------------------------------------------------
Overrides apply at (node, field). Examples:
- ("Urgency_Triage", "urgency") -> "urgent" / "semi_urgent" / "routine"
- ("Confirm_IDA", "ida_confirmed") -> True/False
- ("HighRiskRectalBleeding_Check", "high_risk_rectal_bleeding") -> True/False
- ("Celiac_RuleOut", "proceed_with_referral_despite_celiac") -> True/False
- ("Urgency_Triage", "alarm_unexplained") -> True/False
- ("Urgency_Triage", "urgent_due_to_hb_drop") -> True/False

========================================================
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================
# Output types (UI friendly)
# =========================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None   # "urgent" | "semi_urgent" | "routine" | None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None

    # NEW: UI/report display metadata
    display: Dict[str, Any] = field(default_factory=dict)

@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)

@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None

Output = Action | DataRequest | Stop


# =========================
# Audit trail + overrides
# =========================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str

    # Store as datetime for stable ordering; serialize when needed
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

# =========================
# Context
# =========================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key: str, default=None):
        return self.data.get(key, default)

    def set(self, key: str, value: Any):
        self.data[key] = value

    def apply_override(self, node: str, field: str, current_value: Any) -> Any:
        candidates = [o for o in self.overrides if o.target_node == node and o.field == field]
        if not candidates:
            return current_value
        newest = max(candidates, key=lambda o: o.created_at)
        return newest.new_value
    def add_override(self, target_node: str, field: str, new_value: Any, reason: str):
        """
        Convenience helper for UI/testing.
        Looks up the current value in Context.data if present (optional),
        stores an Override object, and allows apply_override() to pick it up.
        """
        old_value = self.data.get(field, None)
        self.overrides.append(
            Override(
                target_node=target_node,
                field=field,
                old_value=old_value,
                new_value=new_value,
                reason=reason,
            )
        )

    def log(self, node: str, decision: str, used_inputs: Dict[str, Any], outputs: List[Output]):
        def ser_action(a: Action) -> Dict[str, Any]:
            return {
                "type": "action",
                "code": a.code,
                "label": a.label,
                "urgency": a.urgency,
                "details": a.details,
                "override_options": a.override_options,
                "display": a.display,
            }

        def ser(o: Output) -> Dict[str, Any]:
            if isinstance(o, Action):
                return ser_action(o)

            if isinstance(o, DataRequest):
                return {
                    "type": "data_request",
                    "blocking_node": o.blocking_node,
                    "missing_fields": o.missing_fields,
                    "message": o.message,
                    "urgency_context": o.urgency_context,
                    "suggested_actions": [ser_action(a) for a in o.suggested_actions],
                }

            if isinstance(o, Stop):
                return {
                    "type": "stop",
                    "reason": o.reason,
                    "urgency": o.urgency,
                    "actions": [ser_action(a) for a in o.actions],
                }

            return {"type": "unknown"}

        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=used_inputs,
                outputs=[ser(x) for x in outputs],
            )
        )

# =========================
# Node engine
# =========================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None

NodeFn = Callable[[Context], NodeResult]

@dataclass
class Node:
    node_id: str
    fn: NodeFn

class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current is not None:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break
            if current not in self.nodes:
                outputs.append(Stop(reason=f"Engine error: unknown node '{current}' (typo or missing registration)."))
                break
            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (DataRequest, Stop)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# ==========================================================
# IDA PATHWAY IMPLEMENTATION
# ==========================================================

def ida_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -------------------------
    # Helpers
    # -------------------------

    def _normalize_scope_flag(ctx: Context) -> Optional[bool]:
        """
        Accepts either:
        - complete_colonoscopy_within_2y
        - lower_endoscopy_within_2y (alias)
        Preference: complete_colonoscopy_within_2y if present.
        """
        v = ctx.get("complete_colonoscopy_within_2y")
        if v is not None:
            return v
        return ctx.get("lower_endoscopy_within_2y")

    def _iron_deficiency(ctx: Context) -> Dict[str, Any]:
        """
        Returns dict:
          {
            "blocked": bool,
            "missing": [...],
            "iron_deficient": bool|None,
            "ferritin_cutoff": float|None,
            "notes": [...]
          }
        """
        notes: List[str] = []
        sex = ctx.get("sex")
        ferritin = ctx.get("ferritin")
        inflammation = ctx.get("inflammation_present")
        tsat = ctx.get("transferrin_saturation")
        ckd = ctx.get("chronic_kidney_disease")  # optional caveat variable

        missing = []
        if sex is None:
            missing.append("sex")
        if ferritin is None:
            missing.append("ferritin")

        if missing:
            return {"blocked": True, "missing": missing, "iron_deficient": None, "ferritin_cutoff": None, "notes": notes}

        ferritin_cutoff = 30.0 if sex == "male" else 20.0
        notes.append(f"Base ferritin cutoff used: {ferritin_cutoff} (sex-specific)")

        if inflammation is True:
            ferritin_cutoff = 100.0
            notes.append("Inflammation present: ferritin <100 supports iron deficiency (acute phase reactant adjustment)")

        # Pathway text caveat: ferritin >100 and no significant CKD -> iron deficiency very unlikely
        if ferritin > 100.0 and not ckd:
            iron_deficient = False
            notes.append("Ferritin >100 and no significant CKD: iron deficiency very unlikely per pathway text")
        else:
            iron_deficient = ferritin < ferritin_cutoff

        # TSAT <16 supports diagnosis
        if tsat is not None and tsat < 16.0:
            iron_deficient = True
            notes.append("Transferrin saturation <16% supports iron deficiency -> set True")

        return {"blocked": False, "missing": [], "iron_deficient": iron_deficient, "ferritin_cutoff": ferritin_cutoff, "notes": notes}

    def _urgent_alarm_subset(ctx: Context) -> bool:
        return any([
            bool(ctx.get("significant_diarrhea")),
            bool(ctx.get("weight_loss")),
            bool(ctx.get("progressive_bowel_change")),
            bool(ctx.get("significant_abdominal_pain")),
        ])

    def _triage_modifiers_present(ctx: Context) -> bool:
        return any([
            bool(ctx.get("nocturnal_symptoms")),
            bool(ctx.get("family_history_crc_first_degree")),
            bool(ctx.get("family_history_ibd_first_degree")),
            bool(ctx.get("evidence_of_gi_bleeding")),
            # IDA onset age >40 is a modifier; if age available we can compute later
        ])

    def _freshness_flag(days_ago: Optional[int], within_flag: Optional[bool]) -> Optional[bool]:
        """
        If within_flag provided, use it.
        Else if days_ago provided, compute <=56 days (~8 weeks).
        Else None.
        """
        if within_flag is not None:
            return within_flag
        if days_ago is None:
            return None
        return days_ago <= 56

    # -------------------------
    # Nodes
    # -------------------------

    def node_confirm_ida(ctx: Context) -> NodeResult:
        node_id = "Confirm_IDA"

        hb = ctx.get("hemoglobin")
        sex = ctx.get("sex")

        missing = []
        if hb is None:
            missing.append("hemoglobin")
        if ctx.get("ferritin") is None:
            missing.append("ferritin")
        if sex is None:
            missing.append("sex")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Cannot confirm IDA without hemoglobin, ferritin, and sex (thresholds are sex-specific).",
                suggested_actions=[
                    Action(code="ORDER_HB", label="Obtain hemoglobin (Hb)"),
                    Action(code="ORDER_FERRITIN", label="Obtain serum ferritin"),
                    Action(code="CAPTURE_SEX", label="Record patient sex"),
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult(outputs=[dr])

        # Anemia definition (pathway text)
        anemia = False
        if sex == "male" and hb < 130:
            anemia = True
        if sex == "female" and hb < 120:
            anemia = True

        iron = _iron_deficiency(ctx)
        if iron["blocked"]:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=iron["missing"],
                message="Cannot determine iron deficiency without sex and ferritin.",
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": iron["missing"]}, [dr])
            return NodeResult(outputs=[dr])

        ida_confirmed = bool(anemia and iron["iron_deficient"])
        ida_confirmed = ctx.apply_override(node_id, "ida_confirmed", ida_confirmed)
        ctx.set("ida_confirmed", ida_confirmed)

        if not ida_confirmed:
            stop = Stop(
                reason=(
                    "IDA not confirmed: both anemia and iron deficiency must be present. "
                    "Consider alternative anemia etiologies and interpret iron indices accordingly."
                ),
                actions=[Action(code="ALT_ANEMIA_WORKUP", label="Investigate non-IDA anemia causes / alternative etiologies")],
            )
            ctx.log(
                node_id,
                "IDA_NOT_CONFIRMED",
                {"hemoglobin": hb, "sex": sex, "ferritin": ctx.get("ferritin")},
                [stop],
            )
            return NodeResult(outputs=[stop])

        out = [
            Action(
                code="IDA_CONFIRMED",
                label="IDA confirmed (low Hb + low iron stores).",
                details={
                    "supported_by": [
                        f"Hb {hb} g/L is below the anemia threshold for sex ({'130' if sex == 'male' else '120'} g/L)",
                        f"Ferritin interpretation supports iron deficiency using cutoff {iron['ferritin_cutoff']}",
                    ] + (["Transferrin saturation <16% supports iron deficiency"] if ctx.get("transferrin_saturation") is not None and ctx.get("transferrin_saturation") < 16 else []),
                    "anemia": anemia,
                    "iron_deficient": iron["iron_deficient"],
                    "ferritin_cutoff_used": iron["ferritin_cutoff"],
                    "notes": iron["notes"],
                },
                override_options={
                    "node": node_id,
                    "field": "ida_confirmed",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 20,
                },
            )
        ]
        ctx.log(node_id, "IDA_CONFIRMED", {"hemoglobin": hb, "sex": sex, "ferritin": ctx.get("ferritin")}, out)
        return NodeResult(outputs=out, next_node="Urgency_Triage")

    def node_urgency(ctx: Context) -> NodeResult:
        node_id = "Urgency_Triage"

        hb = ctx.get("hemoglobin")
        sex = ctx.get("sex")

        # Safety progressive gating (should already exist from IDA confirm)
        missing = []
        if hb is None:
            missing.append("hemoglobin")
        if sex is None:
            missing.append("sex")
        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Cannot assign urgency without hemoglobin and sex.",
                suggested_actions=[Action(code="ORDER_HB", label="Obtain hemoglobin (Hb)"), Action(code="CAPTURE_SEX", label="Record patient sex")]
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult(outputs=[dr])

        # Compute “unexplained” alarm symptom status:
        # Pathway text qualifies alarm symptoms as “unexplained (i.e., not investigated by lower endoscopy in the last 2 years)”
        urgent_alarm_present = _urgent_alarm_subset(ctx)

        scope_within_2y = _normalize_scope_flag(ctx)

        investigated = ctx.get("alarm_features_investigated_by_lower_endoscopy_within_2y")

        alarm_unexplained: Optional[bool] = None
        if urgent_alarm_present:
            if investigated is None:
                # progressive gate ONLY on whether the alarm features were investigated
                dr = DataRequest(
                    blocking_node=node_id,
                    missing_fields=["alarm_features_investigated_by_lower_endoscopy_within_2y"],
                    message=(
                        "Urgent alarm symptom(s) present. Need to know whether these alarm features have been investigated "
                        "by lower endoscopy within the last 2 years (not just whether a colonoscopy occurred)."
                    ),
                    suggested_actions=[
                        Action(
                            code="CAPTURE_ALARM_INVESTIGATION",
                            label="Document whether current alarm features were investigated by lower endoscopy within last 2 years"
                        )
                    ]
                )
                ctx.log(node_id, "BLOCKED_MISSING_DATA", {"urgent_alarm_present": True, "scope_within_2y_context_only": scope_within_2y}, [dr])
                return NodeResult(outputs=[dr])

            alarm_unexplained = (investigated is False)

        # Hb urgent criteria per text
        urgent_hb = (hb < 110) if sex == "male" else (hb < 100)

        # Hb semi-urgent band
        semi_urgent = False
        if sex == "male":
            semi_urgent = 110 <= hb < 130
        else:
            semi_urgent = 100 <= hb < 120

        # Baseline drop nuance:
        # Text notes that some patients (CKD/elderly/anemia of chronic disease) may have baseline Hb below normal.
        # A significant unexplained drop from baseline is a reason for referral.
        baseline_hb = ctx.get("baseline_hemoglobin")
        hb_drop = ctx.get("hemoglobin_drop_g_per_l")

        if hb_drop is None and baseline_hb is not None and hb is not None:
            hb_drop = baseline_hb - hb
            ctx.set("hemoglobin_drop_g_per_l", hb_drop)

        # We do NOT block if baseline is missing; we only incorporate if available.
        urgent_due_to_hb_drop = False
        if hb_drop is not None:
            # No numeric cutoff provided in text; treat as a clinician-judgement hook.
            # Default heuristic: any drop >= 20 g/L is noteworthy; can be overridden.
            drop_unexplained = ctx.get("drop_unexplained")
            if drop_unexplained is None:
                # If not specified, we treat as unknown and do not force urgent on drop alone.
                urgent_due_to_hb_drop = False
            else:
                urgent_due_to_hb_drop = (hb_drop >= 20.0 and drop_unexplained is True)

            urgent_due_to_hb_drop = ctx.apply_override(node_id, "urgent_due_to_hb_drop", urgent_due_to_hb_drop)

        # Urgency decision:
        # Urgent if urgent_hb OR (urgent alarms present AND unexplained)
        urgent_alarm_qualifies = bool(urgent_alarm_present and (alarm_unexplained is True))
        urgent_alarm_qualifies = ctx.apply_override(node_id, "urgent_alarm_qualifies", urgent_alarm_qualifies)

        if urgent_hb or urgent_alarm_qualifies or urgent_due_to_hb_drop:
            urgency = "urgent"
            label = "Urgent: gastroscopy + colonoscopy (<2 weeks)"
        elif semi_urgent:
            urgency = "semi_urgent"
            label = "Semi-urgent: endoscopy referral"
        else:
            urgency = "routine"
            label = "Routine: endoscopy referral"

        urgency = ctx.apply_override(node_id, "urgency", urgency)
        ctx.set("urgency", urgency)

        supported_by = []
        if urgent_hb:
            supported_by.append("Hb below urgent threshold for sex")
        if urgent_alarm_qualifies:
            supported_by.append("Unexplained urgent alarm symptom(s) present")
        if urgent_due_to_hb_drop:
            supported_by.append("Significant unexplained Hb drop from baseline")
        if semi_urgent and not (urgent_hb or urgent_alarm_qualifies or urgent_due_to_hb_drop):
            supported_by.append("Hb in semi-urgent band for sex")
        if (not urgent_hb) and (not urgent_alarm_qualifies) and (not urgent_due_to_hb_drop) and (not semi_urgent):
            supported_by.append("Hb not in urgent/semi-urgent thresholds and no qualifying alarms")

        out = [Action(
            code="ASSIGN_URGENCY",
            label=label,
            urgency=urgency,
            details={
                "supported_by": supported_by,
                "urgent_hb_threshold_met": urgent_hb,
                "urgent_alarm_present": urgent_alarm_present,
                "scope_within_2y_context_only": scope_within_2y,
                "alarm_features_investigated_by_lower_endoscopy_within_2y": investigated,
                "alarm_unexplained": alarm_unexplained,
                "urgent_alarm_qualifies": urgent_alarm_qualifies,
                "baseline_hemoglobin": baseline_hb,
                "hemoglobin_drop_g_per_l": hb_drop,
                "urgent_due_to_hb_drop": urgent_due_to_hb_drop,
                "semi_urgent_band_met": semi_urgent,
            },
            display={
                "role": "primary_decision",
                "show_as_standalone": True,
                "sort_priority": 10,
            },
        )]
        ctx.log(
            node_id,
            "URGENCY_ASSIGNED",
            {
                "hemoglobin": hb,
                "sex": sex,
                "urgent_alarm_present": urgent_alarm_present,
                "alarm_features_investigated_by_lower_endoscopy_within_2y": investigated,
                "alarm_unexplained": alarm_unexplained,
                "urgent_alarm_qualifies": urgent_alarm_qualifies,
                "baseline_hemoglobin": baseline_hb,
                "hemoglobin_drop_g_per_l": hb_drop,
                "drop_unexplained": ctx.get("drop_unexplained"),
                "urgent_due_to_hb_drop": urgent_due_to_hb_drop,
                "scope_within_2y_context_only": scope_within_2y,
            },
            out,
        )
        return NodeResult(outputs=out, next_node="Celiac_RuleOut")

    def node_celiac(ctx: Context) -> NodeResult:
        node_id = "Celiac_RuleOut"
        urgency = ctx.get("urgency")

        # Collect non-blocking reminders/recommendations so they actually appear in outputs
        extra_outputs: List[Output] = []

        # Exemption: prior normal duodenal biopsy
        if ctx.get("prior_duodenal_biopsy_normal") is True:
            out = [
                Action(
                    code="CELIAC_EXEMPT",
                    label="Celiac rule-out not required: prior normal duodenal biopsy documented.",
                    urgency=urgency,
                    details={
                        "supported_by": ["Prior normal duodenal biopsy documented"],
                    },
                    display={
                        "role": "support",
                        "badge": "info",
                        "show_as_standalone": True,
                        "sort_priority": 30,
                    },
                )
            ]
            ctx.log(node_id, "EXEMPT_BIOPSY_NORMAL", {"prior_duodenal_biopsy_normal": True}, out)
            return NodeResult(outputs=out, next_node="Gynecology_Check")

        # Need TTG recency to apply the <5y rule (TTG not required if done within last 5 years)
        years_since = ctx.get("ttg_years_since_test")
        if years_since is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["ttg_years_since_test"],
                message="Need years since last TTG to apply the <5-year rule (TTG not required if done within last 5 years).",
                urgency_context=urgency,
                suggested_actions=[
                    Action(
                        code="CAPTURE_TTG_RECENCY",
                        label="Enter years since last TTG (<5 is recent)",
                        urgency=urgency
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["ttg_years_since_test"]}, [dr])
            return NodeResult(outputs=[dr])

        # If TTG is outdated (>=5 years), we cannot make a decision from the old result.
        # Require a repeat TTG result specifically (ttg_positive_repeat).
        if years_since >= 5:
            order = Action(
                code="ORDER_TTG",
                label="TTG is outdated (≥5 years): order/repeat TTG to rule out celiac (IgA not required per pathway text).",
                urgency=urgency,
                details={"ttg_years_since_test": years_since},
            )
            extra_outputs.append(order)

            ttg_repeat = ctx.get("ttg_positive_repeat")
            if ttg_repeat is None:
                dr = DataRequest(
                    blocking_node=node_id,
                    missing_fields=["ttg_positive_repeat"],
                    message=(
                        "Last TTG is ≥5 years old. Do not use outdated TTG to decide celiac rule-out. "
                        "Repeat TTG and enter the NEW result (positive/negative) to proceed."
                    ),
                    urgency_context=urgency,
                    suggested_actions=[
                        order,
                        Action(
                            code="CAPTURE_TTG_RESULT_REPEAT",
                            label="Enter repeat TTG result (new test)",
                            urgency=urgency,
                        ),
                    ],
                )
                ctx.log(
                    node_id,
                    "TTG_OUTDATED_BLOCK_REPEAT_REQUIRED",
                    {"ttg_years_since_test": years_since},
                    extra_outputs + [dr],
                )
                return NodeResult(outputs=extra_outputs + [dr])

            # Repeat result exists: use it going forward
            ttg_positive = ttg_repeat
            ctx.log(
                node_id,
                "TTG_OUTDATED_REPEAT_PRESENT",
                {"ttg_years_since_test": years_since, "ttg_positive_repeat": ttg_repeat},
                extra_outputs,
            )
        else:
            # TTG is recent (<5y): use ttg_positive
            ttg_positive = ctx.get("ttg_positive")

        # Need TTG result to complete rule-out
        if ttg_positive is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["ttg_positive"],
                message="Provide TTG result (positive/negative) to complete celiac rule-out.",
                urgency_context=urgency,
                suggested_actions=[
                    Action(code="CAPTURE_TTG_RESULT", label="Enter TTG result", urgency=urgency)
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"ttg_years_since_test": years_since}, extra_outputs + [dr])
            return NodeResult(outputs=extra_outputs + [dr])

        # TTG negative -> celiac ruled out
        if ttg_positive is False:
            out = [
                Action(
                    code="CELIAC_RULED_OUT",
                    label="Celiac ruled out: TTG negative (per available testing).",
                    urgency=urgency,
                    details={
                        "supported_by": ["TTG result negative"],
                        "ttg_years_since_test": years_since,
                    },
                    display={
                        "role": "support",
                        "badge": "info",
                        "show_as_standalone": True,
                        "sort_priority": 30,
                    },
                )
            ]
            ctx.log(node_id, "TTG_NEGATIVE", {"ttg_positive": False, "ttg_years_since_test": years_since}, out)
            return NodeResult(outputs=extra_outputs + out, next_node="Gynecology_Check")

        # TTG positive: apply expanded text nuance:
        # If longstanding (>6 months) and compliant gluten-free diet AND/OR anemia out of keeping with heavy menstruation -> proceed with referral.
        celiac_duration_months = ctx.get("celiac_duration_months")
        gluten_free_compliant = ctx.get("gluten_free_compliant")
        anemia_out = ctx.get("anemia_out_of_keeping_with_menses")

        missing = []
        if celiac_duration_months is None:
            missing.append("celiac_duration_months")
        if gluten_free_compliant is None:
            missing.append("gluten_free_compliant")
        if anemia_out is None:
            missing.append("anemia_out_of_keeping_with_menses")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message=(
                    "TTG positive. To follow pathway text, need celiac duration (>6 months?), gluten-free compliance, "
                    "and whether anemia is out of keeping with heavy menstruation to decide whether to proceed with referral."
                ),
                urgency_context=urgency,
                suggested_actions=[
                    Action(
                        code="CAPTURE_CELIAC_CONTEXT",
                        label="Capture celiac duration, GFD compliance, and menstrual proportionality",
                        urgency=urgency,
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA_TTG_POS", {"ttg_positive": True}, [dr])
            return NodeResult(outputs=extra_outputs + [dr])

        longstanding = (celiac_duration_months > 6)
        proceed = (longstanding and gluten_free_compliant) or bool(anemia_out)
        proceed = ctx.apply_override(node_id, "proceed_with_referral_despite_celiac", proceed)

        if proceed:
            out = [
                Action(
                    code="CELIAC_POSITIVE_PROCEED",
                    label="TTG positive, but per pathway: longstanding treated celiac and/or anemia disproportionate to menses → proceed with referral.",
                    urgency=urgency,
                    details={
                        "supported_by": [
                            "TTG positive",
                            "Pathway allows referral if longstanding treated celiac and/or anemia is disproportionate to menses",
                        ],
                        "celiac_duration_months": celiac_duration_months,
                        "gluten_free_compliant": gluten_free_compliant,
                        "anemia_out_of_keeping_with_menses": anemia_out,
                        "ttg_years_since_test": years_since,
                    },
                    display={
                        "role": "support",
                        "badge": "info",
                        "show_as_standalone": True,
                        "sort_priority": 30,
                    },
                )
            ]
            ctx.log(node_id, "TTG_POSITIVE_PROCEED", {"ttg_positive": True}, out)
            return NodeResult(outputs=extra_outputs + out, next_node="Gynecology_Check")

        # If TTG positive but criteria to proceed are NOT met, route/hold for celiac management.
        out = [
            Action(
                code="CELIAC_POSITIVE_MANAGE",
                label="TTG positive: manage/confirm celiac disease; proceed with referral only if longstanding treated and/or anemia disproportionate to menses per pathway.",
                urgency=urgency,
                details={
                    "supported_by": [
                        "TTG positive",
                        "Proceed criteria for referral despite celiac were not met",
                    ],
                    "celiac_duration_months": celiac_duration_months,
                    "gluten_free_compliant": gluten_free_compliant,
                    "anemia_out_of_keeping_with_menses": anemia_out,
                    "ttg_years_since_test": years_since,
                },
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 30,
                },
            )
        ]
        ctx.log(node_id, "TTG_POSITIVE_MANAGE", {"ttg_positive": True, "proceed": False}, out)
        return NodeResult(outputs=extra_outputs + out, next_node="Gynecology_Check")

    def node_gyne(ctx: Context) -> NodeResult:
        node_id = "Gynecology_Check"
        urgency = ctx.get("urgency")

        if ctx.get("sex") != "female":
            out = [
                Action(
                    code="GYNE_NOT_APPLICABLE",
                    label="Gynecology causes not applicable (not female).",
                    details={
                        "supported_by": ["Patient sex is not female"],
                    },
                    display={
                        "role": "support",
                        "badge": "info",
                        "show_as_standalone": True,
                        "sort_priority": 35,
                    },
                )
            ]
            ctx.log(node_id, "SKIP", {"sex": ctx.get("sex")}, out)
            return NodeResult(outputs=out, next_node="HighRiskRectalBleeding_Check")

        age = ctx.get("age")
        menstruating = ctx.get("menstruating")
        hysterectomy = ctx.get("hysterectomy")
        anemia_out = ctx.get("anemia_out_of_keeping_with_menses")

        missing = []
        if age is None:
            missing.append("age")
        if menstruating is None:
            missing.append("menstruating")
        if hysterectomy is None:
            missing.append("hysterectomy")
        if anemia_out is None:
            missing.append("anemia_out_of_keeping_with_menses")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Female patient: need age, menstruation status, hysterectomy status, and whether anemia is out of keeping with heavy menstruation.",
                urgency_context=urgency,
                suggested_actions=[Action(code="CAPTURE_GYNE", label="Capture gynecology context", urgency=urgency)]
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult(outputs=[dr])

        # If menstruating <50 and anemia proportional -> trial iron.
        if (age < 50) and menstruating and (not hysterectomy) and (not anemia_out):
            out = [
                Action(
                    code="TRIAL_IRON",
                    label="Menstruating female <50: consider menstrual losses; trial iron replacement (if anemia proportional to menses).",
                    urgency=urgency,
                    details={
                        "supported_by": [
                            "Female under 50",
                            "Currently menstruating",
                            "No hysterectomy",
                            "Anemia appears proportionate to menstrual losses",
                        ],
                        "age": age,
                        "menstruating": menstruating,
                        "hysterectomy": hysterectomy,
                        "anemia_out_of_keeping_with_menses": anemia_out,
                    },
                    display={
                        "role": "support",
                        "badge": "info",
                        "show_as_standalone": True,
                        "sort_priority": 35,
                    },
                )
            ]
            ctx.log(
                node_id,
                "TRIAL_IRON_RECOMMENDED",
                {"age": age, "menstruating": menstruating, "hysterectomy": hysterectomy, "anemia_out": anemia_out},
                out,
            )
            return NodeResult(outputs=out, next_node="HighRiskRectalBleeding_Check")

        # Otherwise proceed with referral pathway
        out = [
            Action(
                code="GYNE_PROCEED",
                label="Gynecology causes do not fully explain IDA or anemia disproportionate → proceed with referral pathway.",
                urgency=urgency,
                details={
                    "supported_by": [
                        "Gynecology causes do not fully explain the anemia",
                    ],
                    "age": age,
                    "menstruating": menstruating,
                    "hysterectomy": hysterectomy,
                    "anemia_out_of_keeping_with_menses": anemia_out,
                },
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 35,
                },
            )
        ]
        ctx.log(
            node_id,
            "PROCEED",
            {"age": age, "menstruating": menstruating, "hysterectomy": hysterectomy, "anemia_out": anemia_out},
            out,
        )
        return NodeResult(outputs=out, next_node="HighRiskRectalBleeding_Check")

    def node_hrrb(ctx: Context) -> NodeResult:
        node_id = "HighRiskRectalBleeding_Check"
        urgency = ctx.get("urgency")

        visible = ctx.get("rectal_bleeding_visible")
        new_or_worsening = ctx.get("rectal_bleeding_new_or_worsening")
        most_days = ctx.get("rectal_bleeding_most_days")
        duration_weeks = ctx.get("rectal_bleeding_duration_weeks")

        # ✅ NEW: If bleeding is explicitly NOT visible, this pathway is not applicable.
        # Do NOT ask for the other bleeding-detail fields.
        if visible is False:
            out = [
                Action(
                    code="HRRB_NOT_APPLICABLE",
                    label="No visible rectal bleeding → high-risk rectal bleeding pathway not applicable.",
                    urgency=urgency,
                    details={
                        "supported_by": ["Rectal bleeding is explicitly not visible"],
                        "rectal_bleeding_visible": False,
                    },
                    display={
                        "role": "support",
                        "badge": "info",
                        "show_as_standalone": True,
                        "sort_priority": 40,
                    },
                )
            ]
            ctx.log(node_id, "NO_VISIBLE_BLEEDING_SKIP", {"rectal_bleeding_visible": False}, out)
            return NodeResult(outputs=out, next_node="FIT_Warning")

        # If no bleeding data at all, do not block; just continue and remind.
        if all(x is None for x in [visible, new_or_worsening, most_days, duration_weeks]):
            out = [
                Action(
                    code="CONSIDER_HRRB",
                    label="Consider whether high-risk rectal bleeding is present (if so, route to HRRB pathway).",
                    urgency=urgency,
                    display={
                        "role": "support",
                        "badge": "info",
                        "show_as_standalone": True,
                        "sort_priority": 40,
                    },
                )
            ]
            ctx.log(
                node_id,
                "NO_DATA_PROCEED",
                {
                    "rectal_bleeding_visible": visible,
                    "rectal_bleeding_new_or_worsening": new_or_worsening,
                    "rectal_bleeding_most_days": most_days,
                    "rectal_bleeding_duration_weeks": duration_weeks,
                },
                out,
            )
            return NodeResult(outputs=out, next_node="FIT_Warning")

        # If visible is True OR partially known, we may need details to classify HRRB.
        missing = []
        if visible is None:
            missing.append("rectal_bleeding_visible")
        if new_or_worsening is None:
            missing.append("rectal_bleeding_new_or_worsening")
        if most_days is None:
            missing.append("rectal_bleeding_most_days")
        if duration_weeks is None:
            missing.append("rectal_bleeding_duration_weeks")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message=(
                    "Need bleeding details to determine high-risk rectal bleeding "
                    "(>2 weeks, most days, new/worsening, visible blood in stool/toilet)."
                ),
                urgency_context=urgency,
                suggested_actions=[Action(code="CAPTURE_BLEEDING", label="Capture rectal bleeding details", urgency=urgency)],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult(outputs=[dr])

        # --- keep the rest of your existing HRRB logic below here ---
        scope_within_2y = _normalize_scope_flag(ctx)
        if scope_within_2y is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["complete_colonoscopy_within_2y"],
                message="Need colonoscopy/lower endoscopy within last 2 years to classify bleeding as unexplained.",
                urgency_context=urgency,
                suggested_actions=[Action(code="CAPTURE_SCOPE_HX", label="Document colonoscopy/lower endoscopy within last 2 years", urgency=urgency)],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"bleeding_data_present": True}, [dr])
            return NodeResult(outputs=[dr])

        bleeding_meets_pattern = bool(visible and new_or_worsening and most_days and (duration_weeks > 2))
        unexplained = (scope_within_2y is False)

        other_alarm_flag = ctx.get("other_alarm_features_with_bleeding")
        urgent_alarm_present = _urgent_alarm_subset(ctx)
        other_alarm_present = bool(other_alarm_flag) if other_alarm_flag is not None else urgent_alarm_present

        if bleeding_meets_pattern and unexplained and (other_alarm_flag is not True) and (urgent_alarm_present is False):
            out = [
                Action(
                    code="HRRB_NEEDS_ALARMS_NOTE",
                    label="Rectal bleeding meets high-risk pattern, but must be accompanied by other alarm features; consider clinician review/override.",
                    urgency=urgency,
                    details={
                        "supported_by": [
                            "Bleeding pattern meets HRRB definition",
                            "Bleeding appears unexplained",
                            "Other alarm features were not identified",
                        ],
                        "bleeding_meets_pattern": True,
                        "unexplained": True,
                        "other_alarm_features_with_bleeding": other_alarm_flag,
                        "urgent_alarm_present": urgent_alarm_present,
                    },
                    override_options={
                        "node": node_id,
                        "field": "high_risk_rectal_bleeding",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={
                        "role": "support",
                        "badge": "info",
                        "show_as_standalone": True,
                        "sort_priority": 40,
                    },
                )
            ]
            ctx.log(node_id, "HRRB_PATTERN_NO_ALARMS", {"scope_within_2y_context_only": scope_within_2y}, out)
            return NodeResult(outputs=out, next_node="FIT_Warning")

        high_risk_rectal_bleeding = bool(bleeding_meets_pattern and unexplained and other_alarm_present)
        high_risk_rectal_bleeding = ctx.apply_override(node_id, "high_risk_rectal_bleeding", high_risk_rectal_bleeding)
        ctx.set("high_risk_rectal_bleeding", high_risk_rectal_bleeding)

        if high_risk_rectal_bleeding:
            stop = Stop(
                reason="High-risk rectal bleeding present → follow HRRB pathway for CRC diagnosis.",
                actions=[Action(
                    code="ROUTE_HRRB",
                    label="Route to High Risk Rectal Bleeding Pathway",
                    urgency=urgency,
                    details={
                        "supported_by": [
                            "Bleeding pattern meets HRRB definition",
                            "Bleeding appears unexplained",
                            "Other alarm features are present",
                        ],
                    },
                    display={
                        "role": "primary_decision",
                        "show_as_standalone": True,
                        "sort_priority": 15,
                    },
                )],
                urgency=urgency,
            )
            ctx.log(node_id, "ROUTE_HRRB", {"high_risk_rectal_bleeding": True}, [stop])
            return NodeResult(outputs=[stop])

        out = [
            Action(
                code="HRRB_NOT_MET",
                label="Rectal bleeding does not meet high-risk definition (as provided).",
                urgency=urgency,
                details={
                    "supported_by": ["Provided bleeding details do not meet the HRRB definition"],
                },
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 40,
                },
            )
        ]
        ctx.log(node_id, "PROCEED", {"high_risk_rectal_bleeding": False}, out)
        return NodeResult(outputs=out, next_node="FIT_Warning")

    def node_fit_warning(ctx: Context) -> NodeResult:
        node_id = "FIT_Warning"
        urgency = ctx.get("urgency")

        # Pathway note: for patients with signs of IDA, FIT should not be done.
        # Non-blocking warning. If they plan FIT, output a caution action.
        fit_planned = ctx.get("fit_ordered_or_planned")
        if fit_planned is True:
            out = [Action(
                code="DO_NOT_ORDER_FIT",
                label="Do NOT order FIT when signs of IDA are present (per pathway note).",
                urgency=urgency,
                details={
                    "supported_by": ["Pathway note states FIT should not be used when signs of IDA are present"],
                },
                display={
                    "role": "advisory",
                    "badge": "warning",
                    "show_as_standalone": True,
                    "sort_priority": 50,
                },
            )]
            ctx.log(node_id, "FIT_WARNING_EMITTED", {"fit_ordered_or_planned": True}, out)
            return NodeResult(outputs=out, next_node="Baseline_Investigation_Freshness")

        # If unknown, do not block; optional reminder
        out = [Action(
            code="FIT_REMINDER",
            label="Reminder: FIT should not be done when signs of IDA are present.",
            urgency=urgency,
            display={
                "role": "advisory",
                "badge": "warning",
                "show_as_standalone": True,
                "sort_priority": 50,
            },
        )]
        ctx.log(node_id, "FIT_REMINDER", {"fit_ordered_or_planned": fit_planned}, out)
        return NodeResult(outputs=out, next_node="Baseline_Investigation_Freshness")

    def node_lab_freshness(ctx: Context) -> NodeResult:
        node_id = "Baseline_Investigation_Freshness"
        urgency = ctx.get("urgency")

        # Pathway: baseline investigations should be within ~8 weeks of referral (CBC, ferritin, TTG required).
        # Non-blocking reminders.
        cbc_fresh = _freshness_flag(ctx.get("cbc_days_ago"), ctx.get("cbc_within_8_weeks"))
        ferritin_fresh = _freshness_flag(ctx.get("ferritin_days_ago"), ctx.get("ferritin_within_8_weeks"))
        ttg_fresh = _freshness_flag(ctx.get("ttg_days_ago"), ctx.get("ttg_within_8_weeks"))

        reminders: List[Action] = []

        if cbc_fresh is False:
            reminders.append(Action(code="UPDATE_CBC", label="CBC/Hb is older than 8 weeks: consider repeating for triage.", urgency=urgency))
        if ferritin_fresh is False:
            reminders.append(Action(code="UPDATE_FERRITIN", label="Ferritin is older than 8 weeks: consider repeating for triage.", urgency=urgency))
        if ttg_fresh is False:
            reminders.append(Action(code="UPDATE_TTG", label="TTG is older than 8 weeks: consider repeating/documenting celiac rule-out for triage.", urgency=urgency))

        # If freshness unknown, just remind (non-blocking)
        if cbc_fresh is None:
            reminders.append(Action(code="CHECK_CBC_DATE", label="Confirm CBC/Hb is within 8 weeks of referral (for triage).", urgency=urgency))
        if ferritin_fresh is None:
            reminders.append(Action(code="CHECK_FERRITIN_DATE", label="Confirm ferritin is within 8 weeks of referral (for triage).", urgency=urgency))
        if ttg_fresh is None and ctx.get("prior_duodenal_biopsy_normal") is not True:
            reminders.append(Action(code="CHECK_TTG_DATE", label="Confirm TTG is within 8 weeks or document exemption (prior biopsy/recent TTG).", urgency=urgency))

        ctx.log(node_id, "REMIND_FRESHNESS", {"cbc_fresh": cbc_fresh, "ferritin_fresh": ferritin_fresh, "ttg_fresh": ttg_fresh}, reminders)
        return NodeResult(outputs=reminders, next_node="Triage_Modifiers")

    def node_triage_modifiers(ctx: Context) -> NodeResult:
        node_id = "Triage_Modifiers"
        urgency = ctx.get("urgency")

        # Pathway lists these as “may influence triage”; we do NOT auto-upgrade urgency.
        actions: List[Action] = []

        age = ctx.get("age")
        if age is not None and age > 40:
            actions.append(Action(
                code="MOD_IDA_ONSET_AGE",
                label="IDA onset age >40 may influence triage.",
                urgency=urgency,
                details={"age": age},
                display={
                    "role": "modifier",
                    "group_under": "ASSIGN_URGENCY",
                    "show_as_standalone": False,
                    "sort_priority": 60,
                },
            ))
        elif age is None:
            actions.append(Action(
                code="CAPTURE_AGE",
                label="Capture patient age (IDA onset age >40 may influence triage).",
                urgency=urgency,
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 65,
                },
            ))

        if ctx.get("family_history_crc_first_degree") is True:
            actions.append(Action(
                code="MOD_FH_CRC",
                label="First-degree family history of CRC may influence triage.",
                urgency=urgency,
                display={
                    "role": "modifier",
                    "group_under": "ASSIGN_URGENCY",
                    "show_as_standalone": False,
                    "sort_priority": 60,
                },
            ))
        elif ctx.get("family_history_crc_first_degree") is None:
            actions.append(Action(
                code="CAPTURE_FH_CRC",
                label="Document first-degree family history of CRC (triage modifier).",
                urgency=urgency,
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 65,
                },
            ))

        if ctx.get("family_history_ibd_first_degree") is True:
            actions.append(Action(
                code="MOD_FH_IBD",
                label="First-degree family history of IBD may influence triage.",
                urgency=urgency,
                display={
                    "role": "modifier",
                    "group_under": "ASSIGN_URGENCY",
                    "show_as_standalone": False,
                    "sort_priority": 60,
                },
            ))
        elif ctx.get("family_history_ibd_first_degree") is None:
            actions.append(Action(
                code="CAPTURE_FH_IBD",
                label="Document first-degree family history of IBD (triage modifier).",
                urgency=urgency,
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 65,
                },
            ))

        if ctx.get("nocturnal_symptoms") is True:
            actions.append(Action(
                code="MOD_NOCTURNAL",
                label="Nocturnal symptoms may influence triage.",
                urgency=urgency,
                display={
                    "role": "modifier",
                    "group_under": "ASSIGN_URGENCY",
                    "show_as_standalone": False,
                    "sort_priority": 60,
                },
            ))
        elif ctx.get("nocturnal_symptoms") is None:
            actions.append(Action(
                code="CAPTURE_NOCTURNAL",
                label="Document nocturnal symptoms (triage modifier).",
                urgency=urgency,
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 65,
                },
            ))

        if ctx.get("evidence_of_gi_bleeding") is True:
            actions.append(Action(
                code="MOD_GI_BLEED",
                label="Evidence of GI bleeding may influence triage.",
                urgency=urgency,
                display={
                    "role": "modifier",
                    "group_under": "ASSIGN_URGENCY",
                    "show_as_standalone": False,
                    "sort_priority": 60,
                },
            ))
        elif ctx.get("evidence_of_gi_bleeding") is None:
            actions.append(Action(
                code="CAPTURE_GI_BLEED",
                label="Document evidence of GI bleeding (triage modifier).",
                urgency=urgency,
                display={
                    "role": "support",
                    "badge": "info",
                    "show_as_standalone": True,
                    "sort_priority": 65,
                },
            ))

        ctx.log(node_id, "MODIFIERS_REPORTED", {"modifiers_present": _triage_modifiers_present(ctx)}, actions)
        return NodeResult(outputs=actions, next_node="Finalize")

    def node_finalize(ctx: Context) -> NodeResult:
        node_id = "Finalize"
        urgency = ctx.get("urgency")

        reminders: List[Action] = []

        # Medication review reminders (non-blocking)
        if ctx.get("anticoagulants") is None:
            reminders.append(Action(code="CAPTURE_ANTICOAG", label="Document anticoagulant use (triage information).", urgency=urgency))
        if ctx.get("antiplatelets") is None:
            reminders.append(Action(code="CAPTURE_ANTIPLATELET", label="Document antiplatelet use (triage information).", urgency=urgency))
        if ctx.get("nsaid_use") is None:
            reminders.append(Action(code="CAPTURE_NSAID", label="Document NSAID use (possible contributor to chronic GI blood loss).", urgency=urgency))

        # Physical exam reminder
        if (ctx.get("progressive_bowel_change") or ctx.get("significant_abdominal_pain")) and ctx.get("rectal_exam_done") is None:
            reminders.append(Action(code="CONSIDER_RECTAL_EXAM", label="Consider/document rectal exam (esp. with bowel habit change or lower abdominal pain).", urgency=urgency))

        # --- NEW: referral decision can be overridden ---
        # Default recommendation is True (refer).
        refer_default = True
        refer_final = ctx.apply_override(node_id, "refer_endoscopy", refer_default)

        # Always output the referral Action, but indicate the "final" decision in details.
        referral_action = Action(
            code="REFER_ENDOSCOPY",
            label="Refer for gastroscopy + colonoscopy per urgency.",
            urgency=urgency,
            details={
                "supported_by": [
                    f"Final triage urgency is {urgency}",
                    "IDA pathway reached final referral step",
                ],
                "recommended_by_system": refer_default,
                "final_decision": refer_final,
            },
            override_options={
                "node": node_id,
                "field": "refer_endoscopy",
                "allowed": [True, False],
                "reason_required": True,
            },
            display={
                "role": "primary_decision",
                "group_under": "ASSIGN_URGENCY",
                "show_as_standalone": False,
                "sort_priority": 70,
            },
        )

        # If clinician overrides to False, stop with a clear reason.
        if refer_final is False:
            stop = Stop(
                reason="Endoscopy referral was overridden by clinician (system recommendation declined).",
                actions=[referral_action] + reminders,
                urgency=urgency,
            )
            ctx.log(
                node_id,
                "STOP_REFERRAL_OVERRIDDEN",
                {"urgency": urgency, "refer_default": refer_default, "refer_final": refer_final},
                [stop],
            )
            return NodeResult(outputs=[stop])

        # Otherwise, normal stop
        stop = Stop(
            reason="IDA pathway complete: proceed with endoscopic evaluation per triage urgency and documented context.",
            actions=[referral_action] + reminders,
            urgency=urgency,
        )
        ctx.log(
            node_id,
            "STOP",
            {"urgency": urgency, "refer_default": refer_default, "refer_final": refer_final},
            [stop],
        )
        return NodeResult(outputs=[stop])
    # =========================
    # Register nodes
    # =========================

    nodes["Confirm_IDA"] = Node("Confirm_IDA", node_confirm_ida)
    nodes["Urgency_Triage"] = Node("Urgency_Triage", node_urgency)
    nodes["Celiac_RuleOut"] = Node("Celiac_RuleOut", node_celiac)
    nodes["Gynecology_Check"] = Node("Gynecology_Check", node_gyne)
    nodes["HighRiskRectalBleeding_Check"] = Node("HighRiskRectalBleeding_Check", node_hrrb)
    nodes["FIT_Warning"] = Node("FIT_Warning", node_fit_warning)
    nodes["Baseline_Investigation_Freshness"] = Node("Baseline_Investigation_Freshness", node_lab_freshness)
    nodes["Triage_Modifiers"] = Node("Triage_Modifiers", node_triage_modifiers)
    nodes["Finalize"] = Node("Finalize", node_finalize)

    # =========================
    # Build and return engine
    # =========================

    return PathwayEngine(
        nodes=nodes,
        start_node="Confirm_IDA",
    )

# ==========================================================
# OPTIONAL: tiny convenience runner (UI can replace this)
# ==========================================================

def run_ida_pathway(patient_data: Dict[str, Any], overrides: Optional[List[Override]] = None):
    engine = ida_build_engine()
    ctx = Context(data=dict(patient_data), overrides=overrides or [])
    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx.overrides