# -*- coding: utf-8 -*-
"""liver_mass_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cX0LGNX1ql17WkRI6Nl5qpPj8Zctf335
"""

"""
========================================================
PATHWAY FILE: Liver Mass
FULL WORKFLOW REDESIGN
========================================================
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current:
            guard += 1
            if guard > 300:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break

            if current not in self.nodes:
                outputs.append(Stop(reason=f"Unknown node: {current}"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# HELPERS
# =========================================================

VALID_LESION_TYPES = {
    "simple_cyst",
    "complex_cyst",
    "hemangioma",
    "fnh",
    "adenoma",
    "indeterminate_suspicious",
    "solid_unspecified",
    "metastatic_disease",
}

SOLID_TYPES = {
    "hemangioma",
    "fnh",
    "adenoma",
    "indeterminate_suspicious",
    "solid_unspecified",
    "metastatic_disease",
}

CYST_TYPES = {"simple_cyst", "complex_cyst"}


def _compute_is_cyst(ctx: Context) -> bool:
    lesion_type = ctx.get("lesion_type")
    return lesion_type in CYST_TYPES


def _compute_is_solid(ctx: Context) -> bool:
    lesion_type = ctx.get("lesion_type")
    return lesion_type in SOLID_TYPES


def _compute_high_risk(ctx: Context) -> Dict[str, Any]:
    chronic_viral_hepatitis = bool(ctx.get("chronic_hepatitis_b")) or bool(ctx.get("chronic_hepatitis_c"))
    result = {
        "history_cirrhosis": bool(ctx.get("history_cirrhosis")),
        "chronic_hepatitis_b": bool(ctx.get("chronic_hepatitis_b")),
        "chronic_hepatitis_c": bool(ctx.get("chronic_hepatitis_c")),
        "chronic_viral_hepatitis": chronic_viral_hepatitis,
        "prior_malignancy_any_location": bool(ctx.get("prior_malignancy_any_location")),
        "clinician_concern_malignancy": bool(ctx.get("clinician_concern_malignancy")),
    }
    result["high_risk"] = any(
        [
            result["history_cirrhosis"],
            result["chronic_viral_hepatitis"],
            result["prior_malignancy_any_location"],
            result["clinician_concern_malignancy"],
        ]
    )
    return result


def _compute_hemorrhage_red_flag(ctx: Context) -> bool:
    return bool(
        _compute_is_solid(ctx)
        and ctx.get("episodic_epigastric_or_ruq_pain")
        and ctx.get("hypotension")
    )


# =========================================================
# ENGINE
# =========================================================

def liver_mass_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # 1. Initial lesion classification
    # -----------------------------------------------------
    def node_entry(ctx: Context):
        node_id = "Initial_Lesion_Classification"

        if ctx.get("liver_lesion_detected") is False:
            stop = Stop(
                reason="No liver lesion documented.",
                actions=[
                    Action(
                        code="NO_LIVER_LESION",
                        label="Liver mass pathway is not applicable because no lesion is documented.",
                    )
                ],
            )
            ctx.log(node_id, "NO_LESION", {}, [stop])
            return NodeResult([stop])

        lesion_type = ctx.get("lesion_type")
        if lesion_type is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["lesion_type"],
                message="Need lesion type to begin liver mass pathway.",
                suggested_actions=[
                    Action(code="CAPTURE_LESION_TYPE", label="Capture lesion type")
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_LESION_TYPE", {}, [dr])
            return NodeResult([dr])

        if lesion_type not in VALID_LESION_TYPES:
            stop = Stop(
                reason="Invalid lesion type supplied.",
                actions=[
                    Action(
                        code="INVALID_LESION_TYPE",
                        label="Lesion type must match a supported pathway category.",
                    )
                ],
            )
            ctx.log(node_id, "INVALID_LESION_TYPE", {"lesion_type": lesion_type}, [stop])
            return NodeResult([stop])

        ctx.set("is_cyst", _compute_is_cyst(ctx))
        ctx.set("is_solid_lesion", _compute_is_solid(ctx))

        actions: List[Output] = [
            Action(
                code="LESION_CLASSIFIED",
                label=f"Liver lesion classified as {lesion_type}.",
                details={
                    "imaging_modality": ctx.get("imaging_modality"),
                    "incidental_vs_symptomatic": ctx.get("incidental_vs_symptomatic"),
                },
            )
        ]

        if ctx.get("lesion_characterization_confident") is False:
            actions.append(
                Action(
                    code="LESION_CHARACTERIZATION_UNCERTAIN",
                    label="Radiology characterization confidence is limited.",
                )
            )

        if ctx.get("radiology_recommends_followup") is True:
            actions.append(
                Action(
                    code="RADIOLOGY_RECOMMENDS_FOLLOWUP",
                    label="Radiology has recommended follow-up or further evaluation.",
                )
            )

        ctx.log(node_id, "LESION_CLASSIFIED", {"lesion_type": lesion_type}, actions)
        return NodeResult(actions, next_node="Red_Flag_Hemorrhage")

    nodes["Initial_Lesion_Classification"] = Node("Initial_Lesion_Classification", node_entry)

    # -----------------------------------------------------
    # 2. Hemorrhage red flag
    # -----------------------------------------------------
    def node_hemorrhage(ctx: Context):
        node_id = "Red_Flag_Hemorrhage"

        hemorrhage_red_flag = _compute_hemorrhage_red_flag(ctx)
        hemorrhage_red_flag = ctx.apply_override(node_id, "hemorrhage_red_flag", hemorrhage_red_flag)
        ctx.set("hemorrhage_red_flag", hemorrhage_red_flag)

        if hemorrhage_red_flag:
            stop = Stop(
                reason="Possible hemorrhage into solid liver mass.",
                urgency="urgent",
                actions=[
                    Action(
                        code="EMERGENT_ED_OR_RAAPID",
                        label="Arrange immediate emergency assessment / ED / urgent specialist access.",
                        urgency="urgent",
                        override_options={
                            "node": node_id,
                            "field": "hemorrhage_red_flag",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                    )
                ],
            )
            ctx.log(node_id, "HEMORRHAGE_RED_FLAG", {}, [stop])
            return NodeResult([stop])

        out = [Action(code="NO_HEMORRHAGE_RED_FLAG", label="No hemorrhage red flag identified.")]
        ctx.log(node_id, "NO_HEMORRHAGE_RED_FLAG", {}, out)

        if ctx.get("is_cyst"):
            return NodeResult(out, next_node="Cyst_Pathway")

        return NodeResult(out, next_node="Solid_Lesion_Risk_Assessment")

    nodes["Red_Flag_Hemorrhage"] = Node("Red_Flag_Hemorrhage", node_hemorrhage)

    # -----------------------------------------------------
    # 3. Cyst pathway
    # -----------------------------------------------------
    def node_cyst(ctx: Context):
        node_id = "Cyst_Pathway"
        lesion_type = ctx.get("lesion_type")
        actions: List[Output] = []

        if lesion_type == "simple_cyst":
            actions.append(Action(code="SIMPLE_CYST_BENIGN", label="Simple cyst is benign."))

            if ctx.get("cyst_size_cm") is not None:
                actions.append(
                    Action(
                        code="CYST_SIZE_RECORDED",
                        label="Cyst size recorded.",
                        details={"cyst_size_cm": ctx.get("cyst_size_cm")},
                    )
                )

            needs_followup = any(
                [
                    bool(ctx.get("symptoms_attributable_to_cyst")),
                    bool(ctx.get("abnormal_liver_enzymes")),
                    bool(ctx.get("radiology_recommends_followup")),
                ]
            )

            if needs_followup:
                actions.append(
                    Action(
                        code="CONSIDER_REPEAT_IMAGING_SIMPLE_CYST",
                        label="Consider repeat imaging or further evaluation because of symptoms, abnormal liver enzymes, or radiology recommendation.",
                    )
                )
            else:
                actions.append(
                    Action(
                        code="NO_FOLLOWUP_SIMPLE_CYST",
                        label="No follow-up required for simple cyst.",
                    )
                )

            stop = Stop(reason="Simple cyst pathway complete.", actions=actions)
            ctx.log(node_id, "SIMPLE_CYST", {}, [stop])
            return NodeResult([stop])

        # complex cyst
        actions.extend(
            [
                Action(
                    code="ORDER_MRI_LIVER_COMPLEX_CYST",
                    label="Order MRI liver (preferred) or triphasic CT for complex cyst.",
                ),
                Action(
                    code="REFER_HPB_COMPLEX_CYST",
                    label="Refer concurrently to HPB surgery for complex cyst.",
                ),
            ]
        )

        if ctx.get("cyst_complex_features_present") is True:
            actions.append(
                Action(
                    code="COMPLEX_CYST_FEATURES_DOCUMENTED",
                    label="Complex cyst features documented.",
                )
            )

        stop = Stop(
            reason="Complex cyst requires further characterization and specialty review.",
            actions=actions,
        )
        ctx.log(node_id, "COMPLEX_CYST", {}, [stop])
        return NodeResult([stop])

    nodes["Cyst_Pathway"] = Node("Cyst_Pathway", node_cyst)

    # -----------------------------------------------------
    # 4. Solid lesion risk assessment
    # -----------------------------------------------------
    def node_solid_risk(ctx: Context):
        node_id = "Solid_Lesion_Risk_Assessment"
        lesion_type = ctx.get("lesion_type")
        risk = _compute_high_risk(ctx)

        high_risk = ctx.apply_override(node_id, "high_risk_malignancy", risk["high_risk"])
        ctx.set("high_risk_malignancy", high_risk)

        actions: List[Output] = [
            Action(
                code="SOLID_LESION_RISK_ASSESSED",
                label="Solid lesion malignancy risk assessed.",
                details=risk,
                override_options={
                    "node": node_id,
                    "field": "high_risk_malignancy",
                    "allowed": [True, False],
                    "reason_required": True,
                },
            )
        ]

        # symptoms
        if ctx.get("unintentional_weight_loss") is True:
            actions.append(Action(code="WEIGHT_LOSS_FLAG", label="Unintentional weight loss documented."))
        if ctx.get("persistent_abdominal_pain") is True:
            actions.append(Action(code="PERSISTENT_PAIN_FLAG", label="Persistent abdominal pain documented."))
        if ctx.get("fever") is True:
            actions.append(Action(code="FEVER_FLAG", label="Fever documented."))
        if ctx.get("early_satiety") is True:
            actions.append(Action(code="EARLY_SATIETY_FLAG", label="Early satiety documented."))

        # labs
        for field_name, code in [
            ("alt", "ALT_RECORDED"),
            ("ast", "AST_RECORDED"),
            ("alp", "ALP_RECORDED"),
            ("bilirubin", "BILIRUBIN_RECORDED"),
            ("afp", "AFP_RECORDED"),
        ]:
            if ctx.get(field_name) is not None:
                actions.append(
                    Action(
                        code=code,
                        label=f"{field_name.upper()} recorded.",
                        details={field_name: ctx.get(field_name)},
                    )
                )

        # benign named lesions still go to low-risk management branch
        if lesion_type in {"hemangioma", "fnh", "adenoma"}:
            ctx.log(node_id, "BENIGN_SPECIFIC_BRANCH", {"lesion_type": lesion_type, **risk}, actions)
            return NodeResult(actions, next_node="Low_Risk_Solid_Lesion_Management")

        if high_risk:
            ctx.log(node_id, "HIGH_RISK_SOLID_LESION", {"lesion_type": lesion_type, **risk}, actions)
            return NodeResult(actions, next_node="High_Risk_Solid_Lesion_Management")

        ctx.log(node_id, "LOW_RISK_SOLID_LESION", {"lesion_type": lesion_type, **risk}, actions)
        return NodeResult(actions, next_node="Low_Risk_Solid_Lesion_Management")

    nodes["Solid_Lesion_Risk_Assessment"] = Node("Solid_Lesion_Risk_Assessment", node_solid_risk)

    # -----------------------------------------------------
    # 5. High-risk solid lesion management
    # -----------------------------------------------------
    def node_high_risk(ctx: Context):
        node_id = "High_Risk_Solid_Lesion_Management"
        lesion_type = ctx.get("lesion_type")
        risk = _compute_high_risk(ctx)

        actions: List[Output] = [
            Action(
                code="ORDER_HIGH_RISK_LIVER_LABS",
                label="Order CBC, electrolytes, creatinine, ALT, ALP, AST, GGT, INR, bilirubin, AFP, albumin, HB core, HBsAg, HBsAb, and HCV Ab.",
            ),
            Action(
                code="ADVICE_SERVICE_NOTE",
                label="Use urgent or non-urgent specialist advice services as needed to clarify imaging and referral urgency.",
            ),
        ]

        if risk["history_cirrhosis"] or risk["chronic_viral_hepatitis"]:
            actions.extend(
                [
                    Action(
                        code="ORDER_MRI_OR_TRIPHASIC_CT_HIGH_RISK",
                        label="Order MRI liver (preferred) or triphasic CT.",
                    ),
                    Action(
                        code="REFER_HPB_HIGH_RISK",
                        label="Refer to HPB surgery.",
                    ),
                    Action(
                        code="REFER_HEPATOLOGY_CIRRHOSIS_OR_HEPATITIS",
                        label="Refer to hepatology for cirrhosis or chronic viral hepatitis.",
                    ),
                ]
            )

        if risk["prior_malignancy_any_location"]:
            actions.extend(
                [
                    Action(
                        code="ORDER_MRI_OR_CHEST_ABDO_PELVIS_CT_PRIOR_MALIGNANCY",
                        label="Order MRI liver and/or CT chest/abdomen/pelvis as appropriate.",
                    ),
                    Action(
                        code="REFER_PRIOR_ONCOLOGY_TEAM",
                        label="Refer concurrently to prior oncology team.",
                    ),
                ]
            )

            if lesion_type == "metastatic_disease" or ctx.get("metastatic_pattern_present") is True:
                actions.append(
                    Action(
                        code="CONTACT_ONCOLOGY_OR_HPB_METASTATIC_DISEASE",
                        label="Contact oncology or HPB for new metastatic disease; consider early palliative approach if appropriate.",
                    )
                )

        if risk["clinician_concern_malignancy"] and not (
            risk["history_cirrhosis"] or risk["chronic_viral_hepatitis"] or risk["prior_malignancy_any_location"]
        ):
            actions.extend(
                [
                    Action(
                        code="ORDER_MRI_LIVER_CLINICIAN_CONCERN",
                        label="Order MRI liver (preferred) or triphasic CT because of clinician concern.",
                    ),
                    Action(
                        code="REFER_HPB_CLINICIAN_CONCERN",
                        label="Refer to HPB because of clinician concern for malignancy.",
                    ),
                ]
            )

        if ctx.get("advanced_imaging_done") is True:
            actions.append(Action(code="ADVANCED_IMAGING_ALREADY_DONE", label="Advanced imaging already completed."))
        if ctx.get("biopsy_considered") is True:
            actions.append(Action(code="BIOPSY_CONSIDERED", label="Biopsy has been considered/documented."))
        if ctx.get("referred_to_hepatology") is True:
            actions.append(Action(code="HEPATOLOGY_REFERRAL_ALREADY_MADE", label="Hepatology referral already documented."))
        if ctx.get("referred_to_surgery") is True:
            actions.append(Action(code="SURGICAL_REFERRAL_ALREADY_MADE", label="Surgical referral already documented."))
        if ctx.get("urgent_referral_required") is True:
            actions.append(Action(code="URGENT_REFERRAL_FLAG", label="Urgent referral requirement documented."))

        stop = Stop(
            reason="High-risk solid liver lesion requires advanced imaging and specialty management.",
            actions=actions,
        )
        ctx.log(node_id, "HIGH_RISK_MANAGEMENT", {"lesion_type": lesion_type, **risk}, [stop])
        return NodeResult([stop])

    nodes["High_Risk_Solid_Lesion_Management"] = Node("High_Risk_Solid_Lesion_Management", node_high_risk)

    # -----------------------------------------------------
    # 6. Low-risk solid lesion management
    # -----------------------------------------------------
    def node_low_risk(ctx: Context):
        node_id = "Low_Risk_Solid_Lesion_Management"
        lesion_type = ctx.get("lesion_type")
        actions: List[Output] = []

        if lesion_type == "hemangioma":
            actions.append(Action(code="HEMANGIOMA_BENIGN", label="Hemangioma is benign."))

            size_cm = ctx.get("lesion_size_cm")
            symptomatic = bool(ctx.get("possibly_symptomatic"))
            radiology_fu = bool(ctx.get("radiology_recommends_followup"))

            if size_cm is not None:
                actions.append(
                    Action(
                        code="LESION_SIZE_RECORDED",
                        label="Lesion size recorded.",
                        details={"lesion_size_cm": size_cm},
                    )
                )

            if radiology_fu or ((size_cm is not None and size_cm > 5) and symptomatic):
                actions.append(
                    Action(
                        code="REFER_HPB_HEMANGIOMA_EXCEPTION",
                        label="Refer to HPB for hemangioma exception.",
                    )
                )
            else:
                actions.append(
                    Action(
                        code="NO_FOLLOWUP_HEMANGIOMA",
                        label="No follow-up required for typical hemangioma.",
                    )
                )

            stop = Stop(reason="Hemangioma pathway complete.", actions=actions)
            ctx.log(node_id, "HEMANGIOMA", {}, [stop])
            return NodeResult([stop])

        if lesion_type == "fnh":
            definitive_fnh = bool(ctx.get("definitive_fnh"))
            if ctx.get("fnh_uncertain") is True:
                definitive_fnh = False

            if definitive_fnh:
                actions.append(Action(code="FNH_CONFIRMED", label="Definitive FNH identified."))
                if bool(ctx.get("radiology_recommends_followup")):
                    actions.append(
                        Action(
                            code="FOLLOWUP_FNH_RADIOLOGY_RECOMMENDED",
                            label="Follow-up for FNH as recommended by radiology.",
                        )
                    )
                else:
                    actions.append(Action(code="NO_FOLLOWUP_FNH", label="No follow-up required for definitive FNH."))
            else:
                actions.append(Action(code="ORDER_MRI_CONFIRM_FNH", label="Order MRI liver to define suspected FNH."))

            stop = Stop(reason="FNH pathway complete.", actions=actions)
            ctx.log(node_id, "FNH", {}, [stop])
            return NodeResult([stop])

        if lesion_type == "adenoma":
            actions.append(
                Action(
                    code="REFER_HEPATOLOGY_ADENOMA",
                    label="Refer to hepatology for adenoma.",
                    urgency="urgent" if bool(ctx.get("pregnant")) else None,
                )
            )

            if bool(ctx.get("pregnant")):
                actions.append(
                    Action(
                        code="TIMELY_REFERRAL_ADENOMA_PREGNANCY",
                        label="Adenoma in pregnancy requires timely referral.",
                        urgency="urgent",
                    )
                )

            if ctx.get("oral_contraceptive_use") is True:
                actions.append(Action(code="OCP_USE_RECORDED", label="Oral contraceptive use documented."))
            if ctx.get("anabolic_steroid_use") is True:
                actions.append(Action(code="ANABOLIC_STEROID_USE_RECORDED", label="Anabolic steroid use documented."))
            if ctx.get("adenoma_confirmed") is True:
                actions.append(Action(code="ADENOMA_CONFIRMED", label="Adenoma diagnosis confirmed."))

            stop = Stop(
                reason="Adenoma requires hepatology management.",
                actions=actions,
                urgency="urgent" if bool(ctx.get("pregnant")) else None,
            )
            ctx.log(node_id, "ADENOMA", {}, [stop])
            return NodeResult([stop])

        # low-risk indeterminate / solid unspecified
        actions.extend(
            [
                Action(
                    code="ORDER_MRI_LIVER_LOW_RISK_SOLID",
                    label="Order MRI liver (preferred) or triphasic CT for low-risk indeterminate solid lesion.",
                ),
                Action(
                    code="REFER_HPB_LOW_RISK_INDETERMINATE",
                    label="Refer to HPB for indeterminate or suspicious solid lesion.",
                ),
            ]
        )

        if ctx.get("repeat_imaging_planned") is True:
            actions.append(Action(code="REPEAT_IMAGING_PLANNED_RECORDED", label="Repeat imaging plan documented."))

        stop = Stop(
            reason="Low-risk solid lesion still requires characterization and specialty review.",
            actions=actions,
        )
        ctx.log(node_id, "LOW_RISK_INDETERMINATE", {"lesion_type": lesion_type}, [stop])
        return NodeResult([stop])

    nodes["Low_Risk_Solid_Lesion_Management"] = Node("Low_Risk_Solid_Lesion_Management", node_low_risk)

    return PathwayEngine(nodes=nodes, start_node="Initial_Lesion_Classification")


def run_liver_mass_pathway(patient_data: Dict[str, Any], overrides=None):
    engine = liver_mass_build_engine()
    ctx = Context(data=dict(patient_data), overrides=overrides or [])
    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx.overrides