# -*- coding: utf-8 -*-
"""nafld_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190lnj3klpVGrqFF5fDIXTCpZCoYXVrQ5
"""

"""
========================================================
PATHWAY FILE: Non-Alcoholic Fatty Liver Disease (NAFLD)
FULL WORKFLOW REDESIGN
========================================================
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current:
            guard += 1
            if guard > 300:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break

            if current not in self.nodes:
                outputs.append(Stop(reason=f"Unknown node: {current}"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# HELPERS
# =========================================================

def _entry_met(ctx: Context) -> bool:
    return bool(ctx.get("incidental_abnormal_alt")) or bool(ctx.get("incidental_ultrasound_fatty_liver"))


def _compute_significant_alcohol(ctx: Context) -> Optional[bool]:
    sex = ctx.get("sex")
    drinks = ctx.get("average_drinks_per_day")

    if sex is None or drinks is None:
        return None

    if sex == "male":
        return drinks > 2
    if sex == "female":
        return drinks > 1
    return None


def _compute_fib4(ctx: Context) -> Dict[str, Any]:
    age = ctx.get("age")
    ast = ctx.get("ast")
    alt = ctx.get("alt")
    platelets = ctx.get("platelets")

    missing = []
    if age is None:
        missing.append("age")
    if ast is None:
        missing.append("ast")
    if alt is None:
        missing.append("alt")
    if platelets is None:
        missing.append("platelets")

    if missing:
        return {"blocked": True, "missing": missing, "fib4": None}

    if alt <= 0 or platelets <= 0:
        return {"blocked": True, "missing": [], "invalid_values": True, "fib4": None}

    fib4 = (age * ast) / (platelets * (alt ** 0.5))
    return {"blocked": False, "missing": [], "fib4": round(fib4, 3)}


# =========================================================
# ENGINE
# =========================================================

def nafld_build_engine() -> PathwayEngine:
    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # 1. Suspected NAFLD
    # -----------------------------------------------------
    def node_entry(ctx: Context):
        node_id = "Suspected_NAFLD"

        if not _entry_met(ctx):
            stop = Stop(
                reason="NAFLD pathway entry criteria not met.",
                actions=[
                    Action(
                        code="NOT_SUSPECTED_NAFLD",
                        label="Need incidental abnormal ALT and/or incidental ultrasound finding of fatty liver.",
                    )
                ],
            )
            ctx.log(node_id, "ENTRY_NOT_MET", {
                "incidental_abnormal_alt": ctx.get("incidental_abnormal_alt"),
                "incidental_ultrasound_fatty_liver": ctx.get("incidental_ultrasound_fatty_liver"),
            }, [stop])
            return NodeResult([stop])

        alcohol_flag = _compute_significant_alcohol(ctx)
        if alcohol_flag is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=[x for x in ["sex", "average_drinks_per_day"] if ctx.get(x) is None],
                message="Need sex and average drinks/day to determine whether this NAFLD pathway is appropriate.",
                suggested_actions=[
                    Action(code="CAPTURE_ALCOHOL_CONTEXT", label="Capture sex and average alcohol intake")
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_ALCOHOL_CONTEXT", {}, [dr])
            return NodeResult([dr])

        alcohol_flag = ctx.apply_override(node_id, "significant_alcohol_use", alcohol_flag)
        ctx.set("significant_alcohol_use", alcohol_flag)

        if alcohol_flag:
            stop = Stop(
                reason="This pathway is not designed for significant alcohol consumption.",
                actions=[
                    Action(
                        code="SIGNIFICANT_ALCOHOL_STOP",
                        label="Counsel reduction below pathway thresholds, then retest ALT after 6–8 weeks and reassess.",
                        override_options={
                            "node": node_id,
                            "field": "significant_alcohol_use",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                    )
                ],
            )
            ctx.log(node_id, "SIGNIFICANT_ALCOHOL_STOP", {
                "sex": ctx.get("sex"),
                "average_drinks_per_day": ctx.get("average_drinks_per_day"),
            }, [stop])
            return NodeResult([stop])

        actions = [
            Action(
                code="SUSPECTED_NAFLD_ENTRY_MET",
                label="Suspected NAFLD entry criteria met.",
                details={
                    "incidental_abnormal_alt": bool(ctx.get("incidental_abnormal_alt")),
                    "incidental_ultrasound_fatty_liver": bool(ctx.get("incidental_ultrasound_fatty_liver")),
                },
            )
        ]

        if ctx.get("metabolic_risk_factors_present") is True:
            actions.append(
                Action(
                    code="METABOLIC_RISK_FACTORS_SUPPORT_NAFLD",
                    label="Metabolic risk factors support possible NAFLD/MASLD.",
                )
            )

        ctx.log(node_id, "ENTRY_MET", {}, actions)
        return NodeResult(actions, next_node="Persistent_ALT_Check")

    nodes["Suspected_NAFLD"] = Node("Suspected_NAFLD", node_entry)

    # -----------------------------------------------------
    # 2. ALT >2x ULN for 6 months
    # -----------------------------------------------------
    def node_alt_persistence(ctx: Context):
        node_id = "Persistent_ALT_Check"

        persistent = ctx.get("alt_gt_2x_uln_for_6_months")
        if persistent is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["alt_gt_2x_uln_for_6_months"],
                message="Need to know whether ALT has been >2x ULN for 6 months.",
                suggested_actions=[
                    Action(code="CAPTURE_ALT_PERSISTENCE", label="Capture ALT persistence above 2x ULN for 6 months")
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {}, [dr])
            return NodeResult([dr])

        if persistent:
            out = [
                Action(
                    code="DEEPER_RULE_OUT_REQUIRED",
                    label="ALT >2x ULN for 6 months: deeper workup to rule out other causes is required.",
                )
            ]
            ctx.log(node_id, "ALT_PERSISTENT_HIGH", {"alt_gt_2x_uln_for_6_months": True}, out)
            return NodeResult(out, next_node="Rule_Out_Other_Causes")

        out = [
            Action(
                code="NO_DEEPER_RULE_OUT_TRIGGER",
                label="ALT persistence threshold not met; continue pathway evaluation.",
            )
        ]
        ctx.log(node_id, "ALT_NOT_PERSISTENT_HIGH", {"alt_gt_2x_uln_for_6_months": False}, out)
        return NodeResult(out, next_node="Rule_Out_Other_Causes")

    nodes["Persistent_ALT_Check"] = Node("Persistent_ALT_Check", node_alt_persistence)

    # -----------------------------------------------------
    # 3. Rule out other causes
    # -----------------------------------------------------
    def node_rule_out(ctx: Context):
        node_id = "Rule_Out_Other_Causes"

        other_causes_excluded = ctx.get("other_causes_excluded")
        if other_causes_excluded is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["other_causes_excluded"],
                message="Need to know whether other causes of liver disease have been excluded.",
                suggested_actions=[
                    Action(code="CAPTURE_OTHER_CAUSES_EXCLUDED", label="Document whether alternative causes have been excluded")
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {}, [dr])
            return NodeResult([dr])

        actions: List[Output] = []

        # Stepwise support outputs
        if ctx.get("hepatitis_b_surface_antigen_done") is False:
            actions.append(Action(code="CHECK_HBSAG", label="Complete HBsAg testing."))
        if ctx.get("hepatitis_c_antibody_done") is False:
            actions.append(Action(code="CHECK_ANTI_HCV", label="Complete anti-HCV testing."))
        if ctx.get("autoimmune_markers_done") is False:
            actions.append(Action(code="CHECK_AUTOIMMUNE_MARKERS", label="Complete ANA / anti-smooth muscle / immunoglobulin workup if indicated."))
        if ctx.get("iron_studies_done") is False:
            actions.append(Action(code="CHECK_IRON_STUDIES", label="Complete fasting ferritin and iron/TIBC studies."))
        if ctx.get("celiac_screen_done") is False:
            actions.append(Action(code="CHECK_CELIAC_SCREEN", label="Complete celiac disease screen."))
        if ctx.get("age") is not None and ctx.get("age") < 30 and ctx.get("ceruloplasmin_done") is False:
            actions.append(Action(code="CHECK_CERULOPLASMIN", label="Complete ceruloplasmin because age is under 30."))

        if other_causes_excluded is False:
            stop = Stop(
                reason="Alternative liver disease has not been excluded or a competing diagnosis remains active.",
                actions=actions + [
                    Action(
                        code="TREAT_OR_REFER_NON_NAFLD_CAUSE",
                        label="Treat or refer based on workup suggesting a non-NAFLD diagnosis.",
                    )
                ],
            )
            ctx.log(node_id, "OTHER_CAUSES_NOT_EXCLUDED", {"other_causes_excluded": False}, [stop])
            return NodeResult([stop])

        out = actions + [
            Action(
                code="OTHER_CAUSES_EXCLUDED",
                label="Alternative causes of liver disease have been investigated and excluded.",
            )
        ]
        ctx.log(node_id, "OTHER_CAUSES_EXCLUDED", {"other_causes_excluded": True}, out)
        return NodeResult(out, next_node="Medication_And_Lifestyle_Review")

    nodes["Rule_Out_Other_Causes"] = Node("Rule_Out_Other_Causes", node_rule_out)

    # -----------------------------------------------------
    # 4. Medication and lifestyle review
    # -----------------------------------------------------
    def node_med_lifestyle(ctx: Context):
        node_id = "Medication_And_Lifestyle_Review"

        actions: List[Output] = [
            Action(
                code="COMPLETE_MEDICATION_REVIEW",
                label="Complete medication review including herbals and supplements; stop or modify offending agents if possible.",
            ),
            Action(
                code="REPEAT_LIVER_TESTS_3_TO_6_MONTHS",
                label="Repeat liver function tests after 3–6 months if contributors are modified.",
            ),
            Action(
                code="REVIEW_AND_ADDRESS_ALCOHOL_USE",
                label="Review and address alcohol use.",
            ),
        ]

        if ctx.get("hepatotoxic_medications_present") is True:
            actions.append(Action(code="HEPATOTOXIC_MEDICATION_FLAG", label="Potential hepatotoxic medications/products documented."))
        if ctx.get("physical_inactivity") is True:
            actions.append(Action(code="PHYSICAL_INACTIVITY_FLAG", label="Physical inactivity documented."))
        if ctx.get("diet_high_risk") is True:
            actions.append(Action(code="HIGH_RISK_DIET_FLAG", label="High-risk diet documented."))

        ctx.log(node_id, "MED_LIFESTYLE_REVIEW_EMITTED", {}, actions)
        return NodeResult(actions, next_node="Baseline_Investigations")

    nodes["Medication_And_Lifestyle_Review"] = Node("Medication_And_Lifestyle_Review", node_med_lifestyle)

    # -----------------------------------------------------
    # 5. Baseline investigations
    # -----------------------------------------------------
    def node_baseline(ctx: Context):
        node_id = "Baseline_Investigations"

        complete = ctx.get("baseline_investigations_complete")
        if complete is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["baseline_investigations_complete"],
                message="Need to know whether baseline investigations are complete.",
                suggested_actions=[
                    Action(code="CAPTURE_BASELINE_INVESTIGATIONS", label="Document whether baseline investigations are complete")
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {}, [dr])
            return NodeResult([dr])

        actions: List[Output] = []

        if complete is False:
            actions.append(
                Action(
                    code="COMPLETE_BASELINE_INVESTIGATIONS",
                    label="Complete baseline investigations: ALT, AST, ALP, GGT, CBC with platelets, HbA1C, lipid profile, viral hepatitis screening, and other pathway-directed tests.",
                )
            )
            ctx.log(node_id, "BASELINE_INCOMPLETE", {}, actions)
            return NodeResult(actions, next_node="NAFLD_Diagnosis")

        actions.append(Action(code="BASELINE_INVESTIGATIONS_COMPLETE", label="Baseline investigations complete."))

        if ctx.get("cirrhosis_suspected") is True:
            actions.append(Action(code="CHECK_INR_BILIRUBIN_ALBUMIN", label="Because cirrhosis is suspected, check INR, bilirubin, and albumin."))

        if ctx.get("alp") is not None:
            actions.append(Action(code="ALP_RECORDED", label="ALP recorded.", details={"alp": ctx.get("alp")}))
        if ctx.get("ggt") is not None:
            actions.append(Action(code="GGT_RECORDED", label="GGT recorded.", details={"ggt": ctx.get("ggt")}))
        if ctx.get("hba1c") is not None:
            actions.append(Action(code="HBA1C_RECORDED", label="HbA1C recorded.", details={"hba1c": ctx.get("hba1c")}))
        if ctx.get("lipid_profile_done") is True:
            actions.append(Action(code="LIPID_PROFILE_RECORDED", label="Lipid profile completed."))

        ctx.log(node_id, "BASELINE_COMPLETE", {"baseline_investigations_complete": True}, actions)
        return NodeResult(actions, next_node="NAFLD_Diagnosis")

    nodes["Baseline_Investigations"] = Node("Baseline_Investigations", node_baseline)

    # -----------------------------------------------------
    # 6. Diagnosis
    # -----------------------------------------------------
    def node_diagnosis(ctx: Context):
        node_id = "NAFLD_Diagnosis"

        nafld_diagnosed = bool(_entry_met(ctx) and ctx.get("other_causes_excluded") is True)
        nafld_diagnosed = ctx.apply_override(node_id, "nafld_diagnosed", nafld_diagnosed)
        ctx.set("nafld_diagnosed", nafld_diagnosed)

        if not nafld_diagnosed:
            stop = Stop(
                reason="NAFLD not established.",
                actions=[
                    Action(
                        code="NAFLD_NOT_DIAGNOSED",
                        label="NAFLD is a diagnosis of exclusion and is not established on current data.",
                        override_options={
                            "node": node_id,
                            "field": "nafld_diagnosed",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                    )
                ],
            )
            ctx.log(node_id, "NAFLD_NOT_DIAGNOSED", {}, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="NAFLD_DIAGNOSED",
                label="NAFLD diagnosed/suspected by exclusion.",
                override_options={
                    "node": node_id,
                    "field": "nafld_diagnosed",
                    "allowed": [True, False],
                    "reason_required": True,
                },
            )
        ]
        ctx.log(node_id, "NAFLD_DIAGNOSED", {}, out)
        return NodeResult(out, next_node="FIB4_Assessment")

    nodes["NAFLD_Diagnosis"] = Node("NAFLD_Diagnosis", node_diagnosis)

    # -----------------------------------------------------
    # 7. FIB-4
    # -----------------------------------------------------
    def node_fib4(ctx: Context):
        node_id = "FIB4_Assessment"

        result = _compute_fib4(ctx)
        if result["blocked"]:
            if result.get("invalid_values"):
                stop = Stop(
                    reason="Invalid values supplied for FIB-4 calculation.",
                    actions=[
                        Action(code="INVALID_FIB4_INPUTS", label="Age, AST, ALT, and platelets must support a valid FIB-4 calculation.")
                    ],
                )
                ctx.log(node_id, "INVALID_VALUES", {}, [stop])
                return NodeResult([stop])

            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=result["missing"],
                message="Need age, AST, ALT, and platelets to calculate FIB-4.",
                suggested_actions=[
                    Action(code="CAPTURE_FIB4_INPUTS", label="Capture age, AST, ALT, and platelets")
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": result["missing"]}, [dr])
            return NodeResult([dr])

        fib4 = result["fib4"]
        ctx.set("fib4", fib4)
        ctx.set("fib4_low_risk", fib4 < 1.30)
        ctx.set("fib4_high_risk", fib4 >= 1.30)

        actions: List[Output] = [
            Action(
                code="FIB4_CALCULATED",
                label=f"FIB-4 calculated: {fib4}",
                details={"fib4": fib4},
            )
        ]

        if fib4 >= 1.30:
            stop = Stop(
                reason="FIB-4 indicates indeterminate/high risk of liver fibrosis.",
                actions=actions + [
                    Action(
                        code="REFER_LIVER_DISEASE_SPECIALIST",
                        label="Refer to a specialist trained in management of liver disease.",
                    )
                ],
            )
            ctx.log(node_id, "HIGH_RISK_FIB4", {"fib4": fib4}, [stop])
            return NodeResult([stop])

        ctx.log(node_id, "LOW_RISK_FIB4", {"fib4": fib4}, actions)
        return NodeResult(actions, next_node="Low_Risk_Medical_Home")

    nodes["FIB4_Assessment"] = Node("FIB4_Assessment", node_fib4)

    # -----------------------------------------------------
    # 8. Low-risk medical home
    # -----------------------------------------------------
    def node_low_risk(ctx: Context):
        node_id = "Low_Risk_Medical_Home"

        actions: List[Output] = [
            Action(code="PHYSICAL_ACTIVITY_COUNSELLING", label="Encourage 20+ minutes of physical activity daily, aiming for 150 min/week."),
            Action(code="DIET_WEIGHT_LOSS_COUNSELLING", label="Encourage higher fibre, lower refined starches/added sugars/saturated fats, and weight loss if needed."),
            Action(code="SCREEN_AND_OPTIMIZE_CARDIOMETABOLIC_RISK", label="Screen for diabetes, hypertension, and hyperlipidemia; optimize treatment."),
            Action(code="ENCOURAGE_SMOKING_CESSATION", label="Encourage smoking cessation."),
            Action(code="LIMIT_ALCOHOL_INTAKE", label="Advise limiting alcohol intake."),
            Action(code="CONSIDER_HEP_A_B_IMMUNIZATION", label="Consider hepatitis A and B immunization."),
            Action(code="RECALCULATE_FIB4_2_TO_3_YEARS", label="Recalculate FIB-4 every 2–3 years using ALT, AST, and platelets."),
        ]

        # richer workflow outputs
        if ctx.get("exercise_counselled") is True:
            actions.append(Action(code="EXERCISE_COUNSELLING_DOCUMENTED", label="Exercise counselling documented."))
        if ctx.get("diet_counselled") is True:
            actions.append(Action(code="DIET_COUNSELLING_DOCUMENTED", label="Diet counselling documented."))
        if ctx.get("weight_loss_goal_set") is True:
            actions.append(Action(code="WEIGHT_LOSS_GOAL_DOCUMENTED", label="Weight loss goal documented."))
        if ctx.get("smoking_status") is not None:
            actions.append(Action(code="SMOKING_STATUS_RECORDED", label="Smoking status recorded.", details={"smoking_status": ctx.get("smoking_status")}))
        if ctx.get("alcohol_reduction_counselled") is True:
            actions.append(Action(code="ALCOHOL_COUNSELLING_DOCUMENTED", label="Alcohol counselling documented."))
        if ctx.get("hep_a_vaccinated") is True:
            actions.append(Action(code="HEP_A_STATUS_RECORDED", label="Hepatitis A immunization documented."))
        if ctx.get("hep_b_vaccinated") is True:
            actions.append(Action(code="HEP_B_STATUS_RECORDED", label="Hepatitis B immunization documented."))
        if ctx.get("fib4_recheck_interval_years") is not None:
            actions.append(Action(code="FIB4_RECHECK_INTERVAL_DOCUMENTED", label="FIB-4 recheck interval documented.", details={"fib4_recheck_interval_years": ctx.get("fib4_recheck_interval_years")}))
        if ctx.get("follow_up_plan_documented") is True:
            actions.append(Action(code="FOLLOWUP_PLAN_DOCUMENTED", label="Follow-up plan documented."))

        stop = Stop(
            reason="Low-risk NAFLD: continue care within the Patient Medical Home.",
            actions=actions,
        )
        ctx.log(node_id, "LOW_RISK_MEDICAL_HOME", {}, [stop])
        return NodeResult([stop])

    nodes["Low_Risk_Medical_Home"] = Node("Low_Risk_Medical_Home", node_low_risk)

    return PathwayEngine(nodes=nodes, start_node="Suspected_NAFLD")


def run_nafld_pathway(patient_data: Dict[str, Any], overrides=None):
    engine = nafld_build_engine()
    ctx = Context(data=dict(patient_data), overrides=overrides or [])
    outputs = engine.run(ctx)
    return outputs, ctx.logs, ctx.overrides