# -*- coding: utf-8 -*-
"""chronic_diarrhea_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11las7odDC2EDzZaf5FYcq9hTwy0IGl-v
"""

"""
========================================================
PATHWAY FILE: Chronic Diarrhea
========================================================

Design goals
- Same architecture as other pathway engines
- Progressive gating where appropriate
- UI-friendly outputs: Action / DataRequest / Stop
- Audit log support
- Override capability
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Callable
from datetime import datetime, timezone


# =========================================================
# OUTPUT TYPES
# =========================================================

@dataclass
class Action:
    code: str
    label: str
    urgency: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)
    override_options: Optional[Dict[str, Any]] = None
    display: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DataRequest:
    blocking_node: str
    missing_fields: List[str]
    message: str
    urgency_context: Optional[str] = None
    suggested_actions: List[Action] = field(default_factory=list)


@dataclass
class Stop:
    reason: str
    actions: List[Action] = field(default_factory=list)
    urgency: Optional[str] = None


Output = Action | DataRequest | Stop


# =========================================================
# DECISION LOG
# =========================================================

@dataclass
class DecisionLog:
    node: str
    decision: str
    used_inputs: Dict[str, Any]
    outputs: List[Dict[str, Any]]
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Override:
    target_node: str
    field: str
    old_value: Any
    new_value: Any
    reason: str
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# =========================================================
# CONTEXT
# =========================================================

@dataclass
class Context:
    data: Dict[str, Any]
    logs: List[DecisionLog] = field(default_factory=list)
    overrides: List[Override] = field(default_factory=list)

    def get(self, key, default=None):
        return self.data.get(key, default)

    def set(self, key, value):
        self.data[key] = value

    def apply_override(self, node, field, value):
        for o in reversed(self.overrides):
            if o.target_node == node and o.field == field:
                return o.new_value
        return value

    def log(self, node, decision, inputs, outputs):
        self.logs.append(
            DecisionLog(
                node=node,
                decision=decision,
                used_inputs=inputs,
                outputs=[{"type": type(o).__name__} for o in outputs],
            )
        )


# =========================================================
# ENGINE CORE
# =========================================================

@dataclass
class NodeResult:
    outputs: List[Output]
    next_node: Optional[str] = None


NodeFn = Callable[[Context], NodeResult]


@dataclass
class Node:
    node_id: str
    fn: NodeFn


class PathwayEngine:
    def __init__(self, nodes: Dict[str, Node], start_node: str):
        self.nodes = nodes
        self.start_node = start_node

    def run(self, ctx: Context) -> List[Output]:
        outputs: List[Output] = []
        current = self.start_node
        guard = 0

        while current:
            guard += 1
            if guard > 250:
                outputs.append(Stop(reason="Safety stop: possible infinite loop"))
                break

            result = self.nodes[current].fn(ctx)
            outputs.extend(result.outputs)

            if any(isinstance(o, (Stop, DataRequest)) for o in result.outputs):
                break

            current = result.next_node

        return outputs


# =========================================================
# CHRONIC DIARRHEA PATHWAY IMPLEMENTATION
# =========================================================

def chronic_diarrhea_build_engine() -> PathwayEngine:

    nodes: Dict[str, Node] = {}

    # -----------------------------------------------------
    # Node 1 – Suspected Chronic Diarrhea
    # -----------------------------------------------------
    def node_suspected_diarrhea(ctx: Context):

        node_id = "Suspected_Chronic_Diarrhea"

        stools_per_day = ctx.get("loose_watery_stools_per_day")
        duration_weeks = ctx.get("symptom_duration_weeks")

        missing = []
        if stools_per_day is None:
            missing.append("loose_watery_stools_per_day")
        if duration_weeks is None:
            missing.append("symptom_duration_weeks")

        if missing:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=missing,
                message="Need stool frequency and duration to determine whether chronic diarrhea pathway applies.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_DIARRHEA_ENTRY_CRITERIA",
                        label="Capture loose/watery stools per day and symptom duration",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": missing}, [dr])
            return NodeResult([dr])

        suspected = (stools_per_day >= 3) and (duration_weeks >= 4)
        suspected = ctx.apply_override(node_id, "suspected_chronic_diarrhea", suspected)
        ctx.set("suspected_chronic_diarrhea", suspected)

        if not suspected:
            stop = Stop(
                reason="Chronic diarrhea pathway entry criteria not met.",
                actions=[
                    Action(
                        code="NOT_CHRONIC_DIARRHEA",
                        label="Does not meet chronic diarrhea entry criteria.",
                        details={
                            "supported_by": [
                                f"Loose/watery stools per day: {stools_per_day}",
                                f"Symptom duration weeks: {duration_weeks}",
                            ]
                        },
                        override_options={
                            "node": node_id,
                            "field": "suspected_chronic_diarrhea",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
                    )
                ],
            )
            ctx.log(node_id, "ENTRY_CRITERIA_NOT_MET", {"stools_per_day": stools_per_day, "duration_weeks": duration_weeks}, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="CHRONIC_DIARRHEA_ENTRY_MET",
                label="Chronic diarrhea entry criteria met.",
                details={
                    "supported_by": [
                        f"Loose/watery stools per day: {stools_per_day} (>=3)",
                        f"Symptom duration weeks: {duration_weeks} (>=4)",
                    ]
                },
                override_options={
                    "node": node_id,
                    "field": "suspected_chronic_diarrhea",
                    "allowed": [True, False],
                    "reason_required": True,
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 10},
            )
        ]
        ctx.log(node_id, "ENTRY_CRITERIA_MET", {"stools_per_day": stools_per_day, "duration_weeks": duration_weeks}, out)
        return NodeResult(out, next_node="Alarm_Features")

    nodes["Suspected_Chronic_Diarrhea"] = Node("Suspected_Chronic_Diarrhea", node_suspected_diarrhea)

    # -----------------------------------------------------
    # Node 2 – Alarm Features
    # -----------------------------------------------------
    def node_alarm(ctx: Context):

        node_id = "Alarm_Features"

        fh_ibd = bool(ctx.get("family_history_ibd_first_degree"))
        fh_crc = bool(ctx.get("family_history_crc_first_degree"))
        onset_after_50 = bool(ctx.get("symptom_onset_after_age_50"))
        nocturnal = bool(ctx.get("nocturnal_symptoms"))
        incontinence = bool(ctx.get("significant_incontinence"))
        visible_blood = bool(ctx.get("visible_blood_in_stool"))
        ida = bool(ctx.get("iron_deficiency_anemia_present"))

        weight_loss_pct = ctx.get("unintended_weight_loss_percent_6_to_12_months")
        weight_loss_alarm = (weight_loss_pct is not None and weight_loss_pct > 5)

        alarm_present = any([
            fh_ibd,
            fh_crc,
            onset_after_50,
            weight_loss_alarm,
            nocturnal,
            incontinence,
            visible_blood,
            ida,
        ])
        alarm_present = ctx.apply_override(node_id, "alarm_features_present", alarm_present)
        ctx.set("alarm_features_present", alarm_present)

        if alarm_present:
            stop = Stop(
                reason="Alarm features present – refer for consultation/endoscopy.",
                urgency="urgent",
                actions=[
                    Action(
                        code="URGENT_ENDOSCOPY_REFERRAL",
                        label="Urgent referral for consultation/endoscopy",
                        urgency="urgent",
                        details={
                            "supported_by": [
                                "At least one chronic diarrhea alarm feature is present"
                            ],
                            "family_history_ibd_first_degree": fh_ibd,
                            "family_history_crc_first_degree": fh_crc,
                            "symptom_onset_after_age_50": onset_after_50,
                            "weight_loss_alarm": weight_loss_alarm,
                            "nocturnal_symptoms": nocturnal,
                            "significant_incontinence": incontinence,
                            "visible_blood_in_stool": visible_blood,
                            "iron_deficiency_anemia_present": ida,
                        },
                        override_options={
                            "node": node_id,
                            "field": "alarm_features_present",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 5},
                    )
                ],
            )
            ctx.log(node_id, "ALARM_FEATURES_PRESENT", {
                "family_history_ibd_first_degree": fh_ibd,
                "family_history_crc_first_degree": fh_crc,
                "symptom_onset_after_age_50": onset_after_50,
                "weight_loss_alarm": weight_loss_alarm,
                "nocturnal_symptoms": nocturnal,
                "significant_incontinence": incontinence,
                "visible_blood_in_stool": visible_blood,
                "iron_deficiency_anemia_present": ida,
            }, [stop])
            return NodeResult([stop])

        out = [
            Action(
                code="NO_ALARM_FEATURES",
                label="No alarm features present.",
                details={"supported_by": ["No chronic diarrhea alarm features identified"]},
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 12},
            )
        ]
        ctx.log(node_id, "NO_ALARM_FEATURES", {}, out)
        return NodeResult(out, next_node="Baseline_Investigations")

    nodes["Alarm_Features"] = Node("Alarm_Features", node_alarm)

    # -----------------------------------------------------
    # Node 3 – Baseline Investigations (warnings only)
    # -----------------------------------------------------
    def node_baseline(ctx: Context):

        node_id = "Baseline_Investigations"
        actions: List[Output] = []

        # Blood
        if ctx.get("cbc_done") is not True:
            actions.append(Action(code="CONSIDER_CBC", label="Consider CBC.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))
        if ctx.get("electrolytes_done") is not True:
            actions.append(Action(code="CONSIDER_ELECTROLYTES", label="Consider electrolytes.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))
        if ctx.get("ferritin_done") is not True:
            actions.append(Action(code="CONSIDER_FERRITIN", label="Consider ferritin.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))
        if ctx.get("crp_done") is not True:
            actions.append(Action(code="CONSIDER_CRP", label="Consider CRP.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))
        if ctx.get("celiac_screen_done") is not True:
            actions.append(Action(code="CONSIDER_CELIAC_SCREEN", label="Consider celiac disease screen.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))

        # Stool
        if ctx.get("c_diff_done") is not True:
            actions.append(Action(code="CONSIDER_C_DIFF", label="Consider stool C. difficile testing.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))
        if ctx.get("ova_parasites_done") is not True:
            actions.append(Action(code="CONSIDER_OVA_PARASITES", label="Consider stool ova and parasites.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 20}))

        # FIT warning
        if ctx.get("fit_ordered_or_planned") is True:
            actions.append(Action(
                code="DO_NOT_ORDER_FIT_CHRONIC_DIARRHEA",
                label="Do NOT order FIT for investigation of chronic diarrhea symptoms.",
                details={"supported_by": ["FIT is not validated for investigation of chronic diarrhea symptoms"]},
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 21},
            ))

        # Positive celiac -> refer
        if ctx.get("celiac_screen_positive") is True:
            stop = Stop(
                reason="Positive celiac disease screen – refer for consultation/endoscopy.",
                actions=[
                    Action(
                        code="REFER_POSITIVE_CELIAC",
                        label="Referral for positive celiac disease screen",
                        details={"supported_by": ["Positive celiac disease screen identified"]},
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 6},
                    )
                ],
            )
            ctx.log(node_id, "POSITIVE_CELIAC_SCREEN", {"celiac_screen_positive": True}, actions + [stop])
            return NodeResult(actions + [stop])

        ctx.log(node_id, "BASELINE_INVESTIGATIONS_REVIEWED", {}, actions)
        return NodeResult(actions, next_node="Optimize_Secondary_Causes")

    nodes["Baseline_Investigations"] = Node("Baseline_Investigations", node_baseline)

    # -----------------------------------------------------
    # Node 4 – Optimize Secondary Causes
    # -----------------------------------------------------
    def node_secondary_causes(ctx: Context):

        node_id = "Optimize_Secondary_Causes"
        actions: List[Action] = []

        if ctx.get("medication_review_done") is not True:
            actions.append(Action(code="REVIEW_MEDICATIONS", label="Review medications and optimize or discontinue culprit medications.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30}))
        if ctx.get("underlying_conditions_reviewed") is not True:
            actions.append(Action(code="REVIEW_UNDERLYING_CONDITIONS", label="Review and optimize underlying medical conditions.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30}))
        if ctx.get("history_of_cholecystectomy") is True:
            actions.append(Action(code="CONSIDER_BAD_POST_CHOLE", label="History of cholecystectomy may support bile acid diarrhea.", display={"role": "modifier", "group_under": "ALTERNATIVE_DIAGNOSIS", "show_as_standalone": False, "sort_priority": 60}))
        if ctx.get("history_of_bariatric_surgery") is True:
            actions.append(Action(code="CONSIDER_POST_BARIATRIC_CAUSE", label="History of bariatric surgery may contribute to chronic diarrhea.", display={"role": "modifier", "group_under": "ALTERNATIVE_DIAGNOSIS", "show_as_standalone": False, "sort_priority": 60}))
        if ctx.get("history_of_covid19") is True:
            actions.append(Action(code="CONSIDER_POST_COVID_CONTEXT", label="History of COVID-19 may be relevant context.", display={"role": "modifier", "group_under": "ALTERNATIVE_DIAGNOSIS", "show_as_standalone": False, "sort_priority": 60}))
        if ctx.get("dietary_trigger_review_done") is not True:
            actions.append(Action(code="REVIEW_DIETARY_TRIGGERS", label="Review common dietary triggers such as sugar alcohols, lactose, fructose, caffeine, alcohol, and gluten/wheat.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30}))

        if not actions:
            actions = [
                Action(
                    code="SECONDARY_CAUSES_REVIEWED",
                    label="Secondary causes reviewed and optimized.",
                    details={"supported_by": ["Medication, medical history, and dietary triggers reviewed"]},
                    display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 30},
                )
            ]

        ctx.log(node_id, "SECONDARY_CAUSES_REVIEWED", {}, actions)
        return NodeResult(actions, next_node="General_Management")

    nodes["Optimize_Secondary_Causes"] = Node("Optimize_Secondary_Causes", node_secondary_causes)

    # -----------------------------------------------------
    # Node 5 – General Management
    # -----------------------------------------------------
    def node_general_management(ctx: Context):

        node_id = "General_Management"

        out = [
            Action(
                code="GENERAL_DIARRHEA_MANAGEMENT",
                label="General principles for treatment and management of chronic diarrhea.",
                details={
                    "supported_by": ["General management recommended for chronic diarrhea"],
                    "options": [
                        "education on normal stool form and bowel movement frequency",
                        "patient reassurance and management of expectations",
                        "modify diet, remove trigger foods, and space small meals throughout the day",
                        "soluble fibre supplementation and ensure adequate water intake",
                        "lifestyle modification including physical activity and psychological therapy",
                    ],
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 35},
            )
        ]

        ctx.log(node_id, "GENERAL_MANAGEMENT_EMITTED", {}, out)
        return NodeResult(out, next_node="Pharmacologic_Options")

    nodes["General_Management"] = Node("General_Management", node_general_management)

    # -----------------------------------------------------
    # Node 6 – Pharmacologic Options
    # -----------------------------------------------------
    def node_pharmacologic(ctx: Context):

        node_id = "Pharmacologic_Options"

        out = [
            Action(
                code="PHARMACOLOGIC_OPTIONS_CHRONIC_DIARRHEA",
                label="Pharmacologic options for treating chronic diarrhea.",
                details={
                    "supported_by": ["Pharmacologic options may be used when dietary and lifestyle measures are insufficient"],
                    "options": [
                        "anti-diarrheals / anti-motility agents (loperamide, diphenoxylate-atropine)",
                        "tricyclic antidepressants (TCA)",
                        "bile acid sequestrants",
                        "antibiotics (rifaximin)",
                    ],
                },
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 40},
            )
        ]

        ctx.log(node_id, "PHARMACOLOGIC_OPTIONS_EMITTED", {}, out)
        return NodeResult(out, next_node="Alternative_Diagnoses")

    nodes["Pharmacologic_Options"] = Node("Pharmacologic_Options", node_pharmacologic)

    # -----------------------------------------------------
    # Node 7 – Alternative Diagnoses / IBS / Calprotectin
    # -----------------------------------------------------
    def node_alternatives(ctx: Context):

        node_id = "Alternative_Diagnoses"
        actions: List[Output] = []

        # IBS soft/late routing
        ibs_suspected = bool(ctx.get("predominant_pain_or_bloating")) or bool(ctx.get("suspected_ibsd"))
        ibs_suspected = ctx.apply_override(node_id, "ibs_suspected", ibs_suspected)
        ctx.set("ibs_suspected", ibs_suspected)

        if ibs_suspected:
            stop = Stop(
                reason="IBS suspected as an alternative diagnosis – follow IBS pathway.",
                actions=[
                    Action(
                        code="ROUTE_IBS_PATHWAY",
                        label="Route to suspected IBS pathway",
                        details={"supported_by": ["Predominant pain and/or bloating or IBS-D suspicion identified"]},
                        override_options={
                            "node": node_id,
                            "field": "ibs_suspected",
                            "allowed": [True, False],
                            "reason_required": True,
                        },
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 7},
                    )
                ],
            )
            ctx.log(node_id, "ROUTE_IBS", {"ibs_suspected": ibs_suspected}, [stop])
            return NodeResult([stop])

        # Alternative diagnoses to consider
        if ctx.get("suspect_microscopic_colitis") is True:
            actions.append(Action(code="CONSIDER_MICROSCOPIC_COLITIS", label="Consider microscopic colitis.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))
        if ctx.get("suspect_bad") is True or ctx.get("history_of_cholecystectomy") is True:
            actions.append(Action(code="CONSIDER_BAD", label="Consider bile acid induced diarrhea (BAD).", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))
        if ctx.get("sibo_risk_factor_present") is True:
            actions.append(Action(code="CONSIDER_SIBO", label="Consider SIBO only if risk factors are present.", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))
        if ctx.get("known_pancreatic_disease") is True:
            actions.append(Action(code="CONSIDER_PEI", label="Consider pancreatic exocrine insufficiency (PEI).", display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 45}))

        # Calprotectin logic only if high suspicion of IBD
        high_suspicion_ibd = ctx.get("high_suspicion_ibd")
        if high_suspicion_ibd is None:
            actions.append(Action(
                code="CAPTURE_HIGH_SUSPICION_IBD",
                label="Document whether there is high clinical suspicion of IBD.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 46},
            ))
            ctx.log(node_id, "ALTERNATIVES_REVIEWED", {"high_suspicion_ibd": high_suspicion_ibd}, actions)
            return NodeResult(actions, next_node="Management_Response")

        high_suspicion_ibd = ctx.apply_override(node_id, "high_suspicion_ibd", high_suspicion_ibd)
        ctx.set("high_suspicion_ibd", high_suspicion_ibd)

        if not high_suspicion_ibd:
            ctx.log(node_id, "ALTERNATIVES_REVIEWED", {"high_suspicion_ibd": high_suspicion_ibd}, actions)
            return NodeResult(actions, next_node="Management_Response")

        fcp_done = ctx.get("fecal_calprotectin_done")
        fcp = ctx.get("fecal_calprotectin_ug_g")

        if fcp_done is not True or fcp is None:
            actions.append(Action(
                code="CONSIDER_FECAL_CALPROTECTIN",
                label="Consider fecal calprotectin because there is high clinical suspicion of IBD.",
                display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 47},
            ))
            ctx.log(node_id, "CALPROTECTIN_NOT_AVAILABLE", {"high_suspicion_ibd": high_suspicion_ibd}, actions)
            return NodeResult(actions, next_node="Management_Response")

        if fcp > 120:
            stop = Stop(
                reason="Fecal calprotectin >120 µg/g – refer for consultation/endoscopy.",
                actions=[
                    Action(
                        code="REFER_ELEVATED_FECAL_CALPROTECTIN",
                        label="Referral for elevated fecal calprotectin",
                        details={"supported_by": [f"Fecal calprotectin {fcp} > 120 µg/g"]},
                        display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 8},
                    )
                ],
            )
            ctx.log(node_id, "FECAL_CALPROTECTIN_ELEVATED", {"fecal_calprotectin_ug_g": fcp}, actions + [stop])
            return NodeResult(actions + [stop])

        if 50 <= fcp <= 120:
            actions.append(Action(
                code="REPEAT_FECAL_CALPROTECTIN_WARNING",
                label="Fecal calprotectin 50–120 µg/g: consider repeating in 4–6 weeks if symptoms persist.",
                details={"supported_by": [f"Fecal calprotectin {fcp} is indeterminate"]},
                display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 48},
            ))

        ctx.log(node_id, "ALTERNATIVES_REVIEWED", {"high_suspicion_ibd": high_suspicion_ibd, "fecal_calprotectin_ug_g": fcp}, actions)
        return NodeResult(actions, next_node="Management_Response")

    nodes["Alternative_Diagnoses"] = Node("Alternative_Diagnoses", node_alternatives)

    # -----------------------------------------------------
    # Node 8 – Management Response
    # -----------------------------------------------------
    def node_management_response(ctx: Context):

        node_id = "Management_Response"

        unsat = ctx.get("unsatisfactory_response_to_treatment")
        if unsat is None:
            dr = DataRequest(
                blocking_node=node_id,
                missing_fields=["unsatisfactory_response_to_treatment"],
                message="Need response to chronic diarrhea treatment/management.",
                suggested_actions=[
                    Action(
                        code="CAPTURE_MANAGEMENT_RESPONSE",
                        label="Document whether response to treatment is unsatisfactory",
                        display={"role": "support", "badge": "info", "show_as_standalone": True, "sort_priority": 50},
                    )
                ],
            )
            ctx.log(node_id, "BLOCKED_MISSING_DATA", {"missing": ["unsatisfactory_response_to_treatment"]}, [dr])
            return NodeResult([dr])

        unsat = ctx.apply_override(node_id, "unsatisfactory_response_to_treatment", unsat)
        ctx.set("unsatisfactory_response_to_treatment", unsat)

        if unsat:
            actions: List[Output] = [
                Action(
                    code="CONSIDER_ADVICE_SERVICE",
                    label="Consider using an advice service before referring.",
                    details={"supported_by": ["Unsatisfactory response to treatment/management"]},
                    override_options={
                        "node": node_id,
                        "field": "unsatisfactory_response_to_treatment",
                        "allowed": [True, False],
                        "reason_required": True,
                    },
                    display={"role": "advisory", "badge": "warning", "show_as_standalone": True, "sort_priority": 55},
                )
            ]

            if ctx.get("advice_service_considered") is True:
                stop = Stop(
                    reason="Unsatisfactory response after management – refer for consultation/endoscopy.",
                    actions=[
                        Action(
                            code="REFER_FAILED_MANAGEMENT",
                            label="Refer for consultation/endoscopy due to failed management",
                            display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 9},
                        )
                    ],
                )
                ctx.log(node_id, "FAILED_MANAGEMENT_REFER", {"advice_service_considered": True}, actions + [stop])
                return NodeResult(actions + [stop])

            ctx.log(node_id, "FAILED_MANAGEMENT_ADVICE_FIRST", {"advice_service_considered": ctx.get("advice_service_considered")}, actions)
            return NodeResult(actions)

        stop = Stop(
            reason="Chronic diarrhea pathway complete – continue management in medical home.",
            actions=[
                Action(
                    code="CONTINUE_MEDICAL_HOME_CARE",
                    label="Continue management in the Patient Medical Home.",
                    display={"role": "primary_decision", "show_as_standalone": True, "sort_priority": 10},
                )
            ],
        )
        ctx.log(node_id, "PATHWAY_COMPLETE", {}, [stop])
        return NodeResult([stop])

    nodes["Management_Response"] = Node("Management_Response", node_management_response)

    return PathwayEngine(
        nodes=nodes,
        start_node="Suspected_Chronic_Diarrhea"
    )


# =========================================================
# RUNNER
# =========================================================

def run_chronic_diarrhea_pathway(patient_data: Dict[str, Any], overrides=None):

    engine = chronic_diarrhea_build_engine()

    ctx = Context(
        data=dict(patient_data),
        overrides=overrides or []
    )

    outputs = engine.run(ctx)

    return outputs, ctx.logs, ctx.overrides